### ISSUE TITLE
int8 or int16 support

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#106]
_From [johnqdel...@gmail.com](https://code.google.com/u/102688242252815981623/) on June 10, 2013 08:49:31_

Most of our numpy arrays are int8 or int16.
When will numexpr support int8 and int16 types?

Currently, the following code does not work:
aa=np.zeros(shape=10000000, dtype=np.byte)
ne.evaluate("where(aa=1,2,0)", out=aa)

Error message:
TypeError: Iterator requested dtype could not be cast from dtype('int32') to dtype('int8'), the operand 0 dtype, according to the rule 'safe'

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=106_

**Comment by robbmcleod** [comment]
Present and working in NE3 branch.
