### ISSUE TITLE
Add support for Yeppp!

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#113]
_From [yury.v.zaytsev](https://code.google.com/u/yury.v.zaytsev/) on August 29, 2013 17:22:37_

Please provide any additional information below. Yeppp! is a very fast and accurate numerics library, and it would be very nice if numexpr supported it just as it supports MKL for fast math: http://www.yeppp.info/home http://www.yeppp.info/home/yeppp-performance-numbers http://docs.yeppp.info/c/modules.html Thanks!

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=113_

**Comment by robbmcleod** [comment]
This is an eventually target for the major revision 3 release, please refer to #262.
