### ISSUE TITLE
add min and max functions

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#120]
_From [adamdr...@gmail.com](https://code.google.com/u/117117358273856513679/) on December 02, 2013 23:31:39_

I've added min and max functions in a clone of numexpr, adamdryan-numexpr.

Hope it helps.

Thanks for all your hard work.  Great package!

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=120_

**Comment by brentp** [comment]
any() and all() would also be very useful.

**Comment by jennolsen84** [comment]
Seems like this is done, and can be closed?  https://github.com/pydata/numexpr/commit/78362db52fe580532fe2a1aadcaaf0a6578419d9

**Comment by robbmcleod** [comment]
Closing as per jennolsen84's suggestion.
