### ISSUE TITLE
expected gains with more threads not achieved

### ISSUE THREAD

**Issue by michaelchughes** [pydata/numexpr#129]
I'm trying to do an in-place exp() on a very large (1 million x 100) 2D array. I see some improvement when using multiple threads, but after about 2 or 4 threads performance does not improve further (and actually sometimes gets noticeably worse).  I suppose I can expect diminishing returns for such a simple operation, but I'm hoping to understand whether this performance is expected or if there's anything I can change about my install/config that would provide further improvements.

Code
```
X = np.random.rand(1e6, 100)
starttime = time.time()
for trial in range(10):
    ne.evaluate('exp(X)', out=X)
elapsedtime = time.time() - starttime
```

Machine A has 64 total cores. AMD 1400 MHz  Here are timing results. They are reproduceable across several runs, and the ranking is similar when I make the input array X several times bigger.

------------------------------- 1 cores
0.85 sec/trial, 10 trials
------------------------------- 2 cores
0.75 sec/trial, 10 trials
------------------------------- 4 cores
0.98 sec/trial, 10 trials
------------------------------- 8 cores
1.11 sec/trial, 10 trials
------------------------------- 16 cores
0.64 sec/trial, 10 trials

Machine B has 16 total cores. Intel 2300 MHz. Here are timing results.
------------------------------- 1 cores
1.06 sec/trial, 10 trials
------------------------------- 2 cores
0.58 sec/trial, 10 trials
------------------------------- 4 cores
0.43 sec/trial, 10 trials
------------------------------- 8 cores
0.49 sec/trial, 10 trials
------------------------------- 16 cores
0.55 sec/trial, 10 trials

PS: thanks for such an awesome library. Even now, my code is way faster than just using plain-vanilla numpy.

**Comment by FrancescAlted** [comment]
You are completely right.  By default, numexpr is set to the number of available cores (with a limit of 8). But selecting the number of threads that maximize the performance typically depends of the problem to solve as well as of the computer architecture and normally requires of some experimentation.
