### ISSUE TITLE
compilation and installation have a warning, importing fails

### ISSUE THREAD

**Issue by roberthoeppner** [pydata/numexpr#130]
I followed the instructions:

``` bash
python setup.py build
python setup.py install
```

The latter has two warnings:

``` bash
warning: no files found matching '*.cfg'
warning: no previously-included files found matching 'numexpr/__config__.py'
```

When running python and importing numexpr, I get an error:

``` bash
Enthought Canopy Python 2.7.6 | 64-bit | (default, Jan 29 2014, 17:09:48) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>import numpy as np
>>>import numexpr as ne
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numexpr/__init__.py", line 24, in <module>
    from __config__ import show as show_config, get_info
ImportError: No module named __config__
>>> 
```

**Comment by Wilfred** [comment]
I've just encountered the same issue on Linux. I ran `python setup.py build` and `python setup.py install` without problems.

Running the tests in the source directory fails:

```
~/src/numexpr-2.4 $ python -c "import numexpr; numexpr.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "numexpr/__init__.py", line 24, in <module>
    from __config__ import show as show_config, get_info
ImportError: No module named __config__
~/src/numexpr-2.4 $ cd
~ $ python -c "import numexpr; numexpr.test()"
# works!
```

**Comment by davidedelvento** [comment]
Wilfred, it looks like they don't look at closed tickets, let me know if you open another one.

**Comment by avalentino** [comment]
@Wilfred trying to run the rest from within the source code directory gives an error because python tries to import the local copy of numexpr and not the installed one. This is an expected behaviour and it is OK IMHO as long as the test works if you run it from any other folder.

**Comment by msgoff** [comment]
avalentino - Thank you for posting your comment. That worked for me.
