### ISSUE TITLE
Numexpr: Attribute error

### ISSUE THREAD

**Issue by marcjofre** [pydata/numexpr#159]
Hi,

I have been working with numexpr and pyTables. While generating the compiled program with nuitka we have identified an attribute error:

File "D:\WinPython-64bit-2.7.6.3\python-2.7.6.amd64\Lib\site-packages\numexpr\
cpuinfo.py", line 96, in __getattr__
    raise AttributeError,name
AttributeError: is_AMD

In code:
def __getattr__(self,name):
        if not name.startswith('_'):
            if hasattr(self,'_'+name):
                attr = getattr(self,'_'+name)
                if type(attr) is types.MethodType:
                    return lambda func=self._try_call,attr=attr : func(attr)
            else:
                return lambda : None
        raise AttributeError,name

We have identified a posible solution replacing: if type(attr) is types.MethodType:
By: if inspect.ismethod(attr):

Best regards,

Marc

**Comment by FrancescAlted** [comment]
Fixed in rev a65f06d.  Gràcies!
