### ISSUE TITLE
Error: test_multiprocess

### ISSUE THREAD

**Issue by Arbitel** [pydata/numexpr#160]
I get the following error while doing the numexpr.test().

======================================================================
ERROR: test_multiprocess (numexpr.tests.test_numexpr.test_subprocess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\numexpr-2.4.1.dev-py2.7-win-amd64.egg\nume
xpr\tests\test_numexpr.py", line 839, in test_multiprocess
    ps.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_li
ne
    is not going to be frozen to produce a Windows executable.''')
RuntimeError:
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

I compiled it in Python 2.7.6 MSC v.1600 64 bit.

**Comment by FrancescAlted** [comment]
This seems too specific for `freeze`.  Closing.
