### ISSUE TITLE
Support thread count variable OMP_NUM_THREADS

### ISSUE THREAD

**Issue by StephanErb** [pydata/numexpr#161]
The variable `OMP_NUM_THREADS` is somewhat the gold standard to configure the thread count of an application. Similar to tools like OpenBlas, numexpr should support this variable as a fallback method to its custom variable `NUMEXPR_NUM_THREADS`. 

By supporting  `OMP_NUM_THREADS` it is easier for operators to control all libaries and applications at once.

**Comment by FrancescAlted** [comment]
Agreed.  Pull requests are very welcome.

**Comment by FrancescAlted** [comment]
This was fixed by #175, so closing.
