### ISSUE TITLE
add support for link option rpath

### ISSUE THREAD

**Issue by nbecker** [pydata/numexpr#164]
If you use MKL, likely you want to use:

in setup.py:
                'extra_link_args' : ['-Wl,-rpath,/opt/intel/composerxe/mkl/lib/intel64:/opt/intel/composer_xe_2013.3.163/compiler/lib/intel64']

**Comment by FrancescAlted** [comment]
Configuration for linking with MKL is in the 'site.cfg.example'.  Could you please provide a way to compile with proper (library_dirs, include_dirs, mkl_libs) for your scenario.  I will make sure to add an entry as an example for others.

**Comment by FrancescAlted** [comment]
Uh, sorry, you mean a way to find the MKL libraries during execution.  The typical LD_LIBRARY_PATH environment variable is not enough for you?

**Comment by nbecker** [comment]
It's not my preferred option, although it would work.

On Tue, Apr 14, 2015 at 8:06 AM, FrancescAlted <notifications@github.com>
wrote:

> Uh, sorry, you mean a way to find the MKL libraries during execution. The
> typical LD_LIBRARY_PATH environment variable is not enough for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/numexpr/issues/164#issuecomment-92783905>.
>



-- 
*Those who don't understand recursion are doomed to repeat it*

**Comment by FrancescAlted** [comment]
Not going to use platform-dependent paths in setup.py, so closing.
