### ISSUE TITLE
slice not supported?

### ISSUE THREAD

**Issue by nbecker** [pydata/numexpr#165]
import numexpr as ne
import numpy as np

u = np.ones (100, dtype=complex)
ne.evaluate ('abs(u[::2])')
home/nbecker/.local/lib/python2.7/site-packages/numexpr-2.4-py2.7-linux-x86_64.egg/numexpr/necompiler.pyc in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)
    710     expr_key = (ex, tuple(sorted(context.items())))
    711     if expr_key not in _names_cache:
--> 712         _names_cache[expr_key] = getExprNames(ex, context)
    713     names, ex_uses_vml = _names_cache[expr_key]
    714     # Get the arguments based on the names.

/home/nbecker/.local/lib/python2.7/site-packages/numexpr-2.4-py2.7-linux-x86_64.egg/numexpr/necompiler.pyc in getExprNames(text, context)
    631 
    632 def getExprNames(text, context):
--> 633     ex = stringToExpression(text, {}, context)
    634     ast = expressionToAST(ex)
    635     input_order = getInputOrder(ast, None)

/home/nbecker/.local/lib/python2.7/site-packages/numexpr-2.4-py2.7-linux-x86_64.egg/numexpr/necompiler.pyc in stringToExpression(s, types, context)
    243         names.update(expressions.functions)
    244         # now build the expression
--> 245         ex = eval(c, names)
    246         if expressions.isConstant(ex):
    247             ex = expressions.ConstantNode(ex, expressions.getKind(ex))

<expr> in <module>()

TypeError: 'VariableNode' object has no attribute '__getitem__'

**Comment by FrancescAlted** [comment]
No, slicing is not supported and there are no plans to do it (i.e. far beyond the goals of numexpr).

**Comment by arsenovic** [comment]
bummer

**Comment by wolfgang-noichl** [comment]
It would be also quite useless, I think? Slicing is basically for free, so it won't profit from parallelization etc (doesn't touch the data...), and you can do stuff like this:
```python
u = np.ones (100, dtype=complex)
i = ne.evaluate ('abs(u)', {'u': u[::2]})
```
