### ISSUE TITLE
Install failed with numexpr 2.4

### ISSUE THREAD

**Issue by duytrung** [pydata/numexpr#168]
I tried to update the package but there was error:

```

C:\Python3\Scripts>pip install -U numexpr
Collecting numexpr from https://pypi.python.org/packages/source/n/numexpr/numexpr-2.4.tar.gz#md5=df7e8d9e9dbb145b56d43c4
65c2bf854
  Downloading numexpr-2.4.tar.gz (84kB)
    100% |################################| 86kB 436kB/s
Requirement already up-to-date: numpy>=1.6 in c:\python3\lib\site-packages (from numexpr)
Installing collected packages: numexpr
  Found existing installation: numexpr 2.3.1
    DEPRECATION: Uninstalling a distutils installed project (numexpr) has been deprecated and will be removed in a futur
e version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numexpr-2.3.1:
      Successfully uninstalled numexpr-2.3.1
  Running setup.py install for numexpr
    Appending numexpr.tests configuration to numexpr
    Ignoring attempt to set 'name' (from 'numexpr' to 'numexpr.tests')
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    build_src
    building py_modules sources
    building extension "numexpr.interpreter" sources
    build_src: building npy-pkg config files
    customize Mingw32CCompiler
    customize Mingw32CCompiler using build_ext
    customize Mingw32CCompiler
    customize Mingw32CCompiler using build_ext
    building 'numexpr.interpreter' extension
    compiling C sources
    C compiler: gcc -O2 -Wall -Wstrict-prototypes
    compile options: '-D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include
 -IC:\Python3\include -c'
    extra options: '-funroll-all-loops'
    gcc -O2 -Wall -Wstrict-prototypes -D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:
\Python3\include -IC:\Python3\include -c numexpr\win32\pthread.c -o build\temp.win32-3.4\Release\numexpr\win32\pthread.o
 -funroll-all-loops
    Found executable c:\Python\Scripts\gcc.bat
    Warning: Assuming default configuration (numexpr\tests/{setup_tests,setup}.py was not found)compiling C++ sources
    C compiler: g++ -O2 -Wall
    compile options: '-D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include
 -IC:\Python3\include -c'
    extra options: '-funroll-all-loops'
    g++ -O2 -Wall -D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include -IC
:\Python3\include -c numexpr\interpreter.cpp -o build\temp.win32-3.4\Release\numexpr\interpreter.o -funroll-all-loops
    Found executable c:\Python\Scripts\g++.bat
    g++ -O2 -Wall -D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include -IC
:\Python3\include -c numexpr\module.cpp -o build\temp.win32-3.4\Release\numexpr\module.o -funroll-all-loops
    g++ -O2 -Wall -D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include -IC
:\Python3\include -c numexpr\numexpr_object.cpp -o build\temp.win32-3.4\Release\numexpr\numexpr_object.o -funroll-all-lo
ops
    g++ -shared build\temp.win32-3.4\Release\numexpr\win32\pthread.o build\temp.win32-3.4\Release\numexpr\interpreter.o
build\temp.win32-3.4\Release\numexpr\module.o build\temp.win32-3.4\Release\numexpr\numexpr_object.o -LC:\Python3\libs -L
C:\Python3\PCbuild -lm -lpython34 -lmsvcr100 -o build\lib.win32-3.4\numexpr\interpreter.pyd
    error: Command "g++ -shared build\temp.win32-3.4\Release\numexpr\win32\pthread.o build\temp.win32-3.4\Release\numexp
r\interpreter.o build\temp.win32-3.4\Release\numexpr\module.o build\temp.win32-3.4\Release\numexpr\numexpr_object.o -LC:
\Python3\libs -LC:\Python3\PCbuild -lm -lpython34 -lmsvcr100 -o build\lib.win32-3.4\numexpr\interpreter.pyd" failed with
 exit status 1
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/libpython34.a when searching for -lpython34
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/python34.lib when searching for -lpython34
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs\libpython34.a when searching for -lpython34
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/libpython34.a when searching for -lpython34
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/python34.lib when searching for -lpython34
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs\python34.lib when searching for -lpython34
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpyt
hon34
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/libmsvcr100.a when searching for -lmsvcr100
    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs\libmsvcr100.a when searching for -lmsvcr100
    collect2.exe: error: ld returned 1 exit status
    Complete output from command C:\Python3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\eep1\\AppDat
a\\Local\\Temp\\pip-build-ozkptyo9\\numexpr\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().rep
lace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\eep1\AppData\Local\Temp\pip-3tlp3_5j-record\install-re
cord.txt --single-version-externally-managed --compile:
    Appending numexpr.tests configuration to numexpr

    Ignoring attempt to set 'name' (from 'numexpr' to 'numexpr.tests')

    running install

    running build

    running config_cc

    unifing config_cc, config, build_clib, build_ext, build commands --compiler options

    running config_fc

    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options

    running build_src

    build_src

    building py_modules sources

    creating build

    creating build\src.win32-3.4

    creating build\src.win32-3.4\numexpr

    building extension "numexpr.interpreter" sources

    build_src: building npy-pkg config files

    running build_py

    creating build\lib.win32-3.4

    creating build\lib.win32-3.4\numexpr

    copying numexpr\cpuinfo.py -> build\lib.win32-3.4\numexpr

    copying numexpr\expressions.py -> build\lib.win32-3.4\numexpr

    copying numexpr\necompiler.py -> build\lib.win32-3.4\numexpr

    copying numexpr\utils.py -> build\lib.win32-3.4\numexpr

    copying numexpr\version.py -> build\lib.win32-3.4\numexpr

    copying numexpr\__init__.py -> build\lib.win32-3.4\numexpr

    copying build\src.win32-3.4\numexpr\__config__.py -> build\lib.win32-3.4\numexpr

    creating build\lib.win32-3.4\numexpr\tests

    copying .\numexpr\tests\test_numexpr.py -> build\lib.win32-3.4\numexpr\tests

    copying .\numexpr\tests\__init__.py -> build\lib.win32-3.4\numexpr\tests

    Skipping implicit fixer: buffer

    Skipping implicit fixer: idioms

    Skipping implicit fixer: set_literal

    Skipping implicit fixer: ws_comma

    running build_ext

    customize Mingw32CCompiler

    customize Mingw32CCompiler using build_ext

    customize Mingw32CCompiler

    customize Mingw32CCompiler using build_ext

    building 'numexpr.interpreter' extension

    compiling C sources

    C compiler: gcc -O2 -Wall -Wstrict-prototypes



    creating build\temp.win32-3.4

    creating build\temp.win32-3.4\Release

    creating build\temp.win32-3.4\Release\numexpr

    creating build\temp.win32-3.4\Release\numexpr\win32

    compile options: '-D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include
 -IC:\Python3\include -c'

    extra options: '-funroll-all-loops'

    gcc -O2 -Wall -Wstrict-prototypes -D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:
\Python3\include -IC:\Python3\include -c numexpr\win32\pthread.c -o build\temp.win32-3.4\Release\numexpr\win32\pthread.o
 -funroll-all-loops

    Found executable c:\Python\Scripts\gcc.bat

    Warning: Assuming default configuration (numexpr\tests/{setup_tests,setup}.py was not found)compiling C++ sources

    C compiler: g++ -O2 -Wall



    compile options: '-D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include
 -IC:\Python3\include -c'

    extra options: '-funroll-all-loops'

    g++ -O2 -Wall -D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include -IC
:\Python3\include -c numexpr\interpreter.cpp -o build\temp.win32-3.4\Release\numexpr\interpreter.o -funroll-all-loops

    Found executable c:\Python\Scripts\g++.bat

    g++ -O2 -Wall -D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include -IC
:\Python3\include -c numexpr\module.cpp -o build\temp.win32-3.4\Release\numexpr\module.o -funroll-all-loops

    g++ -O2 -Wall -D__MSVCRT_VERSION__=0x1000 -IC:\Python3\lib\site-packages\numpy\core\include -IC:\Python3\include -IC
:\Python3\include -c numexpr\numexpr_object.cpp -o build\temp.win32-3.4\Release\numexpr\numexpr_object.o -funroll-all-lo
ops

    g++ -shared build\temp.win32-3.4\Release\numexpr\win32\pthread.o build\temp.win32-3.4\Release\numexpr\interpreter.o
build\temp.win32-3.4\Release\numexpr\module.o build\temp.win32-3.4\Release\numexpr\numexpr_object.o -LC:\Python3\libs -L
C:\Python3\PCbuild -lm -lpython34 -lmsvcr100 -o build\lib.win32-3.4\numexpr\interpreter.pyd

    error: Command "g++ -shared build\temp.win32-3.4\Release\numexpr\win32\pthread.o build\temp.win32-3.4\Release\numexp
r\interpreter.o build\temp.win32-3.4\Release\numexpr\module.o build\temp.win32-3.4\Release\numexpr\numexpr_object.o -LC:
\Python3\libs -LC:\Python3\PCbuild -lm -lpython34 -lmsvcr100 -o build\lib.win32-3.4\numexpr\interpreter.pyd" failed with
 exit status 1

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/libpython34.a when searching for -lpython34

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/python34.lib when searching for -lpython34

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs\libpython34.a when searching for -lpython34

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/libpython34.a when searching for -lpython34

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/python34.lib when searching for -lpython34

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs\python34.lib when searching for -lpython34

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpyt
hon34

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs/libmsvcr100.a when searching for -lmsvcr100

    c:/python/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompat
ible C:\Python3\libs\libmsvcr100.a when searching for -lmsvcr100

    collect2.exe: error: ld returned 1 exit status

    ----------------------------------------
    Rolling back uninstall of numexpr
    Command "C:\Python3\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\eep1\\AppData\\Local\\Temp\\pip-
build-ozkptyo9\\numexpr\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'),
__file__, 'exec'))" install --record C:\Users\eep1\AppData\Local\Temp\pip-3tlp3_5j-record\install-record.txt --single-ve
rsion-externally-managed --compile" failed with error code 1 in C:\Users\eep1\AppData\Local\Temp\pip-build-ozkptyo9\nume
xpr

```

Kind regards

**Comment by FrancescAlted** [comment]
Hmm, this seems a problem of MingW32 linking with the windows runtime.  Is your MinGW32 compiler to compile things like numpy?

**Comment by andreabedini** [comment]
it looks to me that @duytrung's python is build with a different compiler than the one he's trying to use (under `c:/python/mingw/bin`). my 2c

**Comment by craigpfeifer** [comment]
Having similar issue on OSX v10.10.5:

MM208463-PC:FY16 cpfeifer$ pip3 install --upgrade numexpr
Collecting numexpr
  Using cached numexpr-2.4.5.tar.gz
Requirement already up-to-date: numpy>=1.6 in /usr/local/lib/python3.4/site-packages (from numexpr)
Installing collected packages: numexpr
  Running setup.py install for numexpr
    Complete output from command /usr/local/opt/python3/bin/python3.4 -c "import setuptools, tokenize;__file__='/private/var/folders/hc/9kgl2x9n7ds69k790f7327381j69yc/T/pip-build-g3wts72f/numexpr/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/hc/9kgl2x9n7ds69k790f7327381j69yc/T/pip-o6xmlp9r-record/install-record.txt --single-version-externally-managed --compile:
    Appending numexpr.tests configuration to numexpr
    Ignoring attempt to set 'name' (from 'numexpr' to 'numexpr.tests')
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.macosx-10.10-x86_64-3.4
    creating build/src.macosx-10.10-x86_64-3.4/numexpr
    building extension "numexpr.interpreter" sources
    build_src: building npy-pkg config files
    running build_py
    creating build/lib.macosx-10.10-x86_64-3.4
    creating build/lib.macosx-10.10-x86_64-3.4/numexpr
    copying numexpr/__init__.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr
    copying numexpr/cpuinfo.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr
    copying numexpr/expressions.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr
    copying numexpr/necompiler.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr
    copying numexpr/utils.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr
    copying numexpr/version.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr
    copying build/src.macosx-10.10-x86_64-3.4/numexpr/__config__.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr
    creating build/lib.macosx-10.10-x86_64-3.4/numexpr/tests
    copying ./numexpr/tests/__init__.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr/tests
    copying ./numexpr/tests/test_numexpr.py -> build/lib.macosx-10.10-x86_64-3.4/numexpr/tests
    Skipping implicit fixer: buffer
    Skipping implicit fixer: idioms
    Skipping implicit fixer: set_literal
    Skipping implicit fixer: ws_comma
    running build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    building 'numexpr.interpreter' extension
    compiling C++ sources
    C compiler: clang++ -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall

    creating build/temp.macosx-10.10-x86_64-3.4
    creating build/temp.macosx-10.10-x86_64-3.4/numexpr
    compile options: '-I/usr/local/lib/python3.4/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c'
    extra options: '-funroll-all-loops'
    clang++: numexpr/module.cpp
    clang: warning: optimization flag '-funroll-all-loops' is not supported
    clang: warning: argument unused during compilation: '-funroll-all-loops'
    In file included from numexpr/module.cpp:12:
    In file included from numexpr/module.hpp:12:
    In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:
    /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    1 warning generated.
    clang++: numexpr/numexpr_object.cpp
    clang: warning: optimization flag '-funroll-all-loops' is not supported
    clang: warning: argument unused during compilation: '-funroll-all-loops'
    In file included from numexpr/numexpr_object.cpp:10:
    In file included from numexpr/module.hpp:12:
    In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:
    /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    numexpr/numexpr_object.cpp:97:30: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        static char *kwlist[] = {"signature", "tempsig",
                                 ^
    numexpr/numexpr_object.cpp:97:43: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        static char *kwlist[] = {"signature", "tempsig",
                                              ^
    numexpr/numexpr_object.cpp:98:30: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
                                 "program",  "constants",
                                 ^
    numexpr/numexpr_object.cpp:98:42: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
                                 "program",  "constants",
                                             ^
    numexpr/numexpr_object.cpp:99:30: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
                                 "input_names", NULL};
                                 ^
    numexpr/numexpr_object.cpp:360:6: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        {"signature", T_OBJECT_EX, offsetof(NumExprObject, signature), READONLY, NULL},
         ^
    numexpr/numexpr_object.cpp:361:6: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        {"constsig", T_OBJECT_EX, offsetof(NumExprObject, constsig), READONLY, NULL},
         ^
    numexpr/numexpr_object.cpp:362:6: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        {"tempsig", T_OBJECT_EX, offsetof(NumExprObject, tempsig), READONLY, NULL},
         ^
    numexpr/numexpr_object.cpp:363:6: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        {"fullsig", T_OBJECT_EX, offsetof(NumExprObject, fullsig), READONLY, NULL},
         ^
    numexpr/numexpr_object.cpp:365:6: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        {"program", T_OBJECT_EX, offsetof(NumExprObject, program), READONLY, NULL},
         ^
    numexpr/numexpr_object.cpp:366:6: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        {"constants", T_OBJECT_EX, offsetof(NumExprObject, constants),
         ^
    numexpr/numexpr_object.cpp:368:6: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        {"input_names", T_OBJECT, offsetof(NumExprObject, input_names), 0, NULL},
         ^
    13 warnings generated.
    clang++: numexpr/interpreter.cpp
    clang: warning: optimization flag '-funroll-all-loops' is not supported
    clang: warning: argument unused during compilation: '-funroll-all-loops'
    In file included from numexpr/interpreter.cpp:10:
    In file included from numexpr/module.hpp:12:
    In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:
    /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:77:14: error: typedef redefinition with different types ('char' vs 'int8_t' (aka 'signed char'))
    typedef char int_fast8_t;
                 ^
    /usr/include/stdint.h:40:27: note: previous definition is here
    typedef int8_t            int_fast8_t;
                              ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:92:13: error: typedef redefinition with different types ('int' vs '__darwin_intptr_t' (aka 'long'))
    typedef int intptr_t;
                ^
    /usr/include/sys/_types/_intptr_t.h:30:27: note: previous definition is here
    typedef __darwin_intptr_t       intptr_t;
                                    ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:101:22: error: typedef redefinition with different types ('unsigned int' vs 'unsigned long')
    typedef unsigned int uintptr_t;
                         ^
    /usr/include/sys/_types/_uintptr_t.h:30:24: note: previous definition is here
    typedef unsigned long           uintptr_t;
                                    ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:106:28: error: typedef redefinition with different types ('long long' vs 'long')
    typedef __STDINT_LONGLONG  intmax_t;
                               ^
    /usr/include/_types/_intmax_t.h:32:25: note: previous definition is here
    typedef __INTMAX_TYPE__ intmax_t;
                            ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:107:38: error: typedef redefinition with different types ('unsigned long long' vs 'unsigned long')
    typedef unsigned __STDINT_LONGLONG   uintmax_t;
                                         ^
    /usr/include/_types/_uintmax_t.h:32:26: note: previous definition is here
    typedef __UINTMAX_TYPE__ uintmax_t;
                             ^
    numexpr/interpreter.cpp:892:22: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
                errmsg = "Parallel engine doesn't support reduction yet";
                         ^
    2 warnings and 5 errors generated.
    Warning: Assuming default configuration (numexpr/tests/{setup_tests,setup}.py was not found)error: Command "clang++ -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/lib/python3.4/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c numexpr/interpreter.cpp -o build/temp.macosx-10.10-x86_64-3.4/numexpr/interpreter.o -funroll-all-loops" failed with exit status 1
    clang: warning: optimization flag '-funroll-all-loops' is not supported
    clang: warning: argument unused during compilation: '-funroll-all-loops'
    In file included from numexpr/interpreter.cpp:10:
    In file included from numexpr/module.hpp:12:
    In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:
    /usr/local/lib/python3.4/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:77:14: error: typedef redefinition with different types ('char' vs 'int8_t' (aka 'signed char'))
    typedef char int_fast8_t;
                 ^
    /usr/include/stdint.h:40:27: note: previous definition is here
    typedef int8_t            int_fast8_t;
                              ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:92:13: error: typedef redefinition with different types ('int' vs '__darwin_intptr_t' (aka 'long'))
    typedef int intptr_t;
                ^
    /usr/include/sys/_types/_intptr_t.h:30:27: note: previous definition is here
    typedef __darwin_intptr_t       intptr_t;
                                    ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:101:22: error: typedef redefinition with different types ('unsigned int' vs 'unsigned long')
    typedef unsigned int uintptr_t;
                         ^
    /usr/include/sys/_types/_uintptr_t.h:30:24: note: previous definition is here
    typedef unsigned long           uintptr_t;
                                    ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:106:28: error: typedef redefinition with different types ('long long' vs 'long')
    typedef __STDINT_LONGLONG  intmax_t;
                               ^
    /usr/include/_types/_intmax_t.h:32:25: note: previous definition is here
    typedef __INTMAX_TYPE__ intmax_t;
                            ^
    In file included from numexpr/interpreter.cpp:40:
    In file included from numexpr/str-two-way.hpp:48:
    numexpr/win32/stdint.h:107:38: error: typedef redefinition with different types ('unsigned long long' vs 'unsigned long')
    typedef unsigned __STDINT_LONGLONG   uintmax_t;
                                         ^
    /usr/include/_types/_uintmax_t.h:32:26: note: previous definition is here
    typedef __UINTMAX_TYPE__ uintmax_t;
                             ^
    numexpr/interpreter.cpp:892:22: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
                errmsg = "Parallel engine doesn't support reduction yet";
                         ^
    2 warnings and 5 errors generated.

    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.4 -c "import setuptools, tokenize;__file__='/private/var/folders/hc/9kgl2x9n7ds69k790f7327381j69yc/T/pip-build-g3wts72f/numexpr/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/hc/9kgl2x9n7ds69k790f7327381j69yc/T/pip-o6xmlp9r-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/hc/9kgl2x9n7ds69k790f7327381j69yc/T/pip-build-g3wts72f/numexpr

**Comment by craigpfeifer** [comment]
Resolved! Thanks!
