### ISSUE TITLE
Ubuntu 12.04.4 LTS error in installation

### ISSUE THREAD

**Issue by vinumanikandan** [pydata/numexpr#174]
sudo apt-get install python-numexpr

Error:
python -c "import numexpr; numexpr.test()"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   1.4.2
NumPy version:     1.9.2
Python version:    2.7.3 (default, Feb 27 2014, 19:58:35) 
[GCC 4.6.3]
Platform:          linux2-x86_64
AMD/Intel CPU?     True
VML available?     False
Detected cores:    64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...F......F..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
======================================================================
FAIL: test_reductions (numexpr.tests.test_numexpr.test_numexpr1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/numexpr/tests/test_numexpr.py", line 76, in test_reductions
    assert_equal(evaluate("sum(x+2,axis=0)"), sum(x+2,axis=0))
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 275, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array(201000.0000001749)
 y: array(200999.99999999983)

======================================================================
FAIL: test_reductions (numexpr.tests.test_numexpr.test_numexpr2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/numexpr/tests/test_numexpr.py", line 76, in test_reductions
    assert_equal(evaluate("sum(x+2,axis=0)"), sum(x+2,axis=0))
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 275, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 739, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array(201000.0000001749)
 y: array(200999.99999999983)

----------------------------------------------------------------------
Ran 5145 tests in 2.324s

FAILED (failures=2)

**Comment by FrancescAlted** [comment]
Uh, Ubuntu 12.04 and numexpr 1.4.2 are pretty old, so I don't think we are going to fix this.  Sorry guy.
