### ISSUE TITLE
Numexpr fails to install from source

### ISSUE THREAD

**Issue by EricR86** [pydata/numexpr#176]
From a fresh install (or virtualenv), numexpr fails to install from source. The following error occurs:
```shell
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 223, in <module>
    setup_package()
  File "setup.py", line 62, in setup_package
    from numpy.distutils.core import setup
ImportError: No module named numpy.distutils.core
```

Specifically the Line 62 in setup.py (https://github.com/pydata/numexpr/blob/master/setup.py#L62) presumes numpy is already installed before even running `setup` itself. I doubt this was intended since numpy is also listed inside `setup_requires`.

This issue seems to be related to https://github.com/PyTables/PyTables/issues/454

**Comment by andreabedini** [comment]
Yes, setup.py should not import numpy (at least before checking it is installed). The typical way to go around this is to override the build_ext command. Numexpr should check what pytables and pandas do.

**Comment by trtm** [comment]
still fails to build and install from source... last working version for me is 2.4.3 ( ```pip install -v numexpr==2.4.3``` )

**Comment by FrancescAlted** [comment]
@trtm I would need a log to figure out what's going on.  BTW, I have fixed an install issue in PR #189.  Could you have a try?

**Comment by trtm** [comment]
this was fast. thank you. last "merge pull request #189" fixed it for me.

**Comment by FrancescAlted** [comment]
Great.  @EricR86 Do you think we can close this one?

**Comment by EricR86** [comment]
Unfortunately I can still easily reproduce this error. I just created a new virtualenv with no python packages installed. I then tried to install numexpr from source using the newly uploaded 2.4.6 to PyPI and got the identical error posted earlier:

```python
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 223, in <module>
    setup_package()
  File "setup.py", line 62, in setup_package
    from numpy.distutils.core import setup
ImportError: No module named numpy.distutils.core
```

This presumes that 2.4.6 includes the fix from pull request #189 (which I assume it does).

**Comment by andreabedini** [comment]
@EricR86 `python setup.py install` doesn't install the dependencies and you have to do it yourself. Try `pip install .`

**Comment by FrancescAlted** [comment]
Yeah, I think the workaround by @andreabedini is fine.  I think we can close this one.

**Comment by EricR86** [comment]
I ran a bunch of tests and I can confirm that I can install this through pip. Though technically, numexpr still cannot be installed from source. If possible I'd suggest changing this to a "wontfix".

**Comment by FrancescAlted** [comment]
Ok.  Wontfix it is :)
