### ISSUE TITLE
Compilation fails on OSX

### ISSUE THREAD

**Issue by matthew-brett** [pydata/numexpr#190]
I was just trying to build wheels for the 2.4.5 release, but the compilation fails with:

```
clang++: numexpr/interpreter.cpp
In file included from numexpr/interpreter.cpp:40:
In file included from numexpr/str-two-way.hpp:48:
numexpr/win32/stdint.h:77:14: error: typedef redefinition with different types ('char' vs 'int8_t' (aka 'signed char'))
typedef char int_fast8_t;
             ^
/usr/include/stdint.h:40:27: note: previous definition is here
typedef int8_t            int_fast8_t;
```

Full log is here : https://travis-ci.org/MacPython/numexpr-wheels/jobs/88847419

It looks like the OSX build is picking up the win32 headers?

**Comment by FrancescAlted** [comment]
Matthew, that should be fixed in recently released 2.4.6.

Francesc

2015-11-02 19:51 GMT+01:00 Matthew Brett <notifications@github.com>:

> I was just trying to build wheels for the 2.4.5 release, but the
> compilation fails with:
>
> clang++: numexpr/interpreter.cpp
> In file included from numexpr/interpreter.cpp:40:
> In file included from numexpr/str-two-way.hpp:48:
> numexpr/win32/stdint.h:77:14: error: typedef redefinition with different types ('char' vs 'int8_t' (aka 'signed char'))
> typedef char int_fast8_t;
>              ^
> /usr/include/stdint.h:40:27: note: previous definition is here
> typedef int8_t            int_fast8_t;
>
> Full log is here :
> https://travis-ci.org/MacPython/numexpr-wheels/jobs/88847419
>
> It looks like the OSX build is picking up the win32 headers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/numexpr/issues/190>.
>



-- 
Francesc Alted

**Comment by matthew-brett** [comment]
Thanks for that.

Maybe, before a release, you could try triggering a build via a commit or
the web interface here?:

https://travis-ci.org/MacPython/numexpr-wheels

Instructions here:

https://github.com/MacPython/numexpr-wheels
​
I uploaded some wheels, but there are instructions on that page how to do
that, if you have the time.

**Comment by FrancescAlted** [comment]
Closing this as it seems that all Mac OSX issues are fixed now.
