### ISSUE TITLE
Math errors in version 2.4.4 in Windows 10

### ISSUE THREAD

**Issue by PeterKucirek** [pydata/numexpr#192]
I'm getting bizarre and random mathematical errors when running version 2.4.4 on a Windows 10 machine. For example, `exp(n)` is yielding *negative numbers* , or a call to `pandas.eval()` on a boolean expression will yield all False. Suffice to say, it is critically broken. What is even more frustrating is that the problem occurs randomly: I will run my program and it will crash in an early step; when I re-run it again, it will crash in a completely different step. 

I haven't had much luck reproducing the problem from a Notebook environment, however I have access to two Windows 10 machines and they both exhibited the same behaviour running the exact same code on the exact same version of `numexpr`. When I downgrade to Version 2.4.3, the problem completely goes away. Furthermore, version 2.4.4 works just fine on my Windows 7 machine, so this appears to be specific to Win 10. 

Any help would be much appreciated.

**Comment by FrancescAlted** [comment]
I have fixed some threading issues in latest release (2.4.6).  Can you try it?

**Comment by PeterKucirek** [comment]
I'm not able to install 2.4.6. I tried from `pip` with no success (it looks like a problem finding a C compiler: `AttributeError: MSVCCompiler instance has no attribute 'compiler_cxx'`), and `conda` cannot find it. Are there other options?

**Comment by Pekka4444** [comment]
I have this same problem in windows 10 while win 7 works just as fine. Sometimes it happens and sometimes not.

**Comment by FrancescAlted** [comment]
This smells the same as #185 and #188.  Please use the latest release (2.4.6) as this should be solved.

**Comment by Pekka4444** [comment]
The problem indeed does not appear in 2.4.6. Thank you.

**Comment by FrancescAlted** [comment]
Great.  Closing.
