### ISSUE TITLE
Non-deterministic calculating issue

### ISSUE THREAD

**Issue by slingyropert** [pydata/numexpr#193]
I don't know why this is happening but sometimes my evaluate gives 0.0 for the output of something that should be about 1.0 about 92 times in 3000 executions. I would love to get the right answer every time, if possible. My test code is

    from numexpr import evaluate
    import numpy as np
    
    failure = 0
    for n in range(3000):
        x = np.ones((1500, 1500), dtype=np.complex128)
        X = evaluate('x.real * x.real + x.imag * x.imag', local_dict={'x': x})
        if X[0, 0] < 0.5:
            failure += 1
    
    print('numexpr failed ' + str(failure) + ' times out of 3000')

My platform is Anaconda python=3.4 for Win64. The relevant package versions are
numexpr: 2.4.4-np19py34_p0 [mkl]
mkl:     11.1-np19py34_p1
numpy:   1.9.3-py34_p0     [mkl]

I have run this code on two different intel processors from two years ago and more like 7 years ago and I get the same behavior. The number of failures and their order are never the same.

**Comment by slingyropert** [comment]
I observe that this could be a duplicate of #192 as I am on Windows 10 and the problem goes away in 2.4.3.

**Comment by FrancescAlted** [comment]
Probably is the same issue that #192, yes.
