### ISSUE TITLE
Import error : import numexpr

### ISSUE THREAD

**Issue by Shekharrajak** [pydata/numexpr#196]
```
In [1]: import numexpr
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f31799291f6e> in <module>()
----> 1 import numexpr

/root/numexpr/numexpr/__init__.py in <module>()
     22 """
     23 
---> 24 from __config__ import show as show_config, get_info
     25 
     26 if get_info('mkl'):

ImportError: No module named __config__
```
Why I am getting this error ?

**Comment by FrancescAlted** [comment]
This largely depends on which platform are you and which distribution are you using.  How did you installed numexpr, and which version and OS are you using?

**Comment by Shekharrajak** [comment]
After doing this : 
` apt-get install python-numexpr` and restarting the terminal it is working fine .
Thanks.

**Comment by lucgiffon** [comment]
Hello, I get the same error on running my project in a fresh environment.

I am using the following configuration:

- `numexpr` version:

`numexpr==2.7.3
`
- OS configuration:

```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
```

python version:

`Python 3.10.4
`

Installed via:

`pip install lightonml
`
which has dependency over `numexpr`.

**Comment by robbmcleod** [comment]
@lucgiffon, NumExpr 2.7.3 doesn't support Python 3.10. Try using NumExpr 2.8.1?
