### ISSUE TITLE
Too large constant (<type 'dict'> 390)

### ISSUE THREAD

**Issue by marcjofre** [pydata/numexpr#197]
Hi all,

While nuitka compiling  a python project which makes extensive use of tables (pytables):

WARNING:Too large constant (<type 'dict'> 390) encountered at D:\WinPytho
n-64bit-2.7.6.3\python-2.7.6.amd64\Lib\site-packages\tables\_past.py:63.

Do not hesitate to contact me if any doubt or information

**Comment by FrancescAlted** [comment]
Hmm, not sure what the problem is, but at any rate, this seems related to PyTables, not numexpr.  Please feel free to open an issue there.
