### ISSUE TITLE
numexpr and mutiprocessing package

### ISSUE THREAD

**Issue by ghost** [pydata/numexpr#204]
Hi,

Is there any interest by including numexpr.evaluate() into a sub-process of multiprocessing package.
Idea is to sub-split by processors.

Or numexpr alreadyachieves this ?

**Comment by FrancescAlted** [comment]
Numexpr already supports multi-threading:

https://github.com/pydata/numexpr/blob/master/numexpr/utils.py#L77

which already achieves pretty good performance on multi-processors.

Which advantage would bring using the multiprocessing package?

**Comment by arita291** [comment]
Hi,
Just wondering, if this makes any sense given the internal archicture of numexpr.

I see performance improvement when using map.reduce when the sub-process calculate the sum (by numexpr) and result of the sum is provided to the main process.

If all the sub-vector should be passed into the main process, there is probably an overhead of mem copy......

**Comment by robbmcleod** [comment]
That sounds unlikely, subprocess and the python multiprocessing libraries have a lot of overhead.  Numexpr makes no use of multiprocessing, and I really don't like the multiprocessing library.  It suffers from a lot of limitations due to the limitations of pickle, and has very different behavour on Windows versus Linux, and often an enormous amount of overhead.

Are you setting n_threads to X in your main process and the subprocess has >X threads by default?

**Comment by gdementen** [comment]
It is possible @arita291 is seeing a speed up, given that aggregate functions in numexpr are NOT multi-threaded (as opposed to element-wise operations).

**Comment by FrancescAlted** [comment]
Yes, I think @gdementen is right.  The solution would be to implement multi-threading for the aggregate functions, but no one did that yet.

**Comment by robbmcleod** [comment]
I did some speed tests, numexpr is single threaded and slower than
numpy.sum() when doing reduction algorithms.

In NumExpr_run():

    /* Reductions do not support parallel execution yet */
    if (is_reduction) {
        gs.force_serial = 1;
    }

The code looks like someone made some progress towards multi-threading it
but didn't finish.  The GIL is turned off for the loops that point to
vm_engine_iter_task and vm_engine_iter_outer_reduce_task, for example.

I guess it can be added to the TODO list.

On Thu, Feb 18, 2016 at 8:34 PM, FrancescAlted <notifications@github.com>
wrote:

> Yes, I think @gdementen <https://github.com/gdementen> is right. The
> solution would be to implement multi-threading for the aggregate functions,
> but no one did that yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/numexpr/issues/204#issuecomment-185882679>.
>



-- 
Robert McLeod, Ph.D.
Center for Cellular Imaging and Nano Analytics (C-CINA)
Biozentrum der Universität Basel
Mattenstrasse 26, 4058 Basel
Work: +41.061.387.3225
robert.mcleod@unibas.ch
robert.mcleod@bsse.ethz.ch <robert.mcleod@ethz.ch>
robbmcleod@gmail.com

**Comment by robbmcleod** [comment]
NumExpr 3.0 now support pickling of the `NumExpr` object, and has been tested by `concurrent.futures`, so closing.  An example can be found in the test suite.
