### ISSUE TITLE
Numpy Histogramdd support?

### ISSUE THREAD

**Issue by tibbon** [pydata/numexpr#205]
Any chance of working in more efficient multi-dimensional histograms?

**Comment by robbmcleod** [comment]
I doubt it as numexpr focuses on principle operations.  Such a thing as binning data isn't on the radar at the moment, as dimension reduction operations are tougher to multi-thread efficiently.  A multi-dimensional histogram would have to be implemented by hand in C, I think, probably using something like the GNU Scientific Library implementation as a template.

What I would suggest is you take a look at Numba to write such an algorithm.  It's a just-in-time compiler that can translate pure python into efficient byte-code.  That may be more practical.
