### ISSUE TITLE
Out directly on indexed ndarray with mask

### ISSUE THREAD

**Issue by JGoutin** [pydata/numexpr#206]
Hello,

"data1", "data2" and "mask" have the same shape a "result".
mask is a boolean mask for indexing.

Out on an intermediate ndarray and copy on final indexed array: work good. 
```python
    result = np.zeros((100, 100))  # Create result array with good shape
    d1, d2 = data1[mask], data2[mask]  # Select data to compute only with mask
    result[mask] = ne.evaluate('d1**d2')  # compute with numexpr
```

Out directly on final indexed array: don't work.
```python
    result = np.zeros((100, 100))  # Create result array with good shape
    d1, d2 = data1[mask], data2[mask]  # Select data to compute with mask
    ne.evaluate('d1**d2', out=result[mask])  # compute with numexpr.
```

**Comment by FrancescAlted** [comment]
Storing the result on an indexed array is not meant to work.  I would say that in these operations the 'jumps' in memory will become the bottleneck for most of the computations.  For this things, I would say that you should use the numpy machinery.

**Comment by JGoutin** [comment]
Ok, thanks.
