### ISSUE TITLE
__getattr__ raises KeyError, should be AttributeError

### ISSUE THREAD

**Issue by nbecker** [pydata/numexpr#207]
I tried using pympler (memory profiling), and ran into an issue with numexpr (I was using pympler to give me a summary of ALL objects, and happened to have some numexpr objects around)

  File "/home/nbecker/.local/lib/python3.4/site-packages/pympler/asizeof.py", line 347, in _dir2
    if hasattr(obj, slots):
  File "/home/nbecker/.local/lib/python3.4/site-packages/numexpr/expressions.py", line 54, in __getattr__
    return self.__dict__[name]
KeyError: '__slots__'

I think the fix is in expressions.py, raise AttributeError (not KeyError):

class Expression(object):
    def __init__(self):
        object.__init__(self)

    def __getattr__(self, name):
        if name.startswith('_'):
            try:
                return self.__dict__[name]
            except KeyError:
                raise AttributeError
        else:
            return VariableNode(name, default_kind)

**Comment by FrancescAlted** [comment]
Good point.  Fixed in a4ba2b6.
