### ISSUE TITLE
numexpr fails to install if current path contains `%` in its name -- breaks git flow

### ISSUE THREAD

**Issue by ssbarnea** [pydata/numexpr#217]
Git flow branch naming conventions uses branches like `feature/xxx`, `release/xxx` and CI systems will usually checkout the branch as a folder, converting it using HTTP escaping like `feature%2Fxxx`. 
Surprise, now if you want to install `numexpr` it will fail with 

```
      File "/usr/lib/python3.4/configparser.py", line 371, in before_get
        self._interpolate_some(parser, option, L, value, section, defaults, 1)
      File "/usr/lib/python3.4/configparser.py", line 421, in _interpolate_some
        "found: %r" % (rest,))
    configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%2Fdevops/workspace/env/lib:/usr/local/lib:/usr/lib:/usr/lib/x86_64-linux-gnu'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3fjvjwcl/numexpr/
```

Full log https://gist.github.com/ssbarnea/b373062dd45de92735c7482b2735c5fb

**Comment by ssbarnea** [comment]
Here a very easy way to replicate the bug:
```
virtualenv -p python3 --no-site-packages env
source env/bin/activate
pip install numexpr
```
The problem cannot be reproduces with other packages, like numpy or pandas.

**Comment by ssbarnea** [comment]
And my impression is that this answer is providing the solution to this bug http://stackoverflow.com/questions/14340366/configparser-and-string-with -- use RawConfigParser instead of ConfigParser.

**Comment by ssbarnea** [comment]
Or even easier, checkout the code somewhere where you have a `%F2` as part of the full path and run:
```
python setup.py egg_info
```

**Comment by steveholden** [comment]
+1 to changing to RawConfigParser - it seems unnecessary to add yet another variable namespace when we have so many already!

**Comment by FrancescAlted** [comment]
+1 for chaning that too, but I don't see any ConfigParser in setup.py.  @ssbarnea would you like to provide a PR?  Thanks.

**Comment by ssbarnea** [comment]
I am still investigating the bug and looking for the root cause and maybe ways to workaround it. So far the only package that encountered it is numexpr.

**Comment by ssbarnea** [comment]
As you can see I made two PRs one against master and another one against latest maintenance branch. 

Initially I wanted to create a patched numpy source tar.gz file myself and use it but somehow it seems that it doesn't want to build the source distro - see https://github.com/numpy/numpy/issues/7574

**Comment by robbmcleod** [comment]
Closing as fixed.
