### ISSUE TITLE
cpuinfo.py report error when import numexpr on smartos system

### ISSUE THREAD

**Issue by FrankYu** [pydata/numexpr#220]
Hi, 
I met below error when try to import numexpr on smartos sytem(open solaris system like)
# python -c 'import numexpr'

/opt/local/lib/python2.7/site-packages/numexpr/cpuinfo.py:50: UserWarning: [Errno 2] No such file or directory
  stacklevel=stacklevel+1)
/opt/local/lib/python2.7/site-packages/numexpr/cpuinfo.py:71: UserWarning: [Errno 2] No such file or directory
  stacklevel=stacklevel+1):

**Comment by robbmcleod** [comment]
I have no way of dealing with this so closing, sorry.
