### ISSUE TITLE
2.6.0 about 25% slower than 2.5.2 with MKL

### ISSUE THREAD

**Issue by hiccup7** [pydata/numexpr#221]
I performed some benchmark comparisons using the WinPython distribution  at https://winpython.github.io/
Like Anaconda on Windows, WinPython uses numexpr and numpy compiled with MKL from wheels on this web site: www.lfd.uci.edu/~gohlke/pythonlibs/

I used the following benchmark script on my Haswell Core i7-4700HQ-based Windows 8.1 PC, which is dominated by numexpr and representative of the way I typically use numexpr:
```
# -*- coding: utf-8 -*-
import numpy as np
import numexpr as ne
from timeit import default_timer as timer

x = np.ones(100000)
scaler = -1J
start = timer()
for k in range(10000):
    cexp = ne.evaluate('exp(scaler * x)')
exec_time=(timer() - start)
print
print("Execution took", str(round(exec_time, 3)), "seconds")
```
I got the same performance for Python 3.4 and 3.5 environments.  With numexpr 2.5.1 and 2.5.2, I got 7.3 seconds.  With numexpr 2.6.0, I got 9.1 seconds, which 25% slower.

My test environment can be reproduced from the following distribution installers:
numexpr 2.5.1 from WinPython-64bit-3.4.4.2.exe at https://sourceforge.net/projects/winpython/files/WinPython_3.4/3.4.4.2/
numexpr 2.6.0 from WinPython-64bit-3.4.4.3rc.exe at https://sourceforge.net/projects/winpython/files/WinPython_3.4/3.4.4.3/betas/

The list of changed packages is available here:
https://github.com/winpython/winpython/issues/309

**Comment by hiccup7** [comment]
@cgohlke - Thanks for the clarification about VML.  I learned something, and it will help the numexpr developers understand the test conditions.  I edited the title and issue description to remove my incorrect info.

**Comment by hiccup7** [comment]
I wonder if my test script shows the same problem on the Haswell processor used by the numexpr developer (E3-1240 v3).  My Haswell processor is only 2 years old.

**Comment by FrancescAlted** [comment]
That's a good point.  Yes, after doing some more detailed benchmarks, I can see the performance regression too (30% for your case and a E3-1240 v3 @ 3.40GHz).  I suppose we can go back to the 4096 figure for BLOCK_SIZE1, but I am curious on whether even a lesser value (say 1024) could be beneficial.  @hiccup7 @cgohlke could you have a try at these lesser values?

**Comment by FrancescAlted** [comment]
I did some benchmarks on my own (on a newer Intel Xeon Skylake CPU) in commit [9312182](https://github.com/pydata/numexpr/commit/04773a8abbccef7d7c11430fa24aac1cfa27a2a0), and I think this regression should be corrected now.  Could you please confirm?

**Comment by cgohlke** [comment]
> this regression should be corrected now. Could you please confirm?

Confirmed. Thank you.

**Comment by FrancescAlted** [comment]
Great.  So I will try to do a release soon.

**Comment by hiccup7** [comment]
I don't have an MKL license or experience in building Python packages.  I will test numexpr 2.6.1 when it is available at www.lfd.uci.edu/~gohlke/pythonlibs/
There will be a new build/release of WinPython soon, so I hope numexpr 2.6.1 will be released before then.

On behalf of the WinPython and Anaconda communities, my thanks to @FrancescAlted and @cgohlke !

**Comment by hiccup7** [comment]
I tested numexpr 2.6.1 from www.lfd.uci.edu/~gohlke/pythonlibs/ in the RC (2016-07-14) build of 64-bit WinPython 3.4 and 3.5.  Using my same test script, I confirm that the regression has been resolved.  Thanks again.
