### ISSUE TITLE
Test failure on  powerpc and ppc64el

### ISSUE THREAD

**Issue by avalentino** [pydata/numexpr#224]
We are trying to update debian packages for numexpr to v2.6.1 and we have test failures on powerpc and ppc64el [1], [2]
I feels very strange because v2.6.0 (currently in testing) seems to work correctly, and changes between v2.6.0 ans v2.6.1 are really minimal [3].

The main change between the two builds seems to be the updated gcc version (5.3.1 vs 6.1.1).

Any idea?

[1] https://buildd.debian.org/status/fetch.php?pkg=numexpr&arch=powerpc&ver=2.6.1-1&stamp=1472197317
[2] https://buildd.debian.org/status/fetch.php?pkg=numexpr&arch=ppc64el&ver=2.6.1-1&stamp=1472197359
[3] https://github.com/pydata/numexpr/compare/v2.6.0...v2.6.1

**Comment by FrancescAlted** [comment]
Hmm, this is really strange.  I have no experimented with gcc 6 yet, but is there a way to build numexpr 2.6.1 with gcc-5?  I am using gcc 5.4.0 (before was gcc 5.3.something) on an Ubuntu 16.04 box and all the tests passes.

**Comment by avalentino** [comment]
Thanks @FrancescAlted, Indeed it is very strange.
The default gcc version on the next Debian stable will be gcc 6 so I think it is not possible to use old versions of building packages.
I will ask for a guest access to powerpc and ppc64el platforms to investigate.

**Comment by ferseiti** [comment]
Hello.
I have created a [PR](https://github.com/pydata/numexpr/pull/235) for this.
I have tested it on ppc64el and x86_64.
Regards.

**Comment by avalentino** [comment]
@FrancescAlted probably this one can be closed since PR #235 has been merged now

**Comment by FrancescAlted** [comment]
Thanks @avalentino for the reminder.  Closing.
