### ISSUE TITLE
isnan and isfinite function in numexpr like in numpy

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#23]
_From [tom.denn...@gmail.com](https://code.google.com/u/110078974596186779257/) on September 08, 2009 22:54:48_

It would be really nice if there were isnan and isfinite function in 
numexpr like in numpy:

An example would be:

> > > a = numpy.arange(10.0)
> > > 
> > > a[2]=numpy.nan
> > > 
> > > a
> > > array([  0.,   1.,  NaN,   3.,   4.,   5.,   6.,   7.,   8.,   9.])
> > > 
> > > numexpr.evaluate('where(isnan(a), 0, a)')
> > > array([ 0.,  1.,  0.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=23_

**Comment by robbmcleod** [comment]
`isnan`, `isnnormal`, `isfinite`, `isinfinite` and `fpclassify` are all present in NE3.
