### ISSUE TITLE
Fix Segmentation fault on OpenBSD

### ISSUE THREAD

**Issue by shadchin** [pydata/numexpr#230]
I do not know how much it is correct, but it helped.
Bug in function [stringcontains](https://github.com/pydata/numexpr/blob/master/numexpr/interpreter.cpp#L536):
strlen can not find the end of string and leaves beyond available memory

[patch-numexpr_numexpr_object_cpp.txt](https://github.com/pydata/numexpr/files/587786/patch-numexpr_numexpr_object_cpp.txt)

**Comment by FrancescAlted** [comment]
Thanks.  This is probably correct, but it would be really nice if you can provide a PR for this, with some tests.

**Comment by shadchin** [comment]
Ok, I will prepare PR
