### ISSUE TITLE
Add support for Bessel functions

### ISSUE THREAD

**Issue by rnorris7756** [pydata/numexpr#237]
I would be willing to work on this.  The C++ standard library does not have great support for Bessel functions, but the boost library has a good implementation [here](http://www.boost.org/doc/libs/1_62_0/libs/math/doc/html/math_toolkit/bessel/bessel_first.html).  What is this project's policy on including pieces of external libraries like boost?

**Comment by FrancescAlted** [comment]
Well, I think that evaluating Bessel functions inside numexpr is really too specific.  numexpr comes with a virtual machine for evaluating expressions that has to lookup for many operators and functions already.  Adding more functions is going to create a noticeable performance impact for all the other evaluations (even if they do not use Bessel functions).  So I am -1 on this.

**Comment by rnorris7756** [comment]
Fair enough.
