### ISSUE TITLE
support for inplace addition/subtraction/multiplication to `out` keyword?

### ISSUE THREAD

**Issue by nbren12** [pydata/numexpr#238]
In a lot of my codes, I want to perform several inplace additions to the same array of data. For example, I may try to evaluate a function `f(x) =g(x)+ h(x)  + k(x)` where k(x), g(x), and h(x) can possibly be expressed in numexpr. Ideally, I could avoid all intermediate allocation be doing something like

```
f = np.zeros(shape)
inplace_funcion_not_numexpr(f)
ne.evaluate(expr1, out=f, inplace_op='+')
ne.evaluate(expr2, out=f, inplace_op='+')
ne.evaluate(expr3, out=f, inplace_op='+')
```

Is this possible using numexpr?

**Comment by robbmcleod** [comment]
Not with the current Python-side implementation of NumExpr2.  Currently NumExpr implements its own abstract-syntax tree representation, separate from Python, which doesn't include such things as Assignment nodes.  I've looked at using the python `ast` module to build the AST representation and it seems significantly faster and more flexible but this is still a work-in-progress (i.e. only pieces work).

**Comment by robbmcleod** [comment]
As the 3.0 branch supports named temporaries, which seem to provide support for this issue, I'm going to close this issue for now.  
[https://github.com/pydata/numexpr/tree/numexpr-3.0](url)
Feel free to re-open if you have further questions/issues.
