### ISSUE TITLE
Problem with "and" (also, __nonzero__ should not be defined)

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#24]
_From [mike.tho...@gmail.com](https://code.google.com/u/117706089323896263204/) on December 12, 2009 04:23:42_

> > > a = numpy.array([1, 2, 1, 2, 1], dtype=numpy.int8)   # or numpy.int32
> > > b = numpy.array([1, 2, 3, 4, 1], dtype=numpy.int8)   # or numpy.int32
> > > numexpr.evaluate("(a==1) & (b>2)")
> > > array([False, False,  True, False, False], dtype=bool)

All good so far.  But, now, if we try to use "and" instead of "&":

> > > numexpr.evaluate("(a==1) and (b>2)")
> > > array([False, False,  True,  True, False], dtype=bool)

Which isn't right.  Seems as if only the RHS expression of the "and" is
evaluated. Ie. the result given is just "b>2".

This on windows XP, python 2.5.

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=24_

**Comment by AbelHutten** [comment]
Closing as stale due to inactivity. Feel free to reopen.
