### ISSUE TITLE
Numpy dependency is now 1.7

### ISSUE THREAD

**Issue by matthew-brett** [pydata/numexpr#245]
I think the numpy dependency for 2.6.2 is numpy 1.7, because compilation fails for numpy 1.6:

```
  g++: numexpr/interpreter.cpp
  In file included from numexpr/module.hpp:14:0,
                   from numexpr/interpreter.cpp:10:
  numexpr/interpreter.cpp: In function ‘PyObject* NumExpr_run(NumExprObject*, PyObject*, PyObject*)’:
  numexpr/interpreter.cpp:1060:47: error: ‘NPY_ARRAY_NOTSWAPPED’ was not declared in this scope
```

https://travis-ci.org/MacPython/numexpr-wheels/jobs/196542706#L401

Compilation with numpy 1.7.1 runs fine.  Worth noting in `requirements.txt` and elsewhere?

**Comment by robbmcleod** [comment]
I've updated the requirement to be 1.7 in 2.6.3dev.  I can't find anything in the docs that references the version requirement.
