### ISSUE TITLE
add support for integer division and truncation?

### ISSUE THREAD

**Issue by t184256** [pydata/numexpr#251]
I could not find neither `//`, nor a `trunc` function in `numexpr`.

I see #247 has `floor`/`ceil`, but no `//` or `trunc`.

 I'd like to suggest adding them.

**Comment by robbmcleod** [comment]
All of these things are in the NumExpr-3.0 branch already.

https://github.com/pydata/numexpr/tree/numexpr-3.0

It's in alpha and in the process of being debugged.

**Comment by t184256** [comment]
Oh, good to hear. Sorry for bugging you then.

**Comment by robbmcleod** [comment]
If you would like to play with the new branch and report any bugs that you find you are welcome to do so.
