### ISSUE TITLE
NE3: Byte and Unicode string support

### ISSUE THREAD

**Issue by robbmcleod** [pydata/numexpr#263]
NE2 had very limited support for ascii-encoded strings (with the `contains` function and comparisons). Likely additional function could be added to NE3 if someone who does string processing could be found to implement them.

The main question is how to interact with the Python Unicode object, and how to get the byte-depth used (i.e. UTF-8 versus UTF-16 versus UTF-32).

**Comment by zorion** [comment]
I guess you already have one, but in case you need a small test for python3:

```
import numexpr as ne

data_text = {'a': 'b'}
data_byte = {'a': b'b'}
condition = "(a=='a')"

try:
    r_text = ne.evaluate(condition, data_text)
except Exception as error:
    print('Exception when text', error)

r_byte = ne.evaluate(condition, data_byte)
print('Byte version', r_byte)

```
