### ISSUE TITLE
NumExpr 3.0 Installation Problem

### ISSUE THREAD

**Issue by wjaekim** [pydata/numexpr#266]
NumExpr 3.0 is exactly what I need for my current project. But I'm having trouble installing it. Could anyone please help me? I am using gcc 6.3.0 and Python 2.7 on Amazon EC2 (Amazon linux based on CentOS). Below are excerpts of error messages I receive during installation (similar types of error messages are omitted).

**UPDATE:** see [here](https://github.com/pydata/numexpr/pull/267)
---------------
numexpr3/functions_GENERATED.cpp:3341:21: error: no match for ‘operator/’ (operand types are ‘npy_complex64 {aka npy_cfloat}’ and ‘npy_complex64 {aka npy_cfloat}’)
dest[J] = x1[J] / x2[J];

...

numexpr3/functions_GENERATED.cpp: In function ‘int div_FFF(npy_intp, npy_intp, const NumExprObject*)’:
numexpr3/functions_GENERATED.cpp:11693:1: error: redefinition of ‘int div_FFF(npy_intp, npy_intp, const NumExprObject*)’
div_FFF( npy_intp block_size, npy_intp pc, const NumExprObject *params )

...

error: Command "g++ -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/ec2-user/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/ec2-user/anaconda2/include/python2.7 -c numexpr3/interpreter.cpp -o build/temp.linux-x86_64-2.7/numexpr3/interpreter.o" failed with exit status 1

**Comment by robbmcleod** [comment]
Closing after commit of 605753f2d7c1bd6b444d8cef5fb6f95ca52d36f1
