### ISSUE TITLE
Support for nanoseconds 

### ISSUE THREAD

**Issue by hughchristensen** [pydata/numexpr#268]
Python will be able to handle nanoseconds when [this](https://bugs.python.org/issue15443) is solved. When it is, we should see nanoseconds specified [here](https://docs.python.org/3/library/datetime.html). Pandas can already handle [nanoseconds](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.dt.nanosecond.html). It also looks like numpy supports [nanoseconds](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#datetime-units).

We can store nanoseconds in the hdf5 files, when we try to query them, we get error messages of unsupported type. [PyTables](http://www.pytables.org), the framework we use for handling hdf5 files, supports *storing*  the timestamps with nanoseconds. However, *numexpr*, a package used by *PyTables*  when querying the data, *does not*  yet support nanoseconds.

We need numexpr to support nanoseconds.

**Comment by robbmcleod** [comment]
Thanks for the feedback, I'll take that under advisement.
