### ISSUE TITLE
pthread_create error in test_numexpr.pyc

### ISSUE THREAD

**Issue by cjnolet** [pydata/numexpr#270]
Not exactly sure why / how this is happening. All of my ulimits and nproc and thread-max limits are definitely high enough and the system itself is not experiencing any type of contention for resources. The following is the error I'm getting while trying to "import numexpr" in the python shell:

```
ERROR; return code from pthread_create() is 22
                Error detail: Invalid argument
```

**Comment by robbmcleod** [comment]
What operating system and Python version are you running?  I've found some problems with Python 3.6 on Windows when calling Windows system functions related to threads.

**Comment by cjnolet** [comment]
I'm on Red Hat 7.3 and using Python 2.7 (through Anaconda 2). What's really strange (and I don't know for sure if it has to do with this) is that another system I'm using this on works just fine but it's redhat 7.1. I can't imagine that alone is enough to throw things off. I've been checking libraries and whatnot like libpthread and gcc and they all seem to be the exact same versions.

**Comment by robbmcleod** [comment]
You could try removing the MKL version and see if that fixes things?  I think it's something like:

    conda install nomkl numpy scipy scikit-learn scikit-image numexpr
    conda remove mkl mkl-service

**Comment by cjnolet** [comment]
Actually, I think I may have figured out (kind of) what may be doing this. This is a production machien where this particular user is used for several different applications. Just for the heck of it, I tried it under my own user and it works just fine. Still not sure exactly what the configuration difference is that's causing this though.

**Comment by robbmcleod** [comment]
I would dump `os.environ()` from each user and diff them.
