### ISSUE TITLE
Integers to negative integer powers are not allowed

### ISSUE THREAD

**Issue by Zex** [pydata/numexpr#272]
Components:
Numpy-1.12.0
Python-3.5.3
Description:
```10**-5``` is fine,
But do it in a for loop ValueError raise.
Here is the code
```
>>> [10**c for c in np.arange(-5,5)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
ValueError: Integers to negative integer powers are not allowed.
>>> 10**0
1
>>> 10**-1
0.1
>>> 10**-2
0.01
>>> 10**-3
0.001
>>> 10**-4
0.0001
>>> 10**-5
1e-05
>>> 10**1
10
>>> 10**2
100
>>> 10**3
1000
>>> 10**4
10000
>>> 10**5
100000
```

**Comment by FrancescAlted** [comment]
Your report does not use the numexpr package at all.  You may want to report that top NumPy really.  I'm closing, but feel free to reopen in case you are really using numexpr.
