### ISSUE TITLE
NE3: Support AArch64

### ISSUE THREAD

**Issue by itdaniher** [pydata/numexpr#273]
`pip install blosc` on aarch64 / python3.5.2 errors out due to cpuinfo.py not having a match clause for aarch64.

This is solvable by adding the following three lines:

```
+       elif re.match('^aarch64$', raw_arch_string):
+               arch = 'AARCH_64'
+               bits = 64
```

Cheers!
Ian

**Comment by robbmcleod** [comment]
We actually use an older version of `cpuinfo.py` in NumExpr that's written by a different author than that used in python-blosc.

**Comment by itdaniher** [comment]
Ooops.. Opened this on the wrong project featuring FrancescAlted.
