### ISSUE TITLE
Support for non scalar output?

### ISSUE THREAD

**Issue by FrederikLauber** [pydata/numexpr#274]
Hello,

is there any support (or any plans for that matter) to not only have scalar outputs but for example vectors (either by specifying multiple expressions for each element or by actual operations which produce an vector)?

I am particular interested in the first usecase as I have o produce many histograms from larger-than-memory data with pytables and being able to specify multiple numexprs which are evaluated during the same time (+the new reduction support) will cut down on that hard.
I would imagine it would work something like this:
```
import numpy as np
import numexpr as ne
a = np.arange(10)
b = ne.evaluate('sum(a<5); sum(a>9);')
print(b)
-> (10, 10)
```

The second usecase would also be very nice but I guess WAY WAY to hard to implement so
I will just put this out as a crazy idea.

**Comment by robbmcleod** [comment]
Hi Frederik, you probably want to take a look at #271 for some discussion of the particulars of summing over boolean arrays. Essentially we need some explicit cast operations to be inserted. The current NumExpr 2.6 has a very limited namespace in its virtual machine, so we've built a new one that can handle 64k different operations, but it's still in an alpha-state (and hence not production ready).  

NumExpr3 supports multi-line evaluation and assignment so if it supported reductions (which it does not at present) then it could do something like:

    ne3.evaluate( 'b1 = sum(uint32(a<5)); b2 = sum(uint32(a>9))' )

It could be quite some time before that's possible, however.

**Comment by FrederikLauber** [comment]
Finished my PhD by now so I guess I somehow managed without the feature ;)

**Comment by FrancescAlted** [comment]
Congrats for your PhD!
