### ISSUE TITLE
control number of threads on import

### ISSUE THREAD

**Issue by marqh** [pydata/numexpr#275]
hi numexpr folks

I have an issue with numexpr, where it is running in a shared environment with thread limits imposed by a scheduler

when i import numexpr, it appears to run `detect_number_of_threads`
https://github.com/pydata/numexpr/blob/master/numexpr/__init__.py#L49
then `set_num_threads`
https://github.com/pydata/numexpr/blob/master/numexpr/__init__.py#L61
as part of the import.  I can't find a way to control this until after I have imported the module

However, the scheduler is setting a thread limit based on resource usage, which is often much lower than that returned by `detect_number_of_threads`
This causes the job to fail before it has got going and before I have `numexpr` imported into my python session to enable me to reduce the number of threads to use.  

So, I am looking for a way to control this thread pool size prior to importing numexpr;
is there any help or advice you can offer?

thank you
mark

**Comment by robbmcleod** [comment]
On Linux I believe you can override the default with the environment variable `OMP_NUM_THREADS`.

**Comment by FrancescAlted** [comment]
Yes, actually you have two ways to override that:

1) Using the `NUMEXPR_NUM_THREADS` (only affects to numexpr computations)

2) Using the more general `OMP_NUM_THREADS` (can affect to more OpenMP apps)

It is true that this is not documented in the User's Guide though.

**Comment by FrancescAlted** [comment]
I have added a description for the `OMP_NUM_THREADS` in UG:

https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide#general-routines

Closing this.
