### ISSUE TITLE
Cannot import name interpreter

### ISSUE THREAD

**Issue by mm-crj** [pydata/numexpr#276]
Unable to import interpreter from numexpr package:

```
In [19]: from numexpr import interpreter
    ...: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-19-e67a4b1a90b0> in <module>()
----> 1 from numexpr import interpreter

/usr/local/lib/python2.7/dist-packages/numexpr/__init__.py in <module>()
     38 import os, os.path
     39 import platform
---> 40 from numexpr.expressions import E
     41 from numexpr.necompiler import NumExpr, disassemble, evaluate, re_evaluate
     42 from numexpr.tests import test, print_versions

/usr/local/lib/python2.7/dist-packages/numexpr/expressions.py in <module>()
     45 scalar_constant_types = tuple(scalar_constant_types)
     46 
---> 47 from numexpr import interpreter
     48 
     49 

ImportError: cannot import name interpreter

```

**Installation details:** ubuntu 16.04lts, python2.7.12, numexpr-2.6.2-cp27-cp27mu-manylinux1_x86_64.whl

**Comment by robbmcleod** [comment]
`interpreter` is the C library so probably something, one of the linked DLLs most likely, with it isn't compatible with your system environment.

Since you're running linux it's fairly trivial to compile, which I would do because the `manylinux` wheels are probably compiled with ancient `CentOS` environment and `Ubuntu 16.04` is running `gcc 5.4`.  I.e. it should run faster if you build it.

    git clone https://github.com/pydata/numexpr.git
    cd numexpr
    python setup.py build_ext install

If there are any errors it will be much more informative than using `pip`.

**Comment by mm-crj** [comment]
As it seems there was no problem, a system restart fixed the issue. Sorry for bothering you guys.

**Comment by mm-crj** [comment]
@robbmcleod building the source on my system will make them run faster? Can you elaborate how is this so?

**Comment by robbmcleod** [comment]
Compiler optimizations improve over time.  There's been a lot of them introduced to `gcc` from the CentOS 6.0 days, to current day. Also the compiler may be able to use instruction sets on your CPU depending on whether you have SSE2 or AVX2 or similar.  I'm not sure with the way the current NumExpr is written that it's going to get a lot of use out of instruction sets, however.
