### ISSUE TITLE
sum returns incorrect result for arrays with one dimension's length is 1

### ISSUE THREAD

**Issue by NJUPole** [pydata/numexpr#277]
sum produces different results from numpy.sum when one dimension's length is 1
``` 
In: a = np.array([[1,2,3]])
In: ne.evaluate('sum(a, axis=0)')
Out: array([[6, 0, 0]])
In: np.sum(a, axis=0)
Out: array([1, 2, 3])
```

**Comment by robbmcleod** [comment]
Hmm... likely either arrays are being flattened for some reason, or a problem with `numpy.nditer`.  If it's the later, hopefully it can be fixed with a flag change. I'll go take a look now.

**Comment by robbmcleod** [comment]
It seems each reduction op has a different wrong behavior:

    >>> a = np.array( [[1,2,3]] )
    >>> ne.evaluate( 'mean(a,axis=0)' )
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
       File "C:\Anaconda3\lib\site-packages\numexpr-2.6.3.dev0-py3.6-win-
    amd64.egg\numexpr\necompiler.py", line 797, in evaluate
         _names_cache[expr_key] = getExprNames(ex, context)
      File "C:\Anaconda3\lib\site-packages\numexpr-2.6.3.dev0-py3.6-win-
    amd64.egg\numexpr\necompiler.py", line 704, in getExprNames
    ex = stringToExpression(text, {}, context)
      File "C:\Anaconda3\lib\site-packages\numexpr-2.6.3.dev0-py3.6-win-
    amd64.egg\numexpr\necompiler.py", line 296, in stringToExpression
        ex = eval(c, names)
      File "<expr>", line 1, in <module>
    TypeError: 'VariableNode' object is not callable
    >>> ne.evaluate( 'sum(a,axis=0)' )
    array([[6, 0, 0]], dtype=int32)
     >>> ne.evaluate( 'prod(a,axis=0)' )
    array([[6, 1, 1]], dtype=int32)
    >>> a.prod(axis=0)
    array([1, 2, 3])
    >>> a.mean(axis=0)
    array([ 1.,  2.,  3.])

**Comment by NJUPole** [comment]
numpy has parameter `keepdims`
```
a = np.array([[1,2,3]])
a.sum(axis=1, keepdims=True)
Out[4]: array([[6]])
a.sum(axis=0, keepdims=True)
Out[5]: array([[1, 2, 3]])
a.mean(axis=0, keepdims=True)
Out[6]: array([[ 1.,  2.,  3.]])
```

**Comment by robbmcleod** [comment]
Ok, e639060 should fix this.  NJUPole would you please clone the master repo and try it on your production code now?  

Basically there was an overlapping case the the code that evaluates the reduction, such that it was treating reductions on arrays with singleton dimensions as being full reductions, e.g. `ne.evaluate('sum(a)')`. So the full reduction was going into `a[0]`, and the remaining elements were just the default identities for that reduction.

**Comment by NJUPole** [comment]
it's ok now, looking forward to the next release, thanks.
