### ISSUE TITLE
NE3: Multiprocessing / Cython?

### ISSUE THREAD

**Issue by itdaniher** [pydata/numexpr#278]
Happily using NE3 on an embedded ARM target. I went to build an executable for my project via Cython - everything works except for my calls to `ne3.evaluate`. I had to replace these with the numpy equivalent expressions. 

I see some conversation that might be relevant at https://www.reddit.com/r/Python/comments/5um04m/numexpr3/ddwca4w/, but it should be noted that multiprocessing works fine by itself, but not in conjunction with a Cython'd file.

If there isn't a readily apparent issue here, I'll try and assemble a minimal test case.

Python 3.5.2 / ARM.

Cheers!

**Comment by robbmcleod** [comment]
I'll need a test example please.  The pushes to make NE3 `pickle`-able were only done last week, but at least at trying to build a simple Cython case it looks to me like there's some sort of problem in trying to lookup the variables in the system frame in Cython. So I think this is moreso related to Cython than multiprocessing.  When I declare variables they're not always present in the `locals` dict, so the abstract syntax tree parser doesn't know what `dtype` they are.

**Comment by itdaniher** [comment]
```
import sys

# may need to hardcode sys.path - cython isn't venv-aware.
print(sys.path)

import numexpr3 as ne3
import numpy as np

b = np.array([1,-1]*100)
x = np.empty(200, dtype=np.int64)
a = ne3.evaluate('x = abs(b)')
print(x)
```
is saved in my working directory as `t.py`

    cython -3 -D --embed t.py
    gcc -fPIC -O2 t.c -I/usr/include/python3.5 -L/usr/lib/python3.5 -lpython3.5m -o t

gives a useful-looking traceback:

```
Traceback (most recent call last):
  File "t.py", line 11, in init t (t.c:1327)
    a = ne3.evaluate('x = abs(b)')
  File "/home/name/.virtualenvs/swbs/lib/python3.5/site-packages/numexpr3-3.0.1a0-py3.5-linux-aarch64.egg/numexpr3/ne3compiler.py", line 201, in evaluate
    call_frame = sys._getframe( stackDepth )
ValueError: call stack is not deep enough
```

although I did not see this traceback with my more complicated system and there are no extraneous try / catch statements.

In any case, I'm upgrading to the latest numexpr3 and will report back in a few.

**Comment by itdaniher** [comment]
same behavior after a

    pip install --upgrade git+https://github.com/pydata/numexpr.git@numexpr-3.0

**Comment by robbmcleod** [comment]
I made a post on the Cython GoogleGroups page but it's not showing up yet.  I suspect the problem lies in that the calling frame `locals` isn't being populated:

http://docs.cython.org/en/latest/src/userguide/limitations.html

What we probably need is some simple work-around to do a simple 'touch' operation on the array before calling NumExpr so that the array appears in the Python frame.

**Comment by robbmcleod** [comment]
Have you tried populating the keyword argument `local_dict` with your variables?

e.g.

    a = np.arange(2.0**16)
    out = np.empty_like(a)
    neObj = ne3.NumExpr( 'out=a*a', local_dict={'a':a, 'out':out} )
    neObj( out=out, a=a )
    np.testing.assert_array_almost_equal( out, a*a )

I just tried this and it seems to work.

**Comment by itdaniher** [comment]
`local_dict` does the job. Strange, but not complaining. Thanks for the fix - want me to close the issue?

**Comment by robbmcleod** [comment]
I'll make note of it in the docs and then close the issue when I've done that.

**Comment by itdaniher** [comment]
Cheers! Thanks for your help.

**Comment by robbmcleod** [comment]
Documented workaround in ef7de37 as this doesn't look like something that Cython plans on fixing.
