### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by dibondar** [pydata/numexpr#286]
The following simple code produces "RecursionError: maximum recursion depth exceeded in comparison"

~~~~
import numexpr as ne 
ne.evaluate("abs(0.0) ** 2")
~~~~

The same error is produced by
~~~~
ne.evaluate("conj(0.0) ** 2")
~~~~

However, if I execute 
~~~~
ne.evaluate("abs(0.0)")
ne.evaluate("conj(0.0)")  
~~~~

produces the correct answer `array(0.0)`

**Comment by robbmcleod** [comment]
Ok, thanks it's been fixed.  It'll probably be awhile until we do another maintenance release. Let me know if you find any more edge cases.

**Comment by robbmcleod** [comment]
Working on a release right now.  Something broke with multiwheels on Travis.
