### ISSUE TITLE
How to cache intermediate values?

### ISSUE THREAD

**Issue by danielzfranklin** [pydata/numexpr#292]
I'm trying to convert an RGB color into the hue component of an HSB color. The algorithm to do so is simple in python

```python
def rgb_to_hue(red, green, blue):
    lowest_color = min(red, green, blue)
    highest_color = max(red, green, blue)
    color_drop = highest_color - lowest_color
    if color_drop == 0:
        hue = 0
    elif highest_color == red:
        hue = (green - blue) / color_drop
    elif highest_color == green:
        hue = 2.0 + (blue - red) / color_drop
    else:
        hue = 4.0 + (red - green) / color_drop
    hue *= 60
    if hue < 0:
        hue += 360

    return hue
```

However, it uses many variables multiple times, such as `color_drop`. I am unsure how to do this in numexpr. I assume that doing each line in numexpr and then chaining the results together in python will be inefficient as it will involve frequent bridging between numexpr and python, and that doing the entire calculation in numexpr would be faster. However, I am unsure how to implement the entire function in numexpr. I can chain `where` functions together to create min, max, and the if-else chain, and I could replace every instance of each variable with the code required to calculate the value, but I feel there has to be a more efficient way to do this. Is there?

**Comment by robbmcleod** [comment]
This is difficult to do in the current `2.6` release.  You can use the development `3.0` branch, which can cache named intermediate matrices, or use `numba`, if that's available on your platform. In general having conditionals is a weakness of `numexpr` unless you're making masks, which you basically are doing here.

**Comment by robbmcleod** [comment]
Closing unless there's further discussion to be had.
