### ISSUE TITLE
Behaviour change of numexpr; NaN instead of 0

### ISSUE THREAD

**Issue by prisae** [pydata/numexpr#293]
Hi,

I am not sure whether this is a `numexpr` issue, or rather a `mkl` or even a `numpy` issue. However, I think the most likely case is `numexpr`.

My pytest CI suite threw a lot of errors in my last run. Digging into it I could boil it down to this minimal example:

    import numpy as np
    from numexpr import evaluate
    test = np.array([-1-1j])*np.infty
    out1 = np.exp(test)
    out2 = evaluate("exp(test)")
    print(' PRINT OUT RESULT ::', out1, out2)

Doing this evaluation with `numpy`, hence `np.exp(test)`, results in `[ 0.-0.j]`. This result was also returned by `numexpr`, until recently. Now, `numexpr` returns `[nan+nanj]`.

I attach below the result for the above minimal example  (saved as `test_numexpr.py`). I run the test first with the up-to-date conda, where `numpy` and `numexpr` yield different results. Then I downgrade `mkl` from 2018 to 2017, which also slightly downgrades `numexpr`. With the older versions `numexpr` and `numpy` yield the same result:

    test/> python test_numexpr.py
    PRINT OUT RESULT :: [ 0.-0.j] [ nan+nanj]

    test/> conda install mkl=2017

    Fetching package metadata ...............
    Solving package specifications: .

    Package plan for installation in environment ~/anaconda3/envs/test_36:

    The following packages will be DOWNGRADED:

        mkl:     2018.0.0-hb491cac_4   --> 2017.0.4-h4c4d0af_0
        numexpr: 2.6.2-py36hdd3393f_1  --> 2.6.2-np113py36_0  
        numpy:   1.13.3-py36ha12f23b_0 --> 1.13.1-py36_0      
        scipy:   1.0.0-py36hbf646e7_0  --> 0.19.1-np113py36_0 

    test/> python test_numexpr.py
    PRINT OUT RESULT :: [ 0.-0.j] [ 0.-0.j]

Any ideas on that?

Thanks,
Dieter

**Comment by robbmcleod** [comment]
You can see the NumExpr complex exponential here (line 149):

https://github.com/pydata/numexpr/blob/master/numexpr/complex_functions.hpp

It's always going to return Nan in the case of minus infinity, because that's what cosine and sine return. Most likely, you were using the Intel VML library with your NumExpr calls and it has branches to accommodate those edge-cases.  Continuum has possibly not built the newer version of NumExpr against the VML?  Try with the two modules:

`import numexpr; numexpr.get_vml_version()`

It will return `None` if you don't have VML linked.

**Comment by prisae** [comment]
Thanks for your reply Robb. Indeed, this seems to be the case. So using `mkl=2017` in `conda` yields

    In [1]: import numexpr; numexpr.get_vml_version()
    Out[1]: 'Intel(R) Math Kernel Library Version 2017.0.4 Product Build 20170811 for Intel(R) 64 architecture applications'

but using `mkl=2018` yields simply nothing (not even `None`)

    In [1]: import numexpr; numexpr.get_vml_version()
    
So it looks like Anaconda did not build the newer version against VML.

Out of interest: Are there many cases where `numpy` and `numexpr` can yield different results?

**Comment by prisae** [comment]
You were spot-on, and the fact that `numexpr` is not built against VML in `mkl-2018` is apparently a regression bug in anaconda that will be fixed (see ContinuumIO/anaconda-issues#7207). Thanks again!

**Comment by robbmcleod** [comment]
Dieter,

> Out of interest: Are there many cases where numpy and numexpr can yield different results?

Quite a few actually.  One of the limitations of NumExpr 2.6 is its restricted number of `dtype`s, so it often has different casting behavoir than NumPy.  Another general case (which you've found) is in edge-cases in complex math.  The complex functions are all branchless, so they don't handle edge cases all that well.  One potential case that may be of concern for you is that Intel VML doesn't support strided arrays, so I believe that NumExpr falls back to its own internal machinery in that case.  So if you do a really cheap binning operation on an array:

    a = np.random.random(1024)
    a4 = a[::4]
    out = ne.evaluate( 'pi*const/ar**2' )

the behavoir may change.

There is a major revision that I've been working on when I have time that fixes the casting issues by supporting almost all of the NumPy `dtype`s, and hopefully will allow us to link against multiple external libraries and let the user pick which library to use for each expression.

**Comment by prisae** [comment]
Interesting, thanks!

**Comment by gdementen** [comment]
@robbmcleod do you have a rough ETA for NE3?
