### ISSUE TITLE
Processes are spawned while loading

### ISSUE THREAD

**Issue by guptaaka** [pydata/numexpr#299]
My main process gets spawned on multiple cores when I say "import numexpr", even if my code does not use the module anywhere. If I run htop to analyze resource usage for my main task, the memory usage/amount of memory reserved gets split up into multiple tasks, just because the module is imported.
[Edit] Attached below are the snapshots from htop output, the sub-process remain in "Sleep" state all the time, and only the parent process keeps "Running".

![main-process](https://user-images.githubusercontent.com/23294197/38349972-f4c81788-38c6-11e8-89a7-3ff0ea95713f.PNG)
![sub-processes](https://user-images.githubusercontent.com/23294197/38349975-f5c04df4-38c6-11e8-95d4-a3da1c930632.PNG)

**Comment by robbmcleod** [comment]
Yes, this is true. NumExpr spawns threads on import.  What is the issue?

**Comment by guptaaka** [comment]
The main process gets unnecessarily spawned even if I'm not using numexpr methods and just importing the module at some place.
Say, I run a script which imports and uses module 'x'. x further imports numexpr globally. My current script does not use any of the numexpr function (even indirectly), but still the main process gets spawned.

**Comment by robbmcleod** [comment]
Dealt with in 694a838a5a188444accecccee65c798fe799ac90 so closing, unless you have further issues.
