### ISSUE TITLE
numexpr/__init__.py doesn't need to import tests

### ISSUE THREAD

**Issue by ghisprince** [pydata/numexpr#302]
this line

https://github.com/pydata/numexpr/blob/8b91a6d0eb4f5ad8a71aceefa17300120272d3c8/numexpr/__init__.py#L40

does some imports which do not get used .

Problem it introduces is that it makes `import numexpr` fail if the `tests` module is excluded from the deployment.

Since that line is not necessary could it be removed? Thanks

I removed line 40 and ran tests.

```
>>> import numexpr
>>> numexpr.tests.test()
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.6.6dev0
NumPy version:     1.14.2
Python version:    3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Platform:          win32-AMD64-10.0.15063
CPU vendor:        GenuineIntel
CPU model:         Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
CPU clock speed:   3691 MHz
VML available?     False
Number of threads used by default: 8 (out of 8 detected cores)
Maximum number of threads: 64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
............. MANY MORE DOTS
----------------------------------------------------------------------
Ran 5516 tests in 4.911s

OK
<unittest.runner.TextTestResult run=5516 errors=0 failures=0>
>>>
```

**Comment by robbmcleod** [comment]
Mmm... that might break other peoples' code.  Why don't we have a stub that lazy imports tests?  E.g., in `__init__.py`:

    def print_versions():
        """Print the versions of software that numexpr relies on."""
        try:
            import numexpr.tests
            return numexpr.tests.print_versions
        except ImportError:
            # To maintain Python 2.6 compatibility we have simple error handling
            raise ImportError('`numexpr.tests` could not be imported, likely it was excluded from the distribution.')

    def test(verbosity=1):
        """Run all the tests in the test suite."""
        try:
            import numexpr.tests
            return numexpr.tests.test(verbosity=verbosity)
        except ImportError:
            # To maintain Python 2.6 compatibility we have simple error handling
            raise ImportError('`numexpr.tests` could not be imported, likely it was excluded from the distribution.')

**Comment by robbmcleod** [comment]
This should be done now in 54fc031d1abb71240f113df8319cc8dc37528350.  Sorry this was missed for 2.6.6, I had forgotten about it.
