### ISSUE TITLE
Numexpr 3 language scope

### ISSUE THREAD

**Issue by jpivarski** [pydata/numexpr#304]
Do you have a document specifying the names of all the functions and operators in numexpr 3? (Including constants like `e` and `pi`: do you recognize these names or do they have to be in scope? In aggressive mode, which powers do you replace with explicit multiplication? Etc.)

I'm developing a histogramming package (https://github.com/diana-hep/histbook) that takes expressions as quantities to evaluate and plot (could address your #205). These expressions look a lot like numexpr and could benefit from being exactly the same language as numexpr (my [#22](https://github.com/diana-hep/histbook/issues/22) and [#23](https://github.com/diana-hep/histbook/issues/23). For instance, I should rename my "asin" to "arcsin" for complete compatibility.

But I see that you're in preparation for a big release, so I should probably aim for compatibility with the new version. Do you have a specification?

Thanks!

**Comment by jpivarski** [comment]
Thanks! I'll make the language used to fill histograms conform to this list. There's already a large overlap and renaming "acos" → "arccos" (etc) is easy enough, but there's also a few extra functions that I have, like "factorial" (because it's in Python's math library) and "heaviside" (because it's in Numpy) and a few extra that you have ("crosspower"? "fpclassify"?). Most of the ones I was lacking are casting functions.

Here's a complete list of functions that I thought were important but aren't in your list, in case they were oversights:

* "min" and "max" (rather than "fmin" and "fmax", applies to integers)
* "rad2deg" and "deg2rad" (Numpy spellings), as well as "degrees" and "radians" (Numpy and Python-math, though I think the names with a "2" in them are more clear)
* "factorial" (Python-math; can be computed from "lgamma" applied to integers `x`: `numpy.round(numpy.exp(lgamma(x + 1)))`)
* "gamma", which is `exp(lgamma(x))`; I'm not sure what your "tgamma" is but I'll look it up
* "pow"; you have the `**` operator, but particularly complex equations are easier to read with "pow" as a function
* "heaviside"
* "logaddexp" and "logaddexp2"
* "sign"

One direction where numexpr 3 is going that I won't be able to follow: assignments. I need the functions to be pure expressions because I construct a dependency graph and arrange instructions to avoid recalculating duplicate subexpressions. The use for this is that particle physicists want to fill hundreds of histograms with very similar quantities; manually optimizing them with explicit temporaries conflicts with clarity— they're easier to read as a flat list of expressions. Therefore, I do something similar to numexpr's aggressive mode (but maybe beyond it), reorganizing the expressions to automatically identify temporary quantities*. However, this requires referential transparency: if assignments are allowed, they'd be used as substitutions, and in-place mutations would be completely impossible.

But in the end, that means that I can say I support a _subset_ of numexpr 3's functionality: just the pure expressions.

* I know that this wrongly assumes floating point associativity. My users aren't depending on that level of precision.

**Comment by robbmcleod** [comment]
> "min" and "max" (rather than "fmin" and "fmax", applies to integers)

Probably it would be better if I just removed `fmin` and `fmax` because they are sort-of reductions but not numpy-like reductions. NumExpr 2.6 has reductions, so the lack of them in Ne3 is a known regression, and these two functions can be achieved with `where`.

> "rad2deg" and "deg2rad" (Numpy spellings), as well as "degrees" and "radians" (Numpy and Python-math, though I think the names with a "2" in them are more clear)

+1; there is no problem with having aliases to functions.

> "factorial" (Python-math; can be computed from "lgamma" applied to integers x: numpy.round(numpy.exp(lgamma(x + 1))))

+1

> "gamma", which is exp(lgamma(x)); I'm not sure what your "tgamma" is but I'll look it up

http://www.cplusplus.com/reference/cmath/tgamma/

I can do a rename of `tgamma` -> `gamma`.

> "pow"; you have the ** operator, but particularly complex equations are easier to read with "pow" as a function

Yes this is an oversight.

> "heaviside"

I would need a reference implementation, or I can show you how the code generator works and you can do a PR.

>  "logaddexp" and "logaddexp2"

I would need a reference implementation, or I can show you how the code generator works and you can do a PR.

> "sign"

I think this is `signbit`, at least for floats... probably the smart thing would be to have two implementations, using `cmath::signbit()` for floats and a comparison for ints, and call them all `sign`.

>One direction where numexpr 3 is going that I won't be able to follow: assignments. I need the functions to be pure expressions because I construct a dependency graph and arrange instructions to avoid recalculating duplicate subexpressions. The use for this is that particle physicists want to fill hundreds of histograms with very similar quantities; manually optimizing them with explicit temporaries conflicts with clarity— they're easier to read as a flat list of expressions. Therefore, I do something similar to numexpr's aggressive mode (but maybe beyond it), reorganizing the expressions to automatically identify temporary quantities*. However, this requires referential transparency: if assignments are allowed, they'd be used as substitutions, and in-place mutations would be completely impossible.
>
>But in the end, that means that I can say I support a subset of numexpr 3's functionality: just the pure expressions.

Mkay, if I think of anything that might be useful regarding the AST I'll pass that on.

**Comment by jpivarski** [comment]
> "min" and "max" (rather than "fmin" and "fmax", applies to integers)

> Probably it would be better if I just removed fmin and fmax because they are sort-of reductions but not numpy-like reductions. NumExpr 2.6 has reductions, so the lack of them in Ne3 is a known regression, and these two functions can be achieved with where.

Min and max can be reducers, but they can also be mappers when they act like `where(a > b, a, b)`. A user is more likely to want to type `max(a, b)` or might not think of the "where" construction. I'd want to keep them, especially for more than two arguments.

The "f" prefix (in fmin, fmax, fabs, and fmod) is unnecessary and probably not what a user would guess. I think they exist to indicate floating point in a language without dispatch by argument type, possibly C. (I can't remember if dispatch by argument type is a C++ feature.) Maybe we need both for historical reasons, but Python users are more likely to want min, max, abs, and mod (if not just `%`).

Speaking of mod, is there an option for C/Java-style `%` versus Python-style `%`, which differ in how negative values are treated? Some languages provide both as "modulo" and "remainder".

> heaviside, logaddexp, logaddexp2, and sign

They're all from Numpy. If have to look in the Numpy code to find out what they do myself.

**Comment by robbmcleod** [comment]
> Min and max can be reducers, but they can also be mappers when they act like where(a > b, a, b). A user is more likely to want to type max(a, b) or might not think of the "where" construction. I'd want to keep them, especially for more than two arguments.

I can get behind calling such functions `maximum` and `minimum` as then they would have the same behavior as the two ufuncs, `np.maximum` and `np.minimum`.

**Comment by jpivarski** [comment]
Oh, that's a good point. I'll do that as well.

**Comment by robbmcleod** [comment]
I added most of what you requested in: https://github.com/pydata/numexpr/commit/3db9144e5d83929ebbf472446868e6e1a7d9a6e1

It's still missing integer `pow` and `mod` as those I have some trouble with seg-faults for reasons that aren't clear to me.

**Comment by jpivarski** [comment]
Great! I have [my own issue open](https://github.com/diana-hep/histbook/issues/26) to integrate with numexpr, which involves both synchronizing with the language and using numexpr to accelerate the calculations. (I need to identify subexpressions in the dependency graph whose parts don't need to be reused and collapse then back down from lists of Numpy commands into simple numexpr expressions.)

This issue was information-seeking, so I was wondering when would be a reasonable time to close it. Since you've implemented all the functions, I guess we can close this.

By the way, the distinction between C-style `%` and Python-style `%` is in `fmod` versus `remainder`. They should be tested with negative and non-integer values in the testing suite, because that's where their differences will reveal themselves.

Thanks for taking the time to go over this with me!
