### ISSUE TITLE
extra carriage returns in test_numexpr is breaking this module

### ISSUE THREAD

**Issue by pjm4github** [pydata/numexpr#309]
this chunk of code is broken:

       method.description = ('test_expressions(%s, test_scalar=%r, '

                              'dtype=%r, optimization=%r, exact=%r)') \

                            % (expr, test_scalar, dtype.__name__, optimization, exact)

The line extension is not operating correctly. Change to this:

       method.description = ('test_expressions(%s, test_scalar=%r, '
                              'dtype=%r, optimization=%r, exact=%r)') \
                            % (expr, test_scalar, dtype.__name__, optimization, exact)

**Comment by robbmcleod** [comment]
I'm assuming this is duplicate of #305?

**Comment by robbmcleod** [comment]
I removed the last line continuation character in the project, even though it should only be an issue with certain version of Python 3.7.
