### ISSUE TITLE
evaluate() generates an extra reference for objects in calling frame

### ISSUE THREAD

**Issue by lgarrison** [pydata/numexpr#310]
I find that `numexpr.evaluate()` generates an extra ref count for objects in calling frame, even when the object isn't used in the expression.  Here's an example:

```python
import numexpr
import numpy as np
import sys

def f():
    a = np.arange(10)
    numexpr.evaluate('1')
    print(sys.getrefcount(a))

def g():
    a = np.arange(10)
    print(sys.getrefcount(a))

f()
g()
```
```
3
2
```

This created a memory leak in my code: in my application, `a` was a big array that I was deleting, but it was never garbage collected because of the reference created by numexpr in a totally unrelated operation.

Notably, passing `local_dict={}` fixes the problem.  I think the usage of `sys._getframe().f_locals` is creating the persistent reference somehow, perhaps via a caching mechanism.  So this code also exhibits the leak:

```python
def h():
    a = np.arange(10)
    sys._getframe(0).f_locals
    print(sys.getrefcount(a))
h()
```

If I had to guess, I'd say this has to do with CPython fast locals (https://github.com/python/cpython/blob/master/Objects/frameobject.c), but I'm not enough of an expert to be able to tell for certain.

If one captures the f_locals dict then calls `clear()` on it, the leak disappears.  I have no idea if this is safe, though!

**Comment by lgarrison** [comment]
[This StackOverflow discussion](https://stackoverflow.com/a/22265447) seems to confirm that fast locals is the culprit.  If fast locals is indeed being copied to a plain dict on a call to `locals()` (or `sys._getframe(0).f_locals` in our case), it would seem safe to clear that dict.  Unless it's possible for a local variable to already exist in `f_locals` but not fast locals...?

**Comment by pkgw** [comment]
Here's an experiment I did:

```python
from __future__ import print_function
import gc
from sys import getrefcount

def demo(x):
   print('D1', getrefcount(x))
   locals()
   gc.collect()
   print('D2', getrefcount(x))

x = object()
print('O1', getrefcount(x))
demo(x)
print('O2', getrefcount(x))
```

This shows to me that all of the references ought to be cleaned up when the `locals()`-calling function in question wraps up. If that's not the case for you, I think that implies that Numexpr function has a leak.

If you can find a way to wipe that dict, if you can run some test cases in `valgrind` and not see any scary warnings pop up, I bet that means what you're doing is OK.

**Comment by lgarrison** [comment]
I think the problem here is that in numexpr the locals dict is getting attached to the parent frame (the frame that calls `evaluate()`) instead of the current frame, as in your (and my) examples.  So that frame has to leave in order for the references to be cleared.

But as @pkgw and I discussed offline, it really ought to be safe to call `clear()` on a pure-Python dict; it seems implausible that it would corrupt CPython state.  So the fix would be to call `local_dict.clear()` at the end of [this function](https://github.com/pydata/numexpr/blob/master/numexpr/necompiler.py#L724-L739) (unless `local_dict` was passed explicitly).

If we agree this is the right fix, I'm happy to submit a PR.

**Comment by robbmcleod** [comment]
@lgarrison  as @pkgw says the extra reference should drop when you exit the scope. So I think the first step is to investigate the NumExpr cache system before we start assuming its a bug with CPython. You can get access to the cache variables as follows:

    from numexpr.necompiler import _names_cache, _numexpr_cache, _numexpr_last

Do you want to pull those in your production code and see if deleting the `NumExpr` objects in `_numexpr_cache` lets your garbage collection proceed?  Looking at `numexpr/interpreter.cpp` I see it is making a bunch of  `Py_INCREF(o);` calls on the operands, i.e. the input arrays, so maybe they are not being decremented as many times as they are incremented.

If that's the case one potential solution is to make the `CacheDict` only hold onto `weakref`s so that it doesn't stop garbage collection.

**Comment by robbmcleod** [comment]
@pkgw do you have a `valgrind` suppressions file that works with Python 3.6+? I have one for Python 3.5:

https://github.com/pydata/numexpr/blob/numexpr-3.0/valgrind-python.supp

but with the memory arena in Python 3.6 it's not very clean.

**Comment by lgarrison** [comment]
I agree the extra reference should drop (and does drop) when you exit the scope.  The problem is that "the scope" is the frame that calls `evaluate()`, not the frame that calls [`sys._getframe(2).f_locals`](https://github.com/pydata/numexpr/blob/master/numexpr/necompiler.py#L726).  This is because that last call creates and attaches the new locals dict to the frame specified in the argument, which is the user's frame two levels up that calls `evaluate()`.

I don't think it's a CPython bug, probably just undesired behavior in the use-case here.  But maybe I'm mistaken and there's a bug in the numexpr caching system!  The fact that we can reproduce it independent of numexpr via an explicit `_getframe()` call seems to suggest not though.

**Comment by pkgw** [comment]
@robbmcleod Hmmm, maybe [this](https://svn.python.org/projects/python/trunk/Misc/valgrind-python.supp) ? (Wrote the man too lazy to just download and compare the two files.)

But yeah, my initial comment was under the assumption that `numexpr.evaluate` was implemented in C. If it's a pure-Python function, I would really, really, really hope that clearing the locals dict couldn't cause any low-level problems.

**Comment by robbmcleod** [comment]
This is a to me a clearer example that demonstrates the problem, as it shows the scoping:

    from numexpr.necompiler import _names_cache, _numexpr_cache, _numexpr_last
    import numexpr as ne
    import numpy as np
    import sys, gc

    def memory_leak():
        a = np.arange(10)

        def good():
            print('good: Pre f_locals call', sys.getrefcount(a))
            ldict = sys._getframe(1).f_locals
            print('good: Post f_locals call', sys.getrefcount(a))
            ldict.clear()
            print('good: cleared ldict', sys.getrefcount(a))

        def bad():
            print('Pre f_locals call', sys.getrefcount(a))
            ldict = sys._getframe(1).f_locals
            print('Post f_locals call', sys.getrefcount(a))
            
        good()
        print('Exited scope of good()', sys.getrefcount(a))
        gc.collect()
        print('Collected garbage', sys.getrefcount(a))

        print('='*78)
        bad()
        print('Exited scope of bad()', sys.getrefcount(a))
        gc.collect()
        print('Collected garbage', sys.getrefcount(a))

    memory_leak()

So yes I see now that `sys._getframe({n>0}).f_locals` may be undefined behavior for CPython.

@pkgw the parsing of Python expressions is all done in Python. The actual virtual machine runs in C. And I don't think the Python.org valgrind suppressions file has been updated since Python 3.5.

@lgarrison if you want a PR on your record go ahead, or I can do it as I have push rights. Just make sure `locals_dict` isn't cleared if it was passed in as an argument.
