### ISSUE TITLE
Manywheels Builds Generating Errors

### ISSUE THREAD

**Issue by robbmcleod** [pydata/numexpr#312]
On trying to build for 2.6.7 release, the Travis side is having issues:

https://github.com/MacPython/numexpr-wheels/

Some Linux builds are erroring and not passing, and some are still erroring but passing...

https://travis-ci.org/MacPython/numexpr-wheels/builds/414659538

Looks like it's some problem with older versions of NumPy (before 1.12.0b1) that permitted negative powers to be applied to integers. I was able to replicate it in a Virtualbox environment. The version check in `expressions.py` isn't working as intended:

    _np_version >= ('1', '12', '0b1')

It won't work for 1.9 or less, as the `'9'` is compared to the `'1'` in the minor version `'12'`.  I'm thinking we should drop the bug-release alphanumeric, and only compare on a 2-element tuple of `(major_ver, minor_ver)` cast to `int`s. The only way the bug-release version would matter if someone was working with an alpha of `numpy` 1.12, which seems unlikely.

**Comment by avalentino** [comment]
Maybe you could consider using something like `distutils.version.LooseVersion`

**Comment by robbmcleod** [comment]
Yeah that would work. We used to have `pkg_resources` do it but it's very slow to import that module. `import distutils.version` is about 1.3 ms (versus > 100 ms for `import pkg_resources`, so it would slow down `import numexpr` by about 10 %.

**Comment by avalentino** [comment]
OK, there is a `numpy.lib.NumpyVersion` function that is available when you import `numpy`.

Required changes are quite limited:

```patch
--- a/numexpr/expressions.py
+++ b/numexpr/expressions.py
@@ -18,7 +18,7 @@ import numpy
 # numpy's behavoir sometimes changes with versioning, especially in regard as 
 # to when ints are cast to floats.
 # _np_version will be similar to ('1', '13', '1') for which we can use simple comparisons
-_np_version = tuple( ver for ver in numpy.__version__.split('.') )
+_np_version = numpy.lib.NumpyVersion(numpy.__version__)
 
 # Declare a double type that does not exist in Python space
 double = numpy.double
@@ -283,7 +283,7 @@ def rtruediv_op(a, b):
 
 @ophelper
 def pow_op(a, b):
-    if (_np_version >= ('1', '12', '0b1') and
+    if (_np_version >= '1.12.0b1' and
         b.astKind in ('int', 'long') and
         a.astKind in ('int', 'long') and
         numpy.any(b.value < 0)):
```

Also the slowdown at import time should be quite limited

```python
%timeit np_version = np.lib.NumpyVersion(np.__version__)
The slowest run took 7.11 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.69 µs per loop

%timeit np_version = tuple( ver for ver in np.__version__.split('.') )
The slowest run took 8.66 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.02 µs per loop
```

The main drawback IMO is that you need numpy >= 1.9 (4 years old) instead of numpy >= 1.7 that is the current requirement.

I can submit a PR if you want.

**Comment by robbmcleod** [comment]
It's ok, I did it with `distutils.version`, thanks for the tip.

**Comment by robbmcleod** [comment]
Closing, Travis seems to have built the 2.6.7 wheels now.
