### ISSUE TITLE
Invalid version number with pre-release NumPy

### ISSUE THREAD

**Issue by beojan** [pydata/numexpr#314]
Numexpr uses distutils' `StrictVersion` which gives an "invalid version number" error with a development version of NumPy.

**Comment by robbmcleod** [comment]
Can you build with https://github.com/pydata/numexpr/commit/4f4bb49e5b89efa28dd270aaedf601606a1a8727 and check if `distutils.version.LooseVersion` instead, works as desired?

**Comment by robbmcleod** [comment]
Should be fixed with 2.6.8, let me know if it's not.
