### ISSUE TITLE
'power' function is not supported

### ISSUE THREAD

**Issue by Bellator95** [pydata/numexpr#330]
Is it possible to add a ```np.power(x, d)``` function to ```numexpr``` ? It seems like it is missed because I can't find it in documentation.

**Comment by robbmcleod** [comment]
The `**` operator is supported, which does what you want:   

    import numpy as np
    import numexpr as ne
    foo = np.arange(256)
    bar = ne.evaluate('foo**2')

**Comment by robbmcleod** [comment]
Closing.
