### ISSUE TITLE
[2.6.9] Tests fails on python 3.6 missing module

### ISSUE THREAD

**Issue by tuxmaster5000** [pydata/numexpr#333]
When I try to let the tests run, it fails:
+ /usr/bin/python3.6 -c 'import numexpr; numexpr.test()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/builddir/build/BUILD/numexpr-2.6.9/numexpr/__init__.py", line 24, in <module>
    from __config__ import show as show_config, get_info
ModuleNotFoundError: No module named '__config__'

**Comment by robbmcleod** [comment]
Where did you install it, where did you clone it, and where did you run Python from? Typically this happens if Python finds NumExpr in the working directory instead of the installed version, because the `config.py` is generated by the install process.

**Comment by tuxmaster5000** [comment]
I have downloaded the source tar from pip repo.
And then build the package. Here the complete build log.
[build.log](https://github.com/pydata/numexpr/files/3093394/build.log)

**Comment by tuxmaster5000** [comment]
It looks like the tests are running in the source folder an not the installed one.

**Comment by tuxmaster5000** [comment]
Yes, running it from the installed one will work.
