### ISSUE TITLE
[2.6.9] Python 3.6 test fails with 'long' is not defined

### ISSUE THREAD

**Issue by tuxmaster5000** [pydata/numexpr#334]
======================================================================
ERROR: numexpr (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: numexpr
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/builddir/build/BUILD/numexpr-2.6.9/numexpr/__init__.py", line 38, in <module>
    from numexpr.expressions import E
  File "/builddir/build/BUILD/numexpr-2.6.9/numexpr/expressions.py", line 40, in <module>
    scalar_constant_types = [bool, int_, long, float, double, complex, bytes]
NameError: name 'long' is not defined

**Comment by robbmcleod** [comment]
The Python `2to3` script didn't run correctly. Same as issue #333 I suspect, you're not running the installed version.

Try: `import numexpr as ne: print(ne.__file__)`

**Comment by tuxmaster5000** [comment]
Yes this was it.
After force python to use the module from system path instant the current path then tests runs:
+ cd numexpr-2.6.9
+ mkdir my_check
+ pushd my_check
~/build/BUILD/numexpr-2.6.9/my_check ~/build/BUILD/numexpr-2.6.9
+ export PYTHONPATH=/builddir/build/BUILDROOT/python-numexpr-2.6.9-1.el7.x86_64/usr/lib64/python3.6/site-packages
+ PYTHONPATH=/builddir/build/BUILDROOT/python-numexpr-2.6.9-1.el7.x86_64/usr/lib64/python3.6/site-packages
+ /usr/bin/python3.6 -c 'import numexpr; numexpr.test()'
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...................................................................................................................................................................................................................
...............................*Warning*: NumPy version is lower than recommended: 1.12.1 < 1.7.0
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.6.9
NumPy version:     1.12.1
Python version:    3.6.6 (default, Mar 29 2019, 00:03:27) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Platform:          linux-x86_64-#1 SMP Mon Mar 18 15:06:45 UTC 2019
CPU vendor:        
CPU model:         
CPU clock speed:    MHz
VML available?     False
Number of threads used by default: 8 (out of 8 detected cores)
Maximum number of threads: 64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
...
----------------------------------------------------------------------
Ran 5520 tests in 7.510s

**Comment by tuxmaster5000** [comment]
But the warning message is strange.

**Comment by robbmcleod** [comment]
Warning message was fixed in #327.

**Comment by robbmcleod** [comment]
Closing, as issue appears to be resolved. Feel free to reopen if you feel differently.
