### ISSUE TITLE
unsigned integers

### ISSUE THREAD

**Issue by kenseehart** [pydata/numexpr#335]
How difficult would it be to add support for unsigned integers?

My use case requires this because I am crunching bits. I'm using shifts and bitwise logic instead of numerical operations.

63 bits is not enough. I need all 64. And if I were in 32 bit mode, I wouldn't want to waste an extra 31 bits by upcasting to 64 bit signed.

it seems to me that by neglecting unsigned integers, you generally eliminate most bit crunching use cases.

**Comment by kenseehart** [comment]
I should mention that one can do bit crunching with signed integers by remembering that negative integers back-fill with 1 when right shifted. However, there are other issues that are not so easily resolved. In particular, builtins.NotImplementedError: couldn't find matching opcode for 'and_bli'

So really the issue is support for bitwise ops, not so much unsigned integers per se.

**Comment by kenseehart** [comment]
And I can't use byte types either because lshift and rshift are not supported for that.

Looking at the blogs... I see this has been discussed a decade ago. Seems there is no significant interest. Hard to believe nobody is apparently processing bits with these tools. Apparently all relevant use cases are numerical.

**Comment by robbmcleod** [comment]
The 3.0 has support for both bitwise operations and unsigned integers:

https://github.com/pydata/numexpr/tree/numexpr-3.0

Also on PyPi:

https://pypi.org/project/numexpr3/

It has some regressions compared to 2.6 (mainly no string support and no reductions) but also a lot of new features.

**Comment by robbmcleod** [comment]
Can we close this?
