### ISSUE TITLE
NE3: Floordiv operand produces wrong results for small numbers

### ISSUE THREAD

**Issue by PeterKucirek** [pydata/numexpr#336]
When testing the `//` operand, NE3 produces `-1` for results smaller than the divisor, where the correct result is `0`. 

Example

```python
import numpy as np
import numexpr3 as ne

array = np.arange(20)
print(ne.evaluate("array // 3"))

>> [-1 -1 -1  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6]
```
**Note the first three results for 0, 1, and 2; respectively**

This is a departure from the result that Numpy gives:

```python
print(array // 3)
>> [0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6]
```

Computer Specs:

 * OS: Windows 7 Enterprise x64 SP 1
* CPU: Intel Core i7-4790

I am working from the `numexpr-3.0` with no modifications.

**Comment by robbmcleod** [comment]
I don't get the quoted behavior, rather I get the expected behavior:

    > python -c "import numpy as np; import numexpr3 as ne3; data=np.arange(20); print(ne3.evaluate('data//3')); print(data.dtype)"
    [0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6]
    int32

Furthermore the tests check this against NumPy, and they are also passing on the CI services:

https://github.com/pydata/numexpr/blob/numexpr-3.0/numexpr3/tests/test_numexpr.py

    def test_floor_div(self):
        logger.info( 'Test floor div3' )
        x = np.arange(self.ssize, dtype='int64')
        intSize = np.int64(self.ssize)
        y = ne3.NumExpr('intSize//x')()
        npt.assert_array_equal(y, intSize//x)

**Comment by robbmcleod** [comment]
Pinging @PeterKucirek, were you able to figure out what is happening on your end here?

**Comment by robbmcleod** [comment]
Closing as I believe this is resolved. Feel free to reopen if you disagree.
