### ISSUE TITLE
Installation on Python2.7 fails due to NumPy dependency

### ISSUE THREAD

**Issue by alivannikov** [pydata/numexpr#339]
Numexpr package installation currently fails for me:

> 12:37:31       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
> 12:37:31         exec(code, globals, locals)
> 12:37:31       File "/tmp/easy_install-enl424/numpy-1.17.0rc1/setup.py", line 31, in <module>
> 12:37:31         with open(os.path.join('numexpr', 'version.py')) as f:
> 12:37:31     RuntimeError: Python version >= 3.5 required.

Numpy guys dropped python2 support from version 1.17. There is related issue reported to Numpy as well:
https://github.com/numpy/numpy/issues/13911

Not sure on which side this should be fixed. Should numpexr setup.py / requirements.txt be adjusted somehow to pickup proper Numpy version depending on python runtime?

**Comment by bashtage** [comment]
There is a bug in pip/PyPI that is supplying NumPy 1.17rc to Python 2.7.  Once the release is out, this shouldn't happen.  See numpy/numpy#13911

**Comment by winstonhong15** [comment]
Any updates on this? I have the same issue

**Comment by robbmcleod** [comment]
Recommended work-around for the moment would be for people to manually install an earlier version of NumPy first?

**Comment by bashtage** [comment]
You could probably do `pip install numexpr 'numpy<=1.16'`

**Comment by alivannikov** [comment]
@bashtage Is it possible to do something like this but with requirements.txt file? I mean is it possible to limit dependency of dependency version per entry in requirements.txt so I do not need to execute separate `pip install` for each special case.

**Comment by robbmcleod** [comment]
@alivannikov yes you can replace the line in `requirements.txt` of `numpy` with `numpy<=1.16`.

**Comment by robbmcleod** [comment]
One thing we could do is the following:
`numpy; python_version >= '3.0'`
`numpy <= 1.16 ; python_version <= '2.7'`

**Comment by kayasmith106** [comment]
I have the following in my requirements:
`numpy==1.16.2'`
However when my Google App Engine Deployment starts and it tries to install the package reverse-geocoder==1.5.1 which has the following dependency:
`install_requires=['numpy>=1.11.0', 'scipy>=0.17.1'`

It fails. Relevant deployment log stetps below:

> Step` #1: Collecting setuptools==41.0.1 (from -r requirements.txt (line 2))
Step #1:   Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
Step #1: Collecting numpy==1.16.2 (from -r requirements.txt (line 61))
Step #1:   Downloading https://files.pythonhosted.org/packages/c4/33/8ec8dcdb4ede5d453047bbdbd01916dbaccdb63e98bba60989718f5f0876/numpy-1.16.2-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
Step #1: Collecting scipy==1.2.1 (from -r requirements.txt (line 81))
Step #1:   Downloading https://files.pythonhosted.org/packages/81/39/f1457091d0a45a84a2bd7815e2cf6bd45d4fe240728e9ed567cbb17c8abe/scipy-1.2.1-cp27-cp27mu-manylinux1_x86_64.whl (24.8MB)
Step #1: Collecting reverse-geocoder==1.5.1 (from -r requirements.txt (line 82))
Step #1:   Downloading https://files.pythonhosted.org/packages/0b/0f/b7d5d4b36553731f11983e19e1813a1059ad0732c5162c01b3220c927d31/reverse_geocoder-1.5.1.tar.gz (2.2MB)
Step #1:     Complete output from command python setup.py egg_info:
Step #1:     Traceback (most recent call last):
Step #1:       File "<string>", line 1, in <module>
Step #1:       File "/tmp/pip-install-7BuPRv/reverse-geocoder/setup.py", line 32, in <module>
Step #1:         long_description=read('README.txt'))
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
Step #1:         _install_setup_requires(attrs)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
Step #1:         dist.fetch_build_eggs(dist.setup_requires)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 504, in fetch_build_eggs
Step #1:         replace_conflicting=True,
Step #1:       File "/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
Step #1:         replace_conflicting=replace_conflicting
Step #1:       File "/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
Step #1:         return self.obtain(req, installer)
Step #1:       File "/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
Step #1:         return installer(requirement)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 571, in fetch_build_egg
Step #1:         return cmd.easy_install(req)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
Step #1:         return self.install_item(spec, dist.location, tmpdir, deps)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
Step #1:         dists = self.install_eggs(spec, download, tmpdir)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
Step #1:         return self.build_and_install(setup_script, setup_base)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
Step #1:         self.run_setup(setup_script, setup_base, args)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1138, in run_setup
Step #1:         run_setup(setup_script, args)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
Step #1:         raise
Step #1:       File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
Step #1:         self.gen.throw(type, value, traceback)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
Step #1:         yield
Step #1:       File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
Step #1:         self.gen.throw(type, value, traceback)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
Step #1:         saved_exc.resume()
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
Step #1:         six.reraise(type, exc, self._tb)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
Step #1:         yield saved
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
Step #1:         yield
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
Step #1:         _execfile(setup_script, ns)
Step #1:       File "/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
Step #1:         exec(code, globals, locals)
Step #1:       File "/tmp/easy_install-Sa4ajy/numpy-1.17.0rc2/setup.py", line 31, in <module>
Step #1:         license='lgpl',
Step #1:     RuntimeError: Python version >= 3.5 required.
Step #1:     
Step #1:     ----------------------------------------
Step #1: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7BuPRv/reverse-geocoder/
Step #1: You are using pip version 10.0.1, however version 19.1.1 is available.
Step #1: You should consider upgrading via the 'pip install --upgrade pip' command.
Step #1: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker@sha256:6e0e30514f339998b9cf9e9aba71b5ad8592eb1bd24ddc123a6a4f3b86b819d9" failed: exit status 1
Step #1: 
--------------------------------------------------------------------------------

ERROR: (gcloud.app.deploy) Cloud build failed. Check logs at https://console.cloud.google.com/gcr/builds/0260ec4c-836d-4126-9e58-f80c1baba748?project=623453940321 Failure status: UNKNOWN: Error Response: [2] Build failed; check build logs for details`

**Comment by robbmcleod** [comment]
@kayasmith106 this really has nothing to do with `numexpr` though. Your pinned requirement is being ignored, perhaps because you are using an older version of `pip`, although who knows:

    Step #1: File "/tmp/easy_install-Sa4ajy/numpy-1.17.0rc2/setup.py", line 31, in 
    Step #1: license='lgpl',
    Step #1: RuntimeError: Python version >= 3.5 required.

I would report it at https://github.com/numpy/numpy/issues/13911, but honestly this is part of the trouble of using old, unsupported software tooling. Probably you need to install NumPy 1.16.2 first, then other modules.

**Comment by robbmcleod** [comment]
Closing as it seems the issue was fixed on the NumPy side of things.
