### ISSUE TITLE
Add '(not in the build directory)' to the installation manual

### ISSUE THREAD

**Issue by w-klijn** [pydata/numexpr#345]
When following the installation manual as found on:
https://numexpr.readthedocs.io/en/latest/user_guide.html#building
to the letter you encounter an 'expected behavior' error (
https://github.com/pydata/numexpr/issues/130).

This is only discovered after doing a google for the error and skipping to the second hit. This time might be saved by adding the text '(not in the build directory)'  in the installation manual.

**Comment by robbmcleod** [comment]
Good point, I'll look into it, thanks.

**Comment by robbmcleod** [comment]
Fixed in 719f93719fa761fd5deed95a69fc40090969ae87. New docs are built and live, so closing. Thanks again.
