### ISSUE TITLE
Python3.7.4 test fails

### ISSUE THREAD

**Issue by pydojo** [pydata/numexpr#347]
- [ x ] Requirement 
Tue Oct 08 echo4py @15:34:54 $ pip3 show numpy
Name: numpy
Version: 1.15.0
Summary: NumPy: array processing for numbers, strings, records, and objects.
Home-page: http://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /Users/xinqi/Library/Python/3.7/lib/python/site-packages
Requires: 
Required-by: thinc, spacy, seaborn, scipy, scikit-learn, rasa-nlu, patsy, pandas, nxviz, msgpack-numpy, matplotlib, Keras, Keras-Preprocessing, Keras-Applications, h5py, numexpr
Tue Oct 08 echo4py @15:35:13 $ python3 -V
Python 3.7.4

- [ ] Installation and test issues 
Tue Oct 08 echo4py @15:31:02 $ python3 setup.py build
Warning: Assuming default configuration (numexpr/tests/{setup_tests,setup}.py was not found)/Users/xinqi/Library/Python/3.7/lib/python/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '2.7.1dev0' to '2.7.1.dev0'
  normalized_version,
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building py_modules sources
creating build
creating build/src.macosx-10.14-x86_64-3.7
creating build/src.macosx-10.14-x86_64-3.7/numexpr
building extension "numexpr.interpreter" sources
build_src: building npy-pkg config files
running build_py
creating build/lib.macosx-10.14-x86_64-3.7
creating build/lib.macosx-10.14-x86_64-3.7/numexpr
copying numexpr/cpuinfo.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr
copying numexpr/version.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr
copying numexpr/expressions.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr
copying numexpr/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr
copying numexpr/utils.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr
copying numexpr/necompiler.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr
copying build/src.macosx-10.14-x86_64-3.7/numexpr/__config__.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr
creating build/lib.macosx-10.14-x86_64-3.7/numexpr/tests
copying ./numexpr/tests/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr/tests
copying ./numexpr/tests/test_numexpr.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr/tests
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
#### ['clang', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-fno-common', '-dynamic', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk', '-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include', '-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers', '-I/usr/local/Cellar/icu4c/60.2/include'] #######
customize UnixCCompiler using build_ext
building 'numexpr.interpreter' extension
compiling C++ sources
C compiler: clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/icu4c/60.2/include

creating build/temp.macosx-10.14-x86_64-3.7/numexpr
compile options: '-I/Users/xinqi/Library/Python/3.7/lib/python/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c'
extra options: '-funroll-all-loops'
clang++: numexpr/interpreter.cpp
clang++: numexpr/module.cpp
clang++: numexpr/numexpr_object.cpp
clang: warning: optimization flag '-funroll-all-loops' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-funroll-all-loops' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-funroll-all-loops' is not supported [-Wignored-optimization-argument]
clang++ -bundle -undefined dynamic_lookup -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/usr/local/Cellar/icu4c/60.2/lib -I/usr/local/Cellar/icu4c/60.2/include build/temp.macosx-10.14-x86_64-3.7/numexpr/interpreter.o build/temp.macosx-10.14-x86_64-3.7/numexpr/module.o build/temp.macosx-10.14-x86_64-3.7/numexpr/numexpr_object.o -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -lm -o build/lib.macosx-10.14-x86_64-3.7/numexpr/interpreter.cpython-37m-darwin.so
Tue Oct 08 echo4py @15:31:31 $ python3 setup.py install
Warning: Assuming default configuration (numexpr/tests/{setup_tests,setup}.py was not found)/Users/xinqi/Library/Python/3.7/lib/python/site-packages/setuptools/dist.py:398: UserWarning: Normalizing '2.7.1dev0' to '2.7.1.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
running build_src
build_src
building py_modules sources
building extension "numexpr.interpreter" sources
build_src: building npy-pkg config files
creating numexpr.egg-info
writing numexpr.egg-info/PKG-INFO
writing dependency_links to numexpr.egg-info/dependency_links.txt
writing requirements to numexpr.egg-info/requires.txt
writing top-level names to numexpr.egg-info/top_level.txt
writing manifest file 'numexpr.egg-info/SOURCES.txt'
reading manifest file 'numexpr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.cfg'
warning: no previously-included files found matching 'numexpr/__config__.py'
warning: no previously-included files found matching 'site.cfg'
writing manifest file 'numexpr.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.14-x86_64/egg
running install_lib
running build_py
copying build/src.macosx-10.14-x86_64-3.7/numexpr/__config__.py -> build/lib.macosx-10.14-x86_64-3.7/numexpr
Skipping optional fixer: buffer
Skipping optional fixer: idioms
Skipping optional fixer: set_literal
Skipping optional fixer: ws_comma
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
#### ['clang', '-Wno-unused-result', '-Wsign-compare', '-Wunreachable-code', '-fno-common', '-dynamic', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk', '-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include', '-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers', '-I/usr/local/Cellar/icu4c/60.2/include'] #######
customize UnixCCompiler using build_ext
creating build/bdist.macosx-10.14-x86_64
creating build/bdist.macosx-10.14-x86_64/egg
creating build/bdist.macosx-10.14-x86_64/egg/numexpr
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/cpuinfo.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/version.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/expressions.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr
creating build/bdist.macosx-10.14-x86_64/egg/numexpr/tests
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/tests/__init__.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr/tests
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/tests/test_numexpr.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr/tests
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/__init__.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/interpreter.cpython-37m-darwin.so -> build/bdist.macosx-10.14-x86_64/egg/numexpr
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/__config__.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/utils.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr
copying build/lib.macosx-10.14-x86_64-3.7/numexpr/necompiler.py -> build/bdist.macosx-10.14-x86_64/egg/numexpr
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/cpuinfo.py to cpuinfo.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/version.py to version.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/expressions.py to expressions.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/tests/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/tests/test_numexpr.py to test_numexpr.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/__config__.py to __config__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/utils.py to utils.cpython-37.pyc
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/necompiler.py to necompiler.cpython-37.pyc
creating stub loader for numexpr/interpreter.cpython-37m-darwin.so
byte-compiling build/bdist.macosx-10.14-x86_64/egg/numexpr/interpreter.py to interpreter.cpython-37.pyc
creating build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying numexpr.egg-info/PKG-INFO -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying numexpr.egg-info/SOURCES.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying numexpr.egg-info/dependency_links.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying numexpr.egg-info/not-zip-safe -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying numexpr.egg-info/requires.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
copying numexpr.egg-info/top_level.txt -> build/bdist.macosx-10.14-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.14-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/numexpr-2.7.1.dev0-py3.7-macosx-10.14-x86_64.egg' and adding 'build/bdist.macosx-10.14-x86_64/egg' to it
removing 'build/bdist.macosx-10.14-x86_64/egg' (and everything under it)
Processing numexpr-2.7.1.dev0-py3.7-macosx-10.14-x86_64.egg
creating /usr/local/lib/python3.7/site-packages/numexpr-2.7.1.dev0-py3.7-macosx-10.14-x86_64.egg
Extracting numexpr-2.7.1.dev0-py3.7-macosx-10.14-x86_64.egg to /usr/local/lib/python3.7/site-packages
Adding numexpr 2.7.1.dev0 to easy-install.pth file

Installed /usr/local/lib/python3.7/site-packages/numexpr-2.7.1.dev0-py3.7-macosx-10.14-x86_64.egg
Processing dependencies for numexpr==2.7.1.dev0
Searching for numpy==1.15.0
Best match: numpy 1.15.0
Adding numpy 1.15.0 to easy-install.pth file
Installing conv-template script to /usr/local/bin
Installing f2py script to /usr/local/bin
Installing from-template script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages
Finished processing dependencies for numexpr==2.7.1.dev0
Tue Oct 08 echo4py @15:31:41 $ python3 -c "import numexpr; numexpr.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xinqi/Documents/GitHub/numexpr_zh/numexpr/__init__.py", line 24, in <module>
    from __config__ import show as show_config, get_info
ModuleNotFoundError: No module named '__config__'

**Comment by pydojo** [comment]
The fail reason is execute `python3 -c "import numexpr; numexpr.test()"` in the repository directory.
After `cd ..` and execute command above, everything is 👌
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.7.1dev0
NumPy version:     1.15.0
Python version:    3.7.4 (default, Sep  7 2019, 18:27:02) 
[Clang 10.0.1 (clang-1001.0.46.4)]
Platform:          darwin-x86_64-Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64
VML available?     False
Number of threads used by default: 4 (out of 4 detected cores)
Maximum number of threads: 64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 5522 tests in 6.718s

OK
```

**Comment by robbmcleod** [comment]
Yes lots of people run into this. We changed the documentation to warn about it, but if you can think of a nice way to emit an error that explicitly explains what the user did wrong, please let us know.
