### ISSUE TITLE
numexpr initial test does not pass. dll load failed

### ISSUE THREAD

**Issue by stelianstoica** [pydata/numexpr#349]
Hello,

I am trying to use numexpr for one of the projects I am working on, however I am getting a "dll load failed error".
I am running the test_numexpr.py from python-3.6.5\Lib\site-packages\numexpr\tests path and I am getting this error.

I have added "c:\WinPython36\python-3.6.5\Lib\site-packages\numexpr\ " to my path variable, restarted the PC but the test still fails.

I am using Windows 10 and python 32bit
c:\WinPython36\python-3.6.5\Lib\site-packages\numexpr\tests>python test_numexpr.py
Traceback (most recent call last):
  File "test_numexpr.py", line 30, in <module>
    import numexpr
  File "C:\WinPython36\python-3.6.5\lib\site-packages\numexpr\__init__.py", line 42, in <module>
    from numexpr.expressions import E
  File "C:\WinPython36\python-3.6.5\lib\site-packages\numexpr\expressions.py", line 50, in <module>
    from numexpr import interpreter
ImportError: DLL load failed: The specified module could not be found.

**Comment by robbmcleod** [comment]
It's NumExpr not really intended to be run within its own folder. Generally this causes problem with Python as the local path takes precedence over the package paths. How did you install the package in the first place? Does it not come with WinPython? In any case, you should be able to install it via `pip install numexpr` on the command line. 

Does WinPython have special console links that set the expected pathing?

**Comment by stelianstoica** [comment]
Hello,

 

Thank you very much for the quick reply.

 

The package came with winpython, of course.

 

Reinstalling numexpr did not do anything.

 

I managed to fix this issue by uninstalling numpy 1.6 and installing numpy 1.7+mkl (apparently mkl was the issue, it was a dependency not properly identified by interpreter.pyd)

 

You may close this topic since a fix has been found.

 

Sent: Friday, October 25, 2019 at 1:52 AM
