### ISSUE TITLE
Is Numexpr 3 going to be released?

### ISSUE THREAD

**Issue by beojan** [pydata/numexpr#350]
The numexpr-3.0 branch hasn't been updated in a year. Is it still going to be released, or is it abandoned?

**Comment by robbmcleod** [comment]
I think it's fair to say that work is suspended for now. With work I already do about 100 % the programming I can tolerate. If my work situation changed, then I would probably have the motivation and time to work on it again.

**Comment by aiudirog** [comment]
Would you happen to have a task list you would like to see for the 3.0 release? I completely understand having enough work at work, but if you're up to just reviewing PRs this could become a community effort with maybe a project board to organize it. This is easily one of my favorite libraries so it would be nice to help push it forward.

**Comment by robbmcleod** [comment]
I feel the big issue is to avoid regressions. So the two big items there are string/unicode support, and adding back in reductions.

https://github.com/pydata/numexpr/issues/263

https://github.com/pydata/numexpr/issues/255

Probably additionally, I would like to be able to map `np.*` to the appropriate NumExpr function. This would make it relatively easy to create a decorator that "numexperized" a function.

**Comment by mkschulze** [comment]
Looks like some effort has been done lately?

**Comment by robbmcleod** [comment]
It's on my mind, unfortunately I've been very busy with work lately.

**Comment by loijord** [comment]
Does that mean that installation of `numexpr3` is still not able? I tried these approaches:
1.  `pip install numexpr3`
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\pip-install-l563yacf\numexpr3\setup.py", line 32, in <module>
        with open( 'doc/__version__.py', 'w' ) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'doc/__version__.py'
2.  Following installation instructions on [Introduction to numexpr3](http://entropyproduction.blogspot.com/2017/02/introduction-to-numexpr-3-alpha.html):

    building 'numexpr3.interpreter' extension
    compiling C sources
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": 
    https://visualstudio.microsoft.com/downloads/

**Comment by robbmcleod** [comment]
@loijord If you clone the Github repo you shouldn't have that error with 'doc' directory not being present. Not sure where you've got the source files from? 

You also definitely have to have MSVC Build Tools installed at a minimum to compile the C source code.

**Comment by robbmcleod** [comment]
I have added the `doc` directory to the distributions with the `a6` release on PyPI.
