### ISSUE TITLE
Add wheels for Python 3.8

### ISSUE THREAD

**Issue by Harmon758** [pydata/numexpr#351]
[Python 3.8.0 has been released for about two months now](https://blog.python.org/2019/10/python-380-is-now-available.html), and [3.8.1 is expected to be released in a few days](https://www.python.org/dev/peps/pep-0569/).

**Comment by robbmcleod** [comment]
Thanks for the reminder, I missed that Appveyor had updated their images in November.

**Comment by robbmcleod** [comment]
Minor issue with Appveyor not using the right compiler for Python 3.8.1 that would mess with the `numexpr-wheels`:

https://github.com/appveyor/ci/issues/3250

**Comment by Harmon758** [comment]
This is likely because [the target is Windows 7](https://github.com/pydata/numexpr/blob/master/appveyor/run_with_env.cmd), as the build console log shows.

Also, Python 3.8.1 hasn't been released yet, so this is with Python 3.8.0, as the build console log also shows.

**Comment by Harmon758** [comment]
[Python 3.8.1 has just been released.](https://pythoninsider.blogspot.com/2019/12/python-381-376-3610-and-390a2-are-now.html)

**Comment by robbmcleod** [comment]
I'm having issues with Travis CI not having `pip` installed with the Python 3.8 environment:

https://travis-ci.org/MacPython/numexpr-wheels/builds/628908663?utm_medium=notification&utm_source=github_status

Not sure why other packages like `pytables` or `scikit-learn` aren't having this problem. Will probably have to go line-by-line through the `.travis.yml` files.

**Comment by Harmon758** [comment]
I've made [a PR](https://github.com/MacPython/numexpr-wheels/pull/4) to fix the Travis CI build by updating multibuild and dropping Python 3.4.

**Comment by robbmcleod** [comment]
Thanks for the help. I've build and uploaded wheels for 2.7.0, but I'll do an official version bump to 2.7.1 because we're removing support for 3.4 here. Probably after Christmas.

**Comment by Harmon758** [comment]
Thanks for adding them for v2.7.0 in the meantime!

**Comment by robbmcleod** [comment]
I'm wondering if we should consider moving to Azure for Windows CI.

**Comment by robbmcleod** [comment]
I've release 2.7.1 now, so closing.
