### ISSUE TITLE
Reconsider setting vml_num_threads to 1 when imported

### ISSUE THREAD

**Issue by realead** [pydata/numexpr#355]
Please reconsider the decision made in #39. Setting the number of VML-threads to 1affects performance of all other algorithms which use VML (see for example https://stackoverflow.com/q/59445147/5769463).

In my opinion, this is actually a job for VML to decide whether parallelization should be used or whether taks should be calculated in a single thread and numexpr should leave this decision to the experts from MKL.

I assume, that if mkl_serv_domain_get_max_threads>1, vml looks at the number of elements and decides what to do. 

My benchmark with numexpr 2.6.9 and MKL 2019.0.4 yields:
```
from numpy import pi
import numpy as np
import numexpr as ne

i = np.arange(1e6)
ne.set_vml_num_threads(2)
ne.set_num_threads(2)
%timeit ne.evaluate("cos(2*pi*i/100.)") # 2 th native, 2 th VML
# 3.57 ms ± 57.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)  
ne.set_vml_num_threads(1)
%timeit ne.evaluate("cos(2*pi*i/100.)") # 2 th native, 1 th VML
# 3.55 ms ± 53 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
ne.set_num_threads(1)
%timeit ne.evaluate("cos(2*pi*i/100.)") # 1 th native, 1 th VML
# 6.38 ms ± 30.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
ne.set_vml_num_threads(2)
%timeit ne.evaluate("cos(2*pi*i/100.)") # 1 th native, 2 th VML
# 6.47 ms ± 73.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Obviously more tests are needed, but it looks as if vml decides to run the calculation single-threaded anyway.

**Comment by robbmcleod** [comment]
@FrancescAlted do you remember what the consequences of not setting the VML threads to 1 was? Crashes on sparc or some similar platform?

**Comment by FrancescAlted** [comment]
That's a good question.  The original reasoning for this is exposed in: https://numexpr.readthedocs.io/en/latest/mkl.html .  Now, if I re-run [that benchmark](https://github.com/pydata/numexpr/blob/master/bench/vml_timing2.py) unchanged on my server with 4 physical cores with hyper-threading (Xeon E3-1245 v5 @ 3.50GHz), I get the next output:

```
base) francesc@francesc:~/software/numexpr/bench$ python vml_timing2.py 
NumPy version: 1.17.2
Time for an algebraic expression:     0.144 s / 7.784 GB/s
Time for a transcendental expression: 0.340 s / 3.289 GB/s
Numexpr version: 2.7.0. Using MKL: True
Time for an algebraic expression:     0.060 s / 18.679 GB/s
Time for a transcendental expression: 0.073 s / 15.267 GB/s
```

Remember, this is with the defaults `ne.set_num_threads(8)` and `ne.set_vml_num_threads(1)`

Now, if I set explicitly the next lines at the beginning of the script:

```
(base) francesc@francesc:~/software/numexpr/bench$ python vml_timing2.py 
NumPy version: 1.17.2
Time for an algebraic expression:     0.126 s / 8.899 GB/s
Time for a transcendental expression: 0.184 s / 6.073 GB/s
Numexpr version: 2.7.0. Using MKL: True
Time for an algebraic expression:     0.058 s / 19.169 GB/s
Time for a transcendental expression: 0.087 s / 12.826 GB/s
```

so, whereas it is pretty clear that NumPy benefits from setting a VML number of threads > 1 (3.3 GB/s -> 6.0 GB/S), numexpr performance suffers a bit (15.3 GB/s -> 12.8 GB/s).

That's tricky.  On one hand, users of numexpr want to execute expressions as fast as possible, but on the other hand, this slow down newer NumPy (which can leverage VML).  Mmmh, one possible solution would be not to mess with VML threads in `numexpr.__init__.py` and disable and re-enable VML threads whenever `ne.eval()` is called (hopefully the overhead of this would be small).

Of course, this is based on figures on my own machine, but if others can contribute more runs on different hardware/software configurations, that would help to adopt a more informed solution.

**Comment by FrancescAlted** [comment]
Out of curiosity, I have ran the [same benchmark](https://github.com/pydata/numexpr/blob/master/bench/vml_timing2.py) on another PC (AMD 3900X with 12 physical cores and 24 logical threads).  As it is an AMD, NumPy in Anaconda comes without MKL support.  Here is the result of using `ne.set_num_threads(1)` and `ne.set_vml_num_threads(1)`.

First, without linking numexpr with MKL:

```
NumPy version: 1.17.4
Time for an algebraic expression:     0.132 s / 8.484 GB/s
Time for a transcendental expression: 0.847 s / 1.319 GB/s
Numexpr version: 2.7.0. Using MKL: False
Time for an algebraic expression:     0.076 s / 14.779 GB/s
Time for a transcendental expression: 0.794 s / 1.408 GB/s
```

and now, linking numexpr with MKL:

```
NumPy version: 1.17.4
Time for an algebraic expression:     0.132 s / 8.446 GB/s
Time for a transcendental expression: 0.843 s / 1.326 GB/s
Numexpr version: 2.7.1. Using MKL: True
Time for an algebraic expression:     0.075 s / 14.898 GB/s
Time for a transcendental expression: 0.383 s / 2.921 GB/s
```

so, in that case, MKL/VML helps to improve performance on this AMD CPU.

Now, using the full amount of threads (`ne.set_num_threads(24)`).  First without MKL:

```
NumPy version: 1.17.4
Time for an algebraic expression:     0.129 s / 8.658 GB/s
Time for a transcendental expression: 0.813 s / 1.374 GB/s
Numexpr version: 2.7.0. Using MKL: False
Time for an algebraic expression:     0.041 s / 27.288 GB/s
Time for a transcendental expression: 0.051 s / 21.858 GB/s
```

Now, with MKL (only for numexpr, not numpy which is always non-MKL):

```
NumPy version: 1.17.4
Time for an algebraic expression:     0.132 s / 8.494 GB/s
Time for a transcendental expression: 0.841 s / 1.329 GB/s
Numexpr version: 2.7.1. Using MKL: True
Time for an algebraic expression:     0.041 s / 27.113 GB/s
Time for a transcendental expression: 0.065 s / 17.134 GB/s
```

So, in this case, and when using this modern, high-core count AMD CPU with all cores at full steam, MKL is not longer an advantage.  Mmmh, this is kind of unexpected and I wonder if this would affect how binaries for numexpr should be delivered (i.e. if with MKL support or not).

**Comment by realead** [comment]
That is somewhat strange, and I don't really understand what is going on (yet?), but for array sizes > 7e7, the version with `ne.set_vml_num_threads(8)` perform much worse than the version with `ne.set_vml_num_threads(1)` for some functions (I have tested sin, cos, exp), until then they have very similar performances (I consider the case with `ne.set_num_threads(1)`):

![image](https://user-images.githubusercontent.com/17513912/72328543-6339ce00-36b3-11ea-9633-ebbf8d5e725b.png)

Noteworthy: Both versions run with a single thread (checked with top), because vml parallelize only if there are at least about 6e3 elements and the vectors in numexpr are at most 1024 (am I right?).

What could explain that? Something on the numexpr side?

Code:

```
import numexpr as ne
import numpy as np
import perfplot


def evaluate(command):
    x = None
    z = None

    def setup(n):
        global x
        global z
        x = np.linspace(0, 1, n)
        z = np.zeros(n, dtype=np.float64)
        return command

    def fun_parallel(command):
        global x
        global z
        ne.set_vml_num_threads(8)
        ne.evaluate(command, out=z)
        
    def fun_single(command):
        global x
        global z
        ne.set_vml_num_threads(1)
        ne.evaluate(command, out=z)

    perfplot.show(
        setup=setup,
        n_range=[int(k) for k in range(int(5e7),int(2e8), int(5e6))],
        kernels=[
            fun_parallel,
            fun_single,
            ],
        labels=[command+" parallel", command+" single"],
        logx=True,
        logy=True,
        xlabel='len(x)',
        equality_check = None,
        )

ne.set_num_threads(1)
evaluate("cos(x)")
```

**Comment by robbmcleod** [comment]
@realead yes NumExpr has a block size of 1024 elements, so it won't run more than one thread until that is exceeded.
 
I suspect `perfplot` is doing some `multiprocessing` tricks or something under the hood that is messing with your benchmark. If I restrict myself to simple benchmarking, I don't observe your anomalous result.

    import numexpr as ne
    import numpy as np
    import matplotlib.pyplot as plt
    from time import perf_counter as pc

    ne.set_num_threads(1)
    expression = 'cos(x)'

    L_vector = np.logspace(7, 8, num=10)
    n_threads = (1, 2, 4, 8)
    bench = np.zeros([len(n_threads), len(L_vector)])

    for J, L in enumerate(L_vector):
        x = np.linspace(0.0, 1.0, L)
        z = np.empty_like(x)
        for I, n_thread in enumerate(n_threads):
            ne.set_vml_num_threads(n_thread)
            t0 = pc()
            ne.evaluate(expression, out=z)
            t1 = pc()
            bench[I, J] = t1 - t0

    plt.figure()
    for I, n_thread in enumerate(n_threads):
        plt.plot(L_vector, bench[I, :], '.-', label=f'{n_thread} VML threads')
    plt.legend(loc='best')
    plt.xlabel('Vector length')
    plt.ylabel('Evaluate time (s)')
    plt.show()

**Comment by robbmcleod** [comment]
@FrancescAlted We could indeed only set our VML threads value, wrapping execution of the virtual machine, perhaps right after dropping the GIL (and resetting before acquiring it)? It is sub-microsecond time-wise, so no concern there. 

My only concern is that it could cause a race condition if someone else is doing something similar. E.g. pseudo-code wise:

    saved_vml_threads = query_vml_num_threads();
    set_vml_num_threads(self->num_vml_threads);
    PY_ALLOW_THREADS

    <vm executes>
    
    set_vml_num_threads(saved_vml_threads);
    PY_END_THREADS

So if something changes the number of vml threads before we do our query, and changes it back to the actual expected value while we are running GILless, then we'll change the value back to the intermediate value. 

I found this warning document here:

https://software.intel.com/en-us/mkl-macos-developer-guide-techniques-to-set-the-number-of-threads

We might be able to use `mkl_set_num_threads_local` instead of `mkl_domain_set_num_threads`? It would require a bit of investigation. For reference:

https://software.intel.com/en-us/mkl-developer-reference-fortran-mkl-domain-set-num-threads

https://software.intel.com/en-us/mkl-developer-reference-fortran-mkl-set-num-threads-local

**Comment by realead** [comment]
thanks @robbmcleod, your measurements were an eye opener. When I run your code as it is, I get the following:

![image](https://user-images.githubusercontent.com/17513912/72413999-6dba9d00-3771-11ea-9197-84deed98debe.png)

which means that 1-threaded version is much slower than the others. However this is due to some additional costs which are paid first time `numexpr` does the evaluation for a given vector size (for whatever reasons), adding a "warmup" to the script, i.e. 

``` 
    ...
    z = np.empty_like(x)
    #warm up
    ne.evaluate(expression, out=z) # Added line!
    for I, n_thread in enumerate(n_threads):      
        ne.set_vml_num_threads(n_thread)
        ...
```
leads to

![image](https://user-images.githubusercontent.com/17513912/72414955-b410fb80-3773-11ea-9339-a69f1fdfe17b.png)

and very similar times for all number of vml-threads.

This also explains the results of perfplot: the additional cost are paid only by the first function (which is the parallelized version). Around vector size =1e8, `perfplot` switching from 100 loops to 10 loops (or maybe 10 to 1) and thus the additional cost of the first run have more weight when run times are averaged. Switching the order of functions (i.e. single-threaded version first) makes single-threaded version "slower".

Adding warming up phase to @robbmcleod's script and playing around with different functions and omp-thread-counts (via `ne.set_num_threads(...)`) I was not able to see any difference between `vml_thread_count = 1` and others. 

Here for example the result for function from @FrancescAlted's script , i.e. sin(x)**2 + cos(x)**2, for `ne.set_num_threads(8)`:

![image](https://user-images.githubusercontent.com/17513912/72416911-03592b00-3778-11ea-8a00-f8c3d70b923f.png)


Which only makes sense: for at most 1024 elements, VML would not bother with starting omp-section and would calculate it single-threaded.

Are there reasons not just to drop `ne.set_vml_num_threads(1)` in `__init__.py` (other that more benchmarks are needed to really shows that the number of vml-threads doesn't have a negative impact on performance)?

**Comment by FrancescAlted** [comment]
@realead Yes, I think your investigations solved this puzzle.  Just to double check, I re-run my previous benchmarks but adding a warm-up expression, and I can reproduce your results.  So on my AMD 3900X, with `ne.set_num_threads(24)` and `ne.set_vml_num_threads(1)` (and setting [MKL_DEBUG_CPU_TYPE=5 ](https://www.pugetsystems.com/labs/hpc/How-To-Use-MKL-with-AMD-Ryzen-and-Threadripper-CPU-s-Effectively-for-Python-Numpy-And-Other-Applications-1637/)):

```
NumPy version: 1.17.4
Time for an algebraic expression:     0.264 s / 8.481 GB/s
Time for a transcendental expression: 1.697 s / 1.317 GB/s
Numexpr version: 2.7.1. Using MKL: True
Time for an algebraic expression:     0.081 s / 27.709 GB/s
Time for a transcendental expression: 0.081 s / 27.749 GB/s
```

and now, with `ne.set_num_threads(24)` and `ne.set_vml_num_threads(24)`:

```
NumPy version: 1.17.4
Time for an algebraic expression:     0.258 s / 8.677 GB/s
Time for a transcendental expression: 1.620 s / 1.380 GB/s
Numexpr version: 2.7.1. Using MKL: True
Time for an algebraic expression:     0.081 s / 27.702 GB/s
Time for a transcendental expression: 0.080 s / 27.815 GB/s
```

so, in this case, I don't see any advantage in disabling VML threading (and you are right in your diagnostic that for 1024 elements, VML does not bother in activating OpenMP), so +1 on dropping `ne.set_vml_num_threads(1)` in `__init__.py`.

**Comment by realead** [comment]
Yet, there is a possibility to trigger vml threads with only 1024 elements - when calculations are done with complex numbers, for example for `tan`:

``` 
# setup + warm up 
x = np.linspace(0.0, 1.0, 10**7).astype(np.complex128)
z = np.empty_like(x)
ne.set_num_threads(8)
expression = 'tan(x)'
ne.evaluate(expression, out=z)

ne.set_vml_num_threads(8)
%timeit ne.evaluate(expression, out=z)
#235 ms ± 36.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

ne.set_vml_num_threads(1)
%timeit ne.evaluate(expression, out=z)
#144 ms ± 3.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

It is factor 1.6.

**Comment by robbmcleod** [comment]
So... why is there a repeated startup cost every time the size of the input array changes? I may be not remembering properly how NE2 works versus NE3, but the cache dictionary should prevent the computation cost of `evaluate` needing to rebuild an AST.

So is this additional startup cost coming from VML? Because if so, that's a pretty significant performance penalty coming from VML. I think a lot of use-cases for NumExpr are going to be unique expressions, rather than repeated expressions.

**Comment by realead** [comment]
I'm not sure, that the startup costs are a numexpr-problem. When I run the @robbmcleod's benchmark for e.g. `np.sin(x,z)`,  I can see the same problems if there is no warm-up.

One reason could be `z=np.empty_like(x)` - the OS only reserves memory without committing it, so the first time the memory touched we also measure the OS giving us the memory. 

Using  `z = np.linspace(0.0, 1.0, int(L))` touches memory and thus it is already committed by OS when used by np.sin first time. Or maybe there is some other caching going on. However, it is enough to level the field between first and second runs for `np.sin`.

Choosing  `z = np.linspace(0.0, 1.0, int(L))`  improves the situation for numexpr (without warmup), but there is still a difference between first and second run - so maybe more going on, than just simple memory reservation.

**Comment by robbmcleod** [comment]
Upon further testing, VML never turns on threads for the provided `BLOCK_SIZE1` of 1024. I cranked it up to >64k and it actually does turn on then.

Here's my testing script:

    # Want to benchmark the startup times, comparing MKL and non-MKL versions of 
    # NumExpr, and MKL and non-MKL versions of NumPy.
    import numpy as np
    import numexpr as ne
    import matplotlib.pyplot as plt
    from time import perf_counter as pc

    n_threads = [8, 4, 1]
    sizes = [2**18, 2**19, 2**20]
    n_sizes = len(sizes)
    n_trials = 10

    exprs = ['cos(x)']
    n_expr = len(exprs)
    bench = np.zeros([len(n_threads), n_expr, n_sizes, n_trials])

    for T, n_thread in enumerate(n_threads):
        if ne.use_vml:
            ne.set_num_threads(1)
            ne.set_vml_num_threads(n_thread)
        else:
            ne.set_num_threads(n_thread)

        for L, expr in enumerate(exprs):
            for K, N in enumerate(sizes):
                x = np.full(N, np.pi)
                for I in range(n_trials):
                    t0 = pc()
                    ne.evaluate(expr)
                    t1 = pc()
                    bench[T, L, K, I] = t1 - t0

    # It's apparent that VML only turns on with a larger BLOCK_SIZE. 
    plt.figure()
    for T, n_thread in enumerate(n_threads):
        for L, expr in enumerate(exprs):
            for K, N in enumerate(sizes):
                plt.semilogy(range(n_trials), bench[T, L, K, :], label=f'{expr}:{n_thread} -> {N*x.dtype.itemsize/2**20:.2f} MB')
    plt.xlabel('Trial')
    plt.ylabel('Benchmark (s)')
    plt.title(f'Using Intel VML: {ne.use_vml}, Block size: {ne.__BLOCK_SIZE1__}')
    plt.legend(loc='upper right')
    plt.savefig(f'bench_startup_vml_{ne.use_vml}_{ne.__BLOCK_SIZE1__}.png', dpi=200)
    plt.show()

First the baseline without VML support shows the expected speed-up with NumExpr threads `[1,4,8]`.
![bench_startup_vml_False_1024](https://user-images.githubusercontent.com/5999769/73143345-d47f6680-404d-11ea-826a-2769023866b6.png)

Now I compile with MKL support and `BLOCK_SIZE1 1024` and force NumExpr threads to `1` but use `set_vml_num_threads()`, I get no multi-threading.

![bench_startup_vml_True_1024](https://user-images.githubusercontent.com/5999769/73143355-e4974600-404d-11ea-8f3f-19030e1c128c.png)

Now change BLOCK_SIZE1 to be 64k elements and re-compile, and we actually see the multi-threading turn on:

![bench_startup_vml_True_65536](https://user-images.githubusercontent.com/5999769/73143387-393ac100-404e-11ea-8aa8-a08ffba0feee.png)

So yes, we should not call `set_vml_num_threads(1)` in the `__init__.py`, so I made commit c7efad14cfb47e7505ed1627f0c5abbdba57651c to comment it out. It does seem though that an update to the docs is in order, and possibly we should disable the `set_vml_num_threads()` since there doesn't seem to be a reason to use it, hence it's just a beginner trap. OTOH, it could be useful for NumPy, which doesn't seem to have such a utility function.

**Comment by FrancescAlted** [comment]
+1 for not calling `set_vml_theads(1)` during initialization and updating docs about VML multithreading being essentially useless for Numexpr. BTW, the later really needs a minimum of 64k elements to trigger multithreading or less elements can do it?

**Comment by robbmcleod** [comment]
I tried 8k and no threading, then bumped it up to 64k. I don't think it used to be like this, the developers might have made some adjustments to their thread pool behavior.

**Comment by realead** [comment]
I have made some experiments (https://github.com/realead/cyvml) concerning when multithreading of VML kicks in. The results in a nutshell

A: double-vector
```
Function    | #elements for which vml multi-threading kicks in
--------------------------
cos, sin    |  5000-6000
acos, asin  |  4000-5000
tan, atan   |  2000-3000
exp, ln     |  7000-8000
mul         |  never?
```


B: complex double-vector
```
Function    | #elements for which vml multi-threading kicks in
--------------------------

A: double-vector
```
Function    | #elements for which vml multi-threading kicks in
--------------------------
cos, sin    |  ca. 125
acos, asin  |  ca. 95
tan, atan   |  ca. 100
exp, ln     |  ca. 750,ca 1200
mul         |  2000-2500
```

As cos/sin & Co. for complex numbers are about 10 times slower than the double-versions. So it makes sense to use multi-threading for shorter vectors.

Without setting vml-number-of-threads to 1 the performance will drop somewhat for complex numbers.

**Comment by FrancescAlted** [comment]
Thanks @realead .  The possibility of having worse performance for complex numbers inside numexpr is a good point.  A possibility is to set the number of VML threads to 1 whenever complex numbers participate in the expression (and reset this setting after the evaluation).  But frankly, I don't know if that is worth the effort (some quick benchmarks would help in the decision).

**Comment by robbmcleod** [comment]
I can look into the previous suggested solution of saving the thread count when we release the GIL and then resetting it when we acquire it again (when I have time).

**Comment by fzimmermann89** [comment]
Hi, 
is there a a plan to tag a release now that the vml threads are not longer changed? 
Being able to require a version with this change would make the workaround of reading the number of threads and setting it back to the original value around each numexpr import obsolete...

**Comment by robbmcleod** [comment]
Some issues with the CDN server that hosts the built wheels for pypi not being operational anymore:

https://github.com/matthew-brett/multibuild/issues/349

Seems to be affecting other Python packages as well.

**Comment by robbmcleod** [comment]
Done with the release of 2.7.2, let me know if you run into any further problems (preferably with a new issue).
