### ISSUE TITLE
Wrote an article on this package

### ISSUE THREAD

**Issue by tirthajyoti** [pydata/numexpr#359]
I wrote an article illustrating the basic features and advantages of NumExpr and it is popular! I hope you guys like it.

**[Speed up your Numpy and Pandas with NumExpr package](https://towardsdatascience.com/speed-up-your-numpy-and-pandas-with-numexpr-package-25bd1ab0836b)**

**Comment by robbmcleod** [comment]
Hi thanks for your contribution. I think this has been left up for long enough, so closing.
