### ISSUE TITLE
not able to use all core of CPU in pandas linux .

### ISSUE THREAD

**Issue by Rishishwar** [pydata/numexpr#360]
I am trying to utilize all cores of CPU, for NumPy, I am able to use all cores, but when I am performing some operation in pandas, then again it using only one core of CPU. I have tried to set the max thread and other params, but nothin working foe me. 

eg, 

```
def `a(x):`
  # performing lot of operations  and checks. 

df.groupby(column_A).apply(a).reset_index()
```

**when system is executing Numpy operation, that time CPU is utilization most of the cores, but when it comes to pandas everything is running on single core.**

**Comment by robbmcleod** [comment]
I'm somewhat doubtful that Pandas is using NumExpr for a `groupby` calculation. Have you considered using some multiprocessing tool such as `dask`?

**Comment by Rishishwar** [comment]
@robbmcleod Even I am not sure though in windows machine I Can see groupby is utilizing all more than one core and taking just half time compare to RHEL.

**Comment by robbmcleod** [comment]
On investigation I cannot see any evidence that pandas is using `numexpr` for their `groupby` method:

https://github.com/pandas-dev/pandas/blob/v1.1.0/pandas/core/frame.py

https://github.com/pandas-dev/pandas/blob/v1.1.0/pandas/core/groupby/generic.py

It would be a very unnatural fit to do so, as this sorting algorithm is something `numexpr` would be very bad at. So absent any way for me to replicate the problem, I'm going to close this one.
