### ISSUE TITLE
update for Max() & Min() operations

### ISSUE THREAD

**Issue by N-Vikram** [pydata/numexpr#362]
Now max(a) returns single value 
a = [10,5,7,8,9,14,2,6,8]
max(a) returns 14

we want something like
a = [10,5,7,8,9,14,2,6,8]
b = [5,15,4,9,7,5,6,12,10]
max(a,b) should return 
[10,15,7,9,9,14,6,12,10]

**Comment by robbmcleod** [comment]
Already exists via the `where` function. E.g.

    c = ne.evaluate('where(a > b, a, b)')

**Comment by N-Vikram** [comment]
Thanks for the reply :)

**Comment by robbmcleod** [comment]
Sure thing, closing.
