### ISSUE TITLE
2.7.2 release not on pypi

### ISSUE THREAD

**Issue by mgorny** [pydata/numexpr#363]
It seems that the pypi package page is still listing 2.7.1 as the newest release. Is 2.7.2 ready to use?

If you're having trouble uploading it, try using `twine upload` instead of `./setup.py upload` — the latter seems no longer to work, at least for my projects.

**Comment by robbmcleod** [comment]
No, the multibuild system has broken as the provider that was gifting the wheels host to the open source community is no longer doing so. See:

https://github.com/MacPython/numexpr-wheels/issues/5

https://github.com/matthew-brett/multibuild/issues/349

https://github.com/pydata/numexpr/issues/355

So it seems the previous solution which @matthew-brett  provided has been replaced with a number of ad-hoc solutions. Personally I'm inclined to copy the Cython fix at present but I haven't had the time to fully investigate.

**Comment by robbmcleod** [comment]
Ok, finally managed to get around to this. The original `v2.7.2` tag was deleted, a new one made in its place, and the 2.7.2 version has been pushed out onto PyPi.
