### ISSUE TITLE
Import error when using numpy 1.15

### ISSUE THREAD

**Issue by kanderso-nrel** [pydata/numexpr#369]
Importing numexpr 2.7.2 fails with `ImportError: numpy.core.multiarray failed to import` when using numpy 1.15 (but works with 1.16):

```
(py36_test) C:\Users\KANDERSO\projects\rdtools>pip show numexpr
Name: numexpr
Version: 2.7.2
...

(py36_test) C:\Users\KANDERSO\projects\rdtools>pip install numpy==1.16
Collecting numpy==1.16
  Using cached numpy-1.16.0-cp36-cp36m-win_amd64.whl (11.9 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.15.0
    Uninstalling numpy-1.15.0:
      Successfully uninstalled numpy-1.15.0
Successfully installed numpy-1.16.0

(py36_test) C:\Users\KANDERSO\projects\rdtools>python -c "import numexpr"

(py36_test) C:\Users\KANDERSO\projects\rdtools>pip install numpy==1.15
Collecting numpy==1.15
  Using cached numpy-1.15.0-cp36-none-win_amd64.whl (13.5 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.16.0
    Uninstalling numpy-1.16.0:
      Successfully uninstalled numpy-1.16.0
Successfully installed numpy-1.15.0

(py36_test) C:\Users\KANDERSO\projects\rdtools>python -c "import numexpr"
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\KANDERSO\Software\Anaconda3\envs\py36_test\lib\site-packages\numexpr\__init__.py", line 26, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
ImportError: numpy.core.multiarray failed to import
```

I know numpy 1.15 isn't very recent anymore, but based on `requirements.txt` I think `numpy>=1.7` is supposed to be supported right?  Version info:

```python
>>> sys.version
'3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]'
```

**Comment by robbmcleod** [comment]
This is probably an ABI issue. I.e. the wheel was compiled for a newer version of `numpy` than what you are using. Assuming you have a free MSVC compiler (e.g. Microsoft Visual C++ Build Tools) installed, you should be able to install from the source tarball.

    pip install https://files.pythonhosted.org/packages/cf/e0/44e876061fcb05d085c35f6d572d258a44694f77e6f3c29f93e64e84700e/numexpr-2.7.2.tar.gz

If you are using Anaconda you'll probably have more luck using `conda` as opposed to `pip` for install if you want to use a specific version of NumPy.

**Comment by kanderso-nrel** [comment]
Thanks @robbmcleod for the pointer.  Is there a way to check which numpy version was used to compile a given wheel?  

RE: anaconda, thanks, but this issue first appeared in our CI which uses vanilla python and I was testing it locally to make sure I could recreate it.

**Comment by robbmcleod** [comment]
@kanderso-nrel it will be whatever version of NumPy GitHub Actions had as the latest available from pip for that version of Python. 

I dug through `numpy.distutils` and didn't see a means to embed the numpy build version into `numexpr/__config__.py`. So I've gone ahead and embedded it into `numexpr/version.py` instead, and made this file auto-generated by `setup.py` in https://github.com/pydata/numexpr/commit/5fef0feb0ddec4452fe290d374d435fdb0be0532

**Comment by kanderso-nrel** [comment]
Okay, thanks!  A suggestion for further improvement: it would be nice if this kind of import error was trapped and re-raised with some breadcrumbs about what the issue is and the relevant numpy version if possible.

**Comment by robbmcleod** [comment]
@kanderso-nrel 
What I'm thinking is trying to change setuptools `build_requires` when its running the command `bdist_wheel`. Then I can setup in GitHub Actions per-job pins for numpy to use the oldest reasonable version for each version of Python.

**Comment by robbmcleod** [comment]
This package from SciPy seems to give a route towards building against the oldest supported numpy, although I think it doesn't work for Python 2.7:

https://github.com/scipy/oldest-supported-numpy

Probably easiest to do it by hand for now, using `numpy==1.7.2` for Python 2.7.

**Comment by FrancescAlted** [comment]
We are in 2021, so I would suggest to just drop support for Python 2.7.

**Comment by robbmcleod** [comment]
I'm going to close this one and refer to people to #372 instead, which seems to be a similar problem.
