### ISSUE TITLE
Adapt the init_num_threads related tests for SPARC64 platform

### ISSUE THREAD

**Issue by antoinecarme** [pydata/numexpr#373]
Hi all,

numexpr tests fail to run properly on the SPARC64 platform preventing the correct building of Debian packages of numexpr and dependent packages (pandas, scikit-learn).

https://buildd.debian.org/status/package.php?p=numexpr&suite=sid#problem-6

![image](https://user-images.githubusercontent.com/16481992/107698722-45270e80-6cb5-11eb-9aa8-6e810e754f6b.png)

There is a developer choice that sets the number of threads to 1, whatever the setting of the environment variables. I have nothing against this.

https://github.com/pydata/numexpr/blob/cfb40aa6f4ff1ac121fe9724be946d93e8491a7c/numexpr/utils.py#L123

![image](https://user-images.githubusercontent.com/16481992/107698195-7521e200-6cb4-11eb-9079-67193039fd7e.png)

This developer choice is not reflected in the functional tests of numexpr and makes these tests fail.

https://github.com/pydata/numexpr/blob/cfb40aa6f4ff1ac121fe9724be946d93e8491a7c/numexpr/tests/test_numexpr.py#L990

I know this platform is old enough, but it is still supported. This problem is easy to fix without impacting other platforms, something like : 

```
if 'sparc' in platform.machine():
     self.assertEquals(1, numexpr._init_num_threads())
else:
     self.assertEquals(3, numexpr._init_num_threads())
```
 
Any help is welcome. I can add a PR for this.

**Comment by avalentino** [comment]
This is closed by #373.

**Comment by antoinecarme** [comment]
YEs. Thanks @avalentino.

**Comment by antoinecarme** [comment]
@avalentino 

Just a question, do you know how to update this log and relaunch the package build process ?

https://buildd.debian.org/status/package.php?p=numexpr&suite=sid#problem-6

**Comment by avalentino** [comment]
That is the build log of packages that are in the archive.
It is updated after a new upload or during archive rebuilds.
I cannot trigger a new build without uploading.

**Comment by antoinecarme** [comment]
Great. Thanks. 

Wait and see.
