### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [pydata/numexpr#375]
**Problem Description:**
On aarch64, pip install numexpr builds the wheels from source code to install it which takes some time to build the wheels than downloading and extracting the wheels from pypi. To build the wheel, development environment is also required to be installed on the user's system.

**Resolution:**
On aarch64, pip install numexpr should be able to download the wheels from pypi

@robbmcleod , please let me know if I can help in building wheel/uploading to PyPI repository by adding support in build.yml for building aarch64 wheels.

**Comment by robbmcleod** [comment]
Ok thanks for the PR.  I knew this was coming.

I will try and prepare a new release today (unlikely) or Sunday (more plausible). I'll probably have to make some changes to GitHub Actions to try and address #372. I'm guessing there are fewer issues with `aarch64` machines being out of date relative to Windows/Linux?

**Comment by robbmcleod** [comment]
Is done with the release of 2.7.3. I'll close the issue for now, feel free to re-open if you see any issues.
