### ISSUE TITLE
Vectorized SIMD evaluation

### ISSUE THREAD

**Issue by kif** [pydata/numexpr#380]
Numexpr supports already the Intel SVML for vectorial evaluation of elementary function. But it is neither free, nor open-source, nor cross-platform.

`Sleef` is another SIMD implementation of all basic math function which runs on most CPU architectures (x86, PPC, ARM ...) on all operating systems. https://sleef.org/ It would provide speed-ups in the same order as SVML.

Do you believe such addition would be valuable ? is there anybody available for mentoring ?

**Comment by FrancescAlted** [comment]
This is still worth pursuing.

**Comment by 27rabbitlt** [comment]
I’ll look at this

**Comment by FrancescAlted** [comment]
@27rabbitlt  How is that going?  Is there any show stopper that we can help with?

**Comment by 27rabbitlt** [comment]
> @27rabbitlt How is that going? Is there any show stopper that we can help with?

Would be able to push this after midterm, just in two weeks  💪
