### ISSUE TITLE
Numexpr3 fails when scalars are used in expression

### ISSUE THREAD

**Issue by sebbelese** [pydata/numexpr#381]
Hi,

I receive an error when a scalar is used in combination with numpy arrays within an expression. It seems so fundamental that I suspect something wrong on my side.

See the following code:
```
import numexpr3 as ne3
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([4,3,2,1])

expressions = ["var1","var1+var2","var1*var2","var1*2"]

for expression in expressions:
    neObj = ne3.NumExpr(expression)
    print("Expression: "+expression, " Result: "+str(neObj()))
```

The three first expressions are calculated correctly, but the third one fails:

```
Expression: var1  Result: [1 2 3 4]
Expression: var1+var2  Result: [5 5 5 5]
Expression: var1*var2  Result: [4 6 6 4]
Traceback (most recent call last):
  File "testnumexpr.py", line 10, in <module>
    neObj = ne3.NumExpr(expression)
  File "/home/sblaise/.local/lib/python3.8/site-packages/numexpr3/ne3compiler.py", line 441, in __init__
    self._assemble()
  File "/home/sblaise/.local/lib/python3.8/site-packages/numexpr3/ne3compiler.py", line 486, in _assemble
    _ASTAssembler[type(bodyItem),-1](self, bodyItem)
  File "/home/sblaise/.local/lib/python3.8/site-packages/numexpr3/ne3compiler.py", line 962, in _expression_last
    valueReg = _ASTAssembler[type(node.value)](self, node.value)
  File "/home/sblaise/.local/lib/python3.8/site-packages/numexpr3/ne3compiler.py", line 1266, in _binop
    rightRegister = _ASTAssembler[type(node.right)](self, node.right)
TypeError: _unsupported() missing 2 required positional arguments: 'self' and 'node'
```

I am using Ubuntu under windows 10 WSL2. Could it be something wrong with my setup or is the code wrong?

Thanks

**Comment by robbmcleod** [comment]
Looks like it's a change that came into play in Python 3.9:

https://docs.python.org/3/library/ast.html

    Changed in version 3.8: Class ast.Constant is now used for all constants.

    Changed in version 3.9: Simple indices are represented by their value, extended slices are represented as tuples.

    Deprecated since version 3.8: Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases. In the meantime, instantiating them will return an instance of a different class.

I'll look into it.

**Comment by robbmcleod** [comment]
@sebbelese I made a push with changes, https://github.com/pydata/numexpr/commit/51ddd622703ee5173b6ab866c1ad87cd487c93a2, can you clone, build, and test against your code?

**Comment by sebbelese** [comment]
It works, thanks! Just maybe some debug info left to clean:
` info('$ast.Binop: %s'%node.op) `

` print(f'{type(node)}: node.left is {type(node.left)}, node.right is {type(node.right)}') `

The result from the same code as above is now:
```
Expression: var1  Result: [1 2 3 4]
$ast.Binop: <_ast.Add object at 0x7f8b17ac65b0>
<class '_ast.BinOp'>: node.left is <class '_ast.Name'>, node.right is <class '_ast.Name'>
Expression: var1+var2  Result: [5 5 5 5]
$ast.Binop: <_ast.Mult object at 0x7f8b17ac6670>
<class '_ast.BinOp'>: node.left is <class '_ast.Name'>, node.right is <class '_ast.Name'>
Expression: var1*var2  Result: [4 6 6 4]
$ast.Binop: <_ast.Mult object at 0x7f8b17ac6670>
<class '_ast.BinOp'>: node.left is <class '_ast.Name'>, node.right is <class '_ast.Constant'>
Expression: var1*2  Result: [2 4 6 8]
```
