### ISSUE TITLE
Wheels for Python 3.10

### ISSUE THREAD

**Issue by itamarst** [pydata/numexpr#385]
Hi,

When you have a chance, it would be great to have wheels uploaded for Python 3.10.

**Comment by robbmcleod** [comment]
NumPy has to provide wheels first.

**Comment by itamarst** [comment]
NumPy has wheels, perhaps you need newer version of pip to install them? (https://pypi.org/project/numpy/#files). `pip install --upgrade pip` in a virtualenv and then it'll work.

(I had the exact same "there's no wheels" moment an hour ago and then remembered, upgraded to pip 21.2, and it started working.)

**Comment by robbmcleod** [comment]
Those are not official wheels by any stretch of the imagination, and they're only for multilinux and aarch64 in any case. Python 3.10 was released yesterday and those wheels are from August 15th. Probably an accidental upload. When NumPy releases wheels officially by making a post stating so on their mailing list, I'll consider examining the issue.

**Comment by bashtage** [comment]
I saw a mention today that wheel in around a month. Possibly waiting for next point release.

**Comment by robbmcleod** [comment]
Making some progress here, refactoring everything from 2to3. `setup.py` being almost completely re-written as it was some unholy dark-age alchemy of `distutils` and `numpy.distutils`, so I'm going for a pure `setuptools` formulation.

**Comment by robbmcleod** [comment]
Ok first try here is https://github.com/pydata/numexpr/commit/99ddb12b18c116f917bc4a8db33bbc431a9bcc70, I tested it on Python 3.8-3.10 on Windows, we'll see if it passes all the other CI tests.

TODO: need to test with MKL, but I don't have MKL on this new machine, so will have to source and install it.

**Comment by FrancescAlted** [comment]
FWIW, MKL is just a pip install away: https://pypi.org/project/mkl/

El dt., 9 nov. 2021, 04:57, Robert McLeod ***@***.***> va
escriure:

**Comment by robbmcleod** [comment]
@FrancescAlted MKL is free now (apparently) so it's pretty trivial to install, but I need to work out how to build with it. Hopefully can find some time next week!

**Comment by robbmcleod** [comment]
Well I think I have it working but GitHub Actions seems to be timing out on the aarch64 builds. 

The only solution I can think of is to not produce wheels for more than one aarch64 build?

**Comment by robbmcleod** [comment]
Ok, sorry for going AWOL for two weeks but I had some business travel that created a bit of a crunch period. Wheels should be up on PyPi now.
