### ISSUE TITLE
test_vml_threads_round_trip failure in our CI using Intel MKL for BLAS

### ISSUE THREAD

**Issue by RaitoBezarius** [pydata/numexpr#387]
Hi,

We are using `numexpr` most likely as a dependency of dependencies with our numerical libraries (SciPy, NumPy) ; when performing some tests, we encountered a consistent strange CI failure on GitHub Actions:

```
======================================================================
FAIL: test_vml_threads_round_trip (__main__.test_threading_config)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/numexpr-2.7.3/numexpr/tests/test_numexpr.py", line 1012, in test_vml_threads_round_trip
    self.assertEquals(n_threads, set_threads)
AssertionError: 3 != 2

----------------------------------------------------------------------
Ran 5523 tests in 6.948s

FAILED (failures=1)
```

(see more here: https://github.com/mangaki/zero/runs/4055537692?check_suite_focus=true / raw log: <https://pipelines.actions.githubusercontent.com/FqxrTre86u76M6def9uADYNBNrO2xb09AW9Gh93WhTjB57PV1c/_apis/pipelines/1/runs/19/signedlogcontent/6?urlExpires=2021-10-30T14%3A59%3A54.2604764Z&urlSigningMethod=HMACV1&urlSignature=NSANxvxOrkfzZMnvHwTzpDYySG8Sz6DNUgro%2B6dWL64%3D>).

This failure do not happen with openBLAS, only with Intel MKL. I am not very familiar with numexpr tests and this test in particular, but it seems like to be a fairly basic sanity check. Do you have any idea what would be going on? Could it be due to GitHub Actions environment?

Many thanks!

**Comment by robbmcleod** [comment]
FYI, `numexpr` is a requirement of `pandas`; that's where it's coming in from.

I'm not sure if this is just GitHub Actions. We don't actually build against MKL on GitHub Actions ourselves right now, but given that you have a ready example I will try and look at incorporating it. Normally I just build against MKL locally on my own machine.
