### ISSUE TITLE
Automatic build_py_2to3 conversion not working anymore with upstream setuptools

### ISSUE THREAD

**Issue by egaudry** [pydata/numexpr#395]
Check the report bug at https://github.com/pypa/setuptools/issues/2997.

### Python version

Python-3.7

### OS

Linux (Rocky Linux 8.5 aarch64)

### Description

Observed when building numexpr with setuptools==60.3.0, setuptools when launched from a custom build of python on aarch64 believes it deals with python2 when it is actually python3.

### Expected behavior

Proper python3 detection.

### How to Reproduce

pip install setuptools==60.3.0
pip install --no-binary :all: numexpr==2.7.3 --verbose

check numexpr/__init__.py file, it contains python2 syntax, same goes for "long" used in numexpr/expression.py

### Workaround
* SETUPTOOLS_USE_DISTUTILS=stdlib
* do not rely on build_py_2to3 conversion

**Comment by robbmcleod** [comment]
The latest version of NumExpr, 2.8.1, does not use the `2to3` script (nor have any Python 2 support or syntax).

I have not been able to build wheels for `aarch64` using GitHub Actions. They keep timing out and failing. See #390.

**Comment by egaudry** [comment]
thanks for your feedback @robbmcleod.

I don't understand why I would still get the same behavior when building 2.8.1 using pip too (i.e. having a python2 syntax). Is there a default path that would redirect to download incorrect wheel in this case ? I will need to check.

I cannot comment on the github action timeout with aarch64, sorry.

**Comment by robbmcleod** [comment]
We used to be able to build `aarch64` wheels, so there are some up there (latest for 2.7.3), but not the latest release. I don't know what GitHub Actions broke. Digging around I did find an example from Scikit Image so maybe some time I can look into it again.

**Comment by robbmcleod** [comment]
Should be resolved with the upcoming 2.8.2 release which will include these wheels. Closing.

**Comment by egaudry** [comment]
thanks @robbmcleod !
