### ISSUE TITLE
Fraction number's operator

### ISSUE THREAD

**Issue by duongkstn** [pydata/numexpr#396]
Hi, your repo are so great but I can not find the "fraction number operator". 

For example, I want a want a fraction with 6 is numerator and 5 is denominator. So I have to write `6/5` but when I want to divide two fraction numbers (say 6/5 and 3/4), I can not write `numexpr.evaluate("6/5/3/4")` since it outputs undesired result

**Comment by gdementen** [comment]
Hi. 

numexpr has the same behavior as Python in this regard and there is no such thing as a fraction number operator in Python (nor numexpr). I think you are looking for parentheses:

```python
>>> 6/5/3/4
0.09999999999999999
>>> (6/5) / (3/4)
1.5999999999999999
>>> import numexpr
>>> numexpr.evaluate("6/5/3/4")
0.09999999999999999
>>> numexpr.evaluate("(6/5) / (3/4)")
1.5999999999999999
```

**Comment by robbmcleod** [comment]
To add onto what @gdementen said, perhaps you are looking for [sympy](https://www.sympy.org/en/index.html)?  It is a Python package that can do symbolic math, like fractions.
