### ISSUE TITLE
Corrupt metadata in 2.8.1 wheels

### ISSUE THREAD

**Issue by radoering** [pydata/numexpr#398]
The `METADATA` file in the `numexpr-2.8.1.dist-info` folder of the 2.8.1 wheels seems to be corrupt. It starts as follows:
```
Metadata-Version: 2.1
Name: numexpr
Version: 2.8.1
Summary: Fast numerical expression evaluator for NumPy
Home-page: https://github.com/pydata/numexpr
Author: David M. Cooke, Francesc Alted, and others
Author-email: 
Requires-Dist: numpy (>=1.13.3)
Requires-Dist: packaging

david.m.cooke@gmail.com
faltet@gmail.com
Maintainer: Robert A. McLeod
```
After the `Author-email` keyword, there are `Requires-Dist` entries before the e-mail adresses.

Perhaps, that is also related to the fact that the metadata is not displayed correctly on PyPI ([2.8.0](https://pypi.org/project/numexpr/2.8.0/) seems to be ok whereas [2.8.1](https://pypi.org/project/numexpr/2.8.1/) seems to be cluttered).

**Comment by stephan-cr** [comment]
I would speculate that `author_email` in setup.cfg allows only one email address, [but two are given](https://github.com/pydata/numexpr/blob/master/setup.cfg#L6-L8).

**Comment by robbmcleod** [comment]
I'll just delete this field since David Cooke hasn't been heard from in a decade and Francsec has better things to do with his time.
