### ISSUE TITLE
get_optimization() is called twice

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#4]
_From [fal...@gmail.com](https://code.google.com/u/101083734699402587936/) on April 14, 2008 14:26:04_

If you apply the next patch to numexpr sources:

{{{
--- numexpr/expressions.py      ( revision 14 )
+++ numexpr/expressions.py      (working copy)
@@ -180,6 +192,7 @@

 @ophelper
 def pow_op(a, b):
-    print "get_optimization()-->", get_optimization()
   if allConstantNodes([a,b]):
       return ConstantNode(a**b)
   if isinstance(b, ConstantNode):

}}}

and run the next code:

{{{
import numpy
import threading
import numexpr

a = numpy.arange(3)

class ThreadTest(threading.Thread):
    def run(self):
        print "result-->", numexpr.evaluate('a**3', optimization="none")
        print "result-->", numexpr.evaluate('a**3', optimization="moderate")
        print "result-->", numexpr.evaluate('a**3', optimization="aggressive")

test = ThreadTest()
test.start()

}}}

you will get the next result:

{{{
result--> get_optimization()--> none
get_optimization()--> aggressive
[0 1 8]
result--> get_optimization()--> moderate
get_optimization()--> aggressive
[0 1 8]
result--> get_optimization()--> aggressive
get_optimization()--> aggressive
[0 1 8]
}}}

There are two problems here:
1. I don't know why get_optimization() is called twice
2. It seems to me that the optimization flag is used in 'aggressive' mode
   always.

Please notice that this is probably not related with threading, but the
example includes threads so as to see if the contexts work as they should.

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=3_

**Comment by AbelHutten** [comment]
Closing as stale due to inactivity. Feel free to reopen.
