### ISSUE TITLE
Installing via conda (with numpy installed and built against mkl) does not find MKL VML libraries

### ISSUE THREAD

**Issue by jaredjeya** [pydata/numexpr#409]
I'm using the latest version of conda on RHEL7 linux. 

The output of numpy.show_config() is:

```
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CNL
```

But weirdly the output of numexpr.test() starts:

```
Numexpr version:   2.8.1
NumPy version:     1.21.5
Python version:    3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0]
Platform:          linux-x86_64-#1 SMP Tue Nov 9 16:09:48 UTC 2021
CPU vendor:        
CPU model:         
CPU clock speed:    MHz
VML available?     False
Number of threads used by default: 8 (out of 12 detected cores)
```

Note "VML available: False".

How can I ensure it finds VML?

I've also tried installing from source but either it doesn't find MKL, the results are identical - or I specify the location in site.cfg as:

```
[mkl]
library_dirs = /scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/lib
include_dirs = /scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/include
libraries = mkl_rt
```

and then I get an `numexpr/numexpr_config.hpp:36:10: fatal error: mkl_vml.h: No such file or directory` error.

How do I fix these issues and get numexpr to install against mkl correctly? Through either method, though preferably through conda so I can update things easily.

**Comment by robbmcleod** [comment]
Mmm... this is really a question for the Anaconda people regarding the `conda` issues. I'm not sure who's in charge of the Linux side of `conda` at present.

For the missing `mkl_vml.h` if you try and configure it manually, is there actually a `mkl_vml.h` in `/scratch2/jjeyaretnam/programs/miniconda3/envs/general_mkl/include`? I think I've always built NumExpr with MKL by downloading MKL from Intel. I'm on Windows here mostly but it looks to me like Anaconda is packaging the DLLs/SOs but not the include files. I certainly don't have a `general_mkl` folder at all.

**Comment by robbmcleod** [comment]
Closing as I haven't heard back from the original reporter.
