### ISSUE TITLE
module 'numexpr' has no attribute '__version__'

### ISSUE THREAD

**Issue by yucsong** [pydata/numexpr#411]
module 'numexpr' has no attribute '__version__' 

This would caused pandas problem

**Comment by robbmcleod** [comment]
NumExpr has `__version__`, it's generated by `setup.py`:

https://github.com/pydata/numexpr/blob/master/setup.py

Do you have some problem with the import path perhaps?

**Comment by robbmcleod** [comment]
Going to close this one as I'm pretty sure it's a path issue and reporter did not reply.
