### ISSUE TITLE
Incorrect result with python % (modulo) operator and integer variable

### ISSUE THREAD

**Issue by arondaniel** [pydata/numexpr#413]
Python 3.9.13, numpy 1.23.0, numexpr 2.8.3

Hello and many thanks for a great library.

Using python modulo gives incorrect result if integer variable used w/ modulo operator.

>>> solar = np.array([ -135 ])

Expected:

>>> solar%360
array([225])

Incorrect answer using int variable:

>>> ne.evaluate("solar%360")
array([-135], dtype=int64)

Workaround, make left or right side a float:
>>> ne.evaluate("solar%360.")
array([225.])

**Comment by 27rabbitlt** [comment]
According to the C code in `interp_body.cpp`, we could see that numexpr directly use `operator%` in C language. 

In C/C++, -135 % 360 = -135. I don't know choosing which one is better, but it's ugly to see this unconsistency between integer operation and float operation. It's easy to unify them, and I can fix this. But I don't know which one should we preserve. Do you have any suggestions? @robbmcleod

**Comment by 27rabbitlt** [comment]
@robbmcleod Yes, it's unperformant to add one more branch. Need some time to think about the solution carefully.

**Comment by 27rabbitlt** [comment]
@robbmcleod It seems that we can use this kind of thing:

previous:
```c++
l_dest=l2 ? l1 % l2 : 0
```

updated:
```c++
l_dest=l2? (l1 % l2 + ((l1 > 0) ^ (l2 > 0)) * l2 : 0)
```

**Comment by robbmcleod** [comment]
@27rabbitlt Your function does not seem to work if the operand is zero and the modulo is positive, e.g. 
```
a = 0
n = 360
out = ne.evaluate('a % n') 
````

`out` is 360 for NumExpr but 0 for NumPy and Python. Do you want to try again with nesting your current ternary in another one to cover this specific case?

I'd appreciate a pull request with a test, if you're game.

**Comment by 27rabbitlt** [comment]
@robbmcleod sorry for late reply because I was preparing for GRE test :sob: I will try to fix it as soon as possible

**Comment by robbmcleod** [comment]
Should be fixed in https://github.com/pydata/numexpr/commit/b5c7c10c0ec80a2043dc64fe6b7c4c304bb92368. I used the following:

```
OP_MOD_III: VEC_ARG2(i_dest = i2 == 0 ? 0 :((i1 % i2) + i2) % i2);
```

which has two C `%` remainder ops, so possible performance loss, but it does pass all tests.

**Comment by 27rabbitlt** [comment]
nice fix
