### ISSUE TITLE
df.query("'tom'") produces ValueError: NumExpr 2 does not support Unicode as a dtype.

### ISSUE THREAD

**Issue by bfeeny** [pydata/numexpr#422]
Is there any fix to have have this error? Is the only fix downgrading python to 2.x?

# pandas 1.1.5
# numexpr 2.8.1
# numpy 1.19.5
# python 3.6.9
data = [['tom', 10], ['nick', 15], ['juli', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df.query("'tom'")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-04cf72efded2> in <module>()
----> 1 df.query("'tom'")

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in query(self, expr, inplace, **kwargs)
   3343         kwargs["level"] = kwargs.pop("level", 0) + 1
   3344         kwargs["target"] = None
-> 3345         res = self.eval(expr, **kwargs)
   3346 
   3347         try:

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in eval(self, expr, inplace, **kwargs)
   3473         kwargs["resolvers"] = kwargs.get("resolvers", ()) + tuple(resolvers)
   3474 
-> 3475         return _eval(expr, inplace=inplace, **kwargs)
   3476 
   3477     def select_dtypes(self, include=None, exclude=None) -> "DataFrame":

/usr/local/lib/python3.6/dist-packages/pandas/core/computation/eval.py in eval(expr, parser, engine, truediv, local_dict, global_dict, resolvers, level, target, inplace)
    344         eng = _engines[engine]
    345         eng_inst = eng(parsed_expr)
--> 346         ret = eng_inst.evaluate()
    347 
    348         if parsed_expr.assigner is None:

/usr/local/lib/python3.6/dist-packages/pandas/core/computation/engines.py in evaluate(self)
     71 
     72         # make sure no names in resolvers and locals/globals clash
---> 73         res = self._evaluate()
     74         return reconstruct_object(
     75             self.result_type, res, self.aligned_axes, self.expr.terms.return_type

/usr/local/lib/python3.6/dist-packages/pandas/core/computation/engines.py in _evaluate(self)
    112         scope = env.full_scope
    113         _check_ne_builtin_clash(self.expr)
--> 114         return ne.evaluate(s, local_dict=scope)
    115 
    116 

~/.local/lib/python3.6/site-packages/numexpr/necompiler.py in evaluate(ex, local_dict, global_dict, out, order, casting, **kwargs)
    813     # Create a signature
    814     signature = [(name, getType(arg)) for (name, arg) in
--> 815                  zip(names, arguments)]
    816 
    817     # Look up numexpr if possible.

~/.local/lib/python3.6/site-packages/numexpr/necompiler.py in <listcomp>(.0)
    812 
    813     # Create a signature
--> 814     signature = [(name, getType(arg)) for (name, arg) in
    815                  zip(names, arguments)]
    816 

~/.local/lib/python3.6/site-packages/numexpr/necompiler.py in getType(a)
    689         return bytes
    690     if kind == 'U':
--> 691         raise ValueError('NumExpr 2 does not support Unicode as a dtype.')
    692     raise ValueError("unknown type %s" % a.dtype.name)
    693 

ValueError: NumExpr 2 does not support Unicode as a dtype.

**Comment by robbmcleod** [comment]
NumExpr will function on `bytes` objects with Python > 3.5. You can have anything you want here, encoded in UTF-8 or whatnot.

This seems to be an issue for the `pandas` dev team, since it doesn't allow the method 'query' to be of type 'bytes'?
