### ISSUE TITLE
Wheels for Python 3.11

### ISSUE THREAD

**Issue by rikardn** [pydata/numexpr#423]
Python 3.11 is expected to be released today. Do you have any plans for wheels for Python 3.11 on PyPI?

**Comment by rikardn** [comment]
Sounds good! NumPy wheels for 3.11 was released to PyPI  2022-10-12

**Comment by robbmcleod** [comment]
Had to fight with PyPi yet again (sigh) but release of NumExpr 2.8.4 seems to be done from my end. Please re-open if you encounter any problems.

**Comment by rikardn** [comment]
It works well to install on my machine. Many thanks for doing this release!
