### ISSUE TITLE
ImportError: DLL load failed while importing interpreter: The specified module was not found.

### ISSUE THREAD

**Issue by SuperPypok** [pydata/numexpr#432]
Hi, I wanted to write a calculator using this library, but I ended up with this error:
![](https://cdn.discordapp.com/attachments/1014200166473023540/1087393975083729056/2023-03-20_221501.png)
`(Не найден указанный модуль - The specified module was not found.)`
I naturally installed the library, even tried reinstalling it. But nothing helps.
I'm not a very experienced programmer, so from what I've tried to solve this problem is: reinstall the library and ask ChatGPT how it's solved. Oh, well, also find information on Stackoverflow and don't understand anything.

Lib version: 2.8.4
OS: Windows 11 (build 22621.1344)
Tested with Python 3.11 and 3.10

Code:
```py
import numexpr

expr = input("Введите выражение: ")
result = numexpr.evaluate(expr)
print(f"Результат {result}")
```

**Comment by robbmcleod** [comment]
You installed the library from `pip` or `conda` or what?

What directory are you running the script from?

Is there an `interpreterXYZ.pyd` file in the provided directory?

**Comment by SuperPypok** [comment]
> You installed the library from `pip` or `conda` or what?

Installed the library via the "Python packages" button in PyCharm.


> What directory are you running the script from

I run the script through PyCharm.


> Is there an `interpreterXYZ.pyd` file in the provided directory

I must have misunderstood what you meant. So I'll tell you that there is no such file in the "pythonProject1" folder that PyCharm created for me and in which I have this code.

**Comment by robbmcleod** [comment]
I don't have any familiarity with PyCharm. Maybe file a bug report with them, and link in this issue?

**Comment by SuperPypok** [comment]
Well, let's give it a try.

**Comment by SuperPypok** [comment]
It fixed itself somehow.
Thank you for your reply. And you can see my calculator [here](https://github.com/SuperPypok/MEGA-SuperFeda-s-calculator).
