### ISSUE TITLE
Installing takes wayyyy to long for some reason

### ISSUE THREAD

**Issue by shroominic** [pydata/numexpr#435]
Context:
![Screenshot 2023-04-21 at 16 37 03](https://user-images.githubusercontent.com/34897716/233663713-d5973a7a-e093-4559-9d83-19d22b074772.png)

**Comment by robbmcleod** [comment]
I don't have any access to ARM64 machines, sorry.

**Comment by shroominic** [comment]
You can get a free on on AWS

![Screenshot 2023-04-21 at 18 48 04](https://user-images.githubusercontent.com/34897716/233691206-fb230ab9-7aea-422d-8e45-9a1357959367.png)
