### ISSUE TITLE
Signature for `validate()` Function

### ISSUE THREAD

**Issue by robbmcleod** [pydata/numexpr#437]
I'd like to solicit advice/opinions from NumExpr users here. Since we seem to have a lot of people who use the package as a tool to execute equations based on human input like a line edit widget in a GUI, it seems we need the conjugate to the `re_evaluate()` function, a `validate()` function. The `validate()` function should take the exact same inputs as `evaluate` but it will not actually execute the compiled expression, as that's potentially a costly operation. The concept is you should be able to call `validate()` and then `re_evaluate()` safely.

The main question in my head is how to handle the return. I can think of three options:

1. Return `None` on success, and raise exceptions as usual. This requires the developer to use `try ... except .. finally` blocks.
2. Return a `bool` and if any exception happens attach it to the function handle with a decorator. So on false, the developer has the option of checking the exception. Feels a little too much like C++ to me.
3. Have a `Optional[Exception]` return type, that returns `None` on success and the exception if it would have otherwise been raised.

Personally I currently favor 3. but would be interested in other options as well.

**Comment by gdementen** [comment]
I would not use option 2 as is. Either you just return a boolean value and the exception is not available at all, or you use a more Pythonic approach to make the exception available (1 or 3). I like option 3 too, but I wonder if the name can be made more explicit, especially for those who only care whether the arguments are valid or not. The following is a bit awkward/confusing:
```python
if not validate(*args):
    # success
```

But I am probably overthinking this as the following reads fine to me:
```python
exception = validate(*args)
if exception is None:
    # success
```
Also, I wonder if several exceptions couldn't occur during validation, in which case a list would be more appropriate.

**Comment by kwunlyou** [comment]
Our project badly needs this function. Could you point out which methods could be (re)used to implement `validate`? Probably, we could contribute.

**Comment by robbmcleod** [comment]
I ended up going with a return type of `Optional[Exception]`. I.e. it returns `None` on success and an Exception object otherwise.

@kwunlyou I made a commit for a prototype version.

https://github.com/pydata/numexpr/commit/21ff376a0853aff6aea63343c6010d6434917319

If you would like to help, perhaps you could test it in your application.

**Comment by kwunlyou** [comment]
Thanks, @robbmcleod. Very helpful. Unfortunately, our project can't directly use the `validate` function. In our project, we have hundreds of `str` expression equations. An input in one equation (e.g., `z=ay+b`) could be output from another one (e.g., `y=cx+d`). The chained equations will be a large directed graph. The computation is quite expensive if we use `local_dict` and `global_dict`. I will build an in-house `validate` for our project, basically, it will be equivalent to this code block

```python
        context = getContext(kwargs)
        expr_key = (ex, tuple(sorted(context.items())))
        if expr_key not in _names_cache:
            _names_cache[expr_key] = getExprNames(ex, context)
        names, ex_uses_vml = _names_cache[expr_key]
```

**Comment by robbmcleod** [comment]
Closing with release of 2.8.5.
