### ISSUE TITLE
ModuleNotFoundError: No module named 'numexpr.interpreter'

### ISSUE THREAD

**Issue by Jeffer1980** [pydata/numexpr#438]
Hi,

I'm getting the following error when trying to import numexpr:

> >     from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
> 
> ModuleNotFoundError: No module named 'numexpr.interpreter'

Python version 3.10.11
Numexpr 2.8.4

**Comment by robbmcleod** [comment]
Typically this happens when people do something like this:

```
git clone https://github.com/pydata/numexpr.git
cd numexpr
pip install .
python -ic "import numexpr"
```

Because then the local directory `numexpr` trumps the one in `site-packages`, and of course the `interpreter.pyd/so` file isn't there in the local directory.

**Comment by robbmcleod** [comment]
Closing as we haven't heard back from the reporter.
