### ISSUE TITLE
Hash pin github workflow dependencies 

### ISSUE THREAD

**Issue by joycebrum** [pydata/numexpr#441]
## Description

Hi again, I would like to suggest another security practice recommended by the [OpenSSF Scorecard][scorecard-repo], and the [GitHub itself][github-hashpin], which is to hash pin the CI dependencies to prevent dependency-confusion, typosquatting and tag renaming attacks. 

This means:
- Hash pinning GitHub Workflow actions.
- Using --require-hashes on pip installs.

Along with hash-pinning dependencies, I also recommend adopting dependabot or renovatebot to help keep the dependencies up to date. Both tools can update  hashes and associated semantic version comments. 

Let me know if you are open to evaluate those changes and I'll submit the PR ASAP. 

Any questions or concerns just let me know.
Thanks!

## Additional Context

Regarding Github Actions:
A [tag renaming attack][tag-renaming] is a type of attack whereby an attacker:
- Hijack an action.
- Upload a malicious version.
- Replace existing tags with malicious versions.

Regarding package managers (such as pip):
A [dependency-confusion][deps-confusion] attack occurs when an attacker:
- Find the name of a package that the victims wants to install
- Create an identically named package and publish it under the public or default registry.
- Assign the package with a higher version number to trick the package manager tool to download it from the public repo.

A [typosquatting attack][typosquatting] is a type of attack whereby an attacker:
- Create a malicious package
- Publish it with a similar name of a known package (example: numpi instead of numpy)

For more informations about the dependency-update tools:
- [Dependabot][dependabot]
- [Renovatebot][renovatebot]

[scorecard-repo]: https://github.com/ossf/scorecard
[tag-renaming]: https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash
[deps-confusion]: https://www.websecuritylens.org/how-dependency-confusion-attack-works-and-how-to-prevent-it/ 
[typosquatting]: https://snyk.io/blog/typosquatting-attacks/ 
[dependabot]: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
[renovatebot]:https://www.mend.io/renovate/
[github-hashpin]: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

**Comment by diogoteles08** [comment]
Hey! This issue/PR has been idle for quite some time. Do you plan on considering this suggestion?

For your specific case, hash-pinning your dependencies on [build.yml](https://github.com/pydata/numexpr/blob/master/.github/workflows/build.yml) should be valuable because it's responsible for uploading your wheels to the releases, right? So any malicious or broken changes on the unpinned dependencies on that workflows could endanger possible users that consumes those wheels.

In case you don't show interest on these changes, we'll probably wait up to 2 more months and close the issue.

Thanks!
