### ISSUE TITLE
It is not possible to disable sanitization via `NUMEXP_SANITIZE` when using `numexpr.NumExpr`

### ISSUE THREAD

**Issue by loichuder** [pydata/numexpr#450]
While encountering #449, I tried to get rid of it by disabling the sanitization. 

Unfortunately, the code I am calling is using `numexpr.NumExpr` so that setting `NUMEXP_SANITIZE` to `0` does not work. (`NUMEXP_SANITIZE`  is only checked when using `validate`.)

Is this the intended behaviour ?

**Comment by 27rabbitlt** [comment]
It seems that `sanitize` works only before evaluation but not when `NumExpr` is created. I don't know if there is any benefit allowing `NumExpr` not being sanitized. I guess it's unintended.
