### ISSUE TITLE
Please upload a pure python wheel to PyPi

### ISSUE THREAD

**Issue by dvvilkins** [pydata/numexpr#455]
I need it to use micropip to install the package. micropip will produce an error if it cannot find a pure Python wheel. To determine if a package has a pure Python wheel manually, you can open its PyPi page and go to the “Download files” tab. If this tab doesn’t contain a file *py3-none-any.whl then the pure Python wheel is missing.

**Comment by gdementen** [comment]
Well, numexpr contains C/compiled code, so AFAIK, it is not possible to provide pure python wheels.

**Comment by FrancescAlted** [comment]
That's correct, numexpr is not a pure Python package.  Closing.
