### ISSUE TITLE
``global_dict`` input ignored in version 2.8.7

### ISSUE THREAD

**Issue by euklid321** [pydata/numexpr#456]
With ``numexpr=2.8.7``, the global dict input of ``numexpr.evaluate`` seems to be ignored:

```
import numexpr as ne

a = 1
b = 1

print(ne.evaluate("a + b + c", global_dict={"c": 1}))

# Result with numexpr=2.8.4
# 3

# Results with numexpr=2.8.7
# KeyError: 'c'
```

**Comment by 27rabbitlt** [comment]
This is caused by adding `validate` function and changing the logic of `evaluate` function. 

`evaluate` function will firstly call `validate` and if nothing wrong then call `re_evaluate`. But `re_evaluate` previously doesn't take `global_dict` as an argument, which causes the bug.

**Comment by 27rabbitlt** [comment]
should be closed by https://github.com/pydata/numexpr/pull/457

**Comment by FrancescAlted** [comment]
This can be closed, right @27rabbitlt  and @euklid321 ?

**Comment by 27rabbitlt** [comment]
Yes, thanks!
