### ISSUE TITLE
Forbidden Control Character Error for imaginary element

### ISSUE THREAD

**Issue by skuschel** [pydata/numexpr#459]
I believe that https://github.com/pydata/numexpr/commit/397cc98359301d0e7b96aaa6d3c79419d1d4f189 introduced a bug or at least it changed the behavior:

I used to do something like this, of course with x being a large array:
```
import numexpr as ne
x = 5
y = ne.evaluate('exp(1.j*x)')
```
As of the mentioned change, this gives me an "Expression has forbidden control character" error. 
It works with ints e.g `'exp(1j*x)'`, but `'exp(1.5j*x)'` is also raising the error.

**Comment by FrancescAlted** [comment]
Fixed by #462
