### ISSUE TITLE
support for class instant variables.     (self.abc)

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#46]
_From [kkb...@gmail.com](https://code.google.com/u/116631529576673851438/) on February 20, 2011 21:34:15_

class t:
    def **init**(self):
        self.t = 1
    def test(self, a):
        numexpr.evaluate('a + self.t')
test = t()
t.test(2)

I think evaluate() should be able to process 'self.t' but it doesn't

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=46_

**Comment by paddyroddy** [comment]
just saying f-strings allow you to use class variables
