### ISSUE TITLE
2.9.0 tar.gz is missing on pypi

### ISSUE THREAD

**Issue by thebaptiste** [pydata/numexpr#471]
Hello

For the new 2.9.0 release, there are only wheels available on pypi. No tar.gz file. Is it intentional ?
Of course I can do without it but I'm used to build numexpr from pypi sources...

Regards

**Comment by FrancescAlted** [comment]
Right.  That was an oversight on my side. Sorry.

**Comment by thebaptiste** [comment]
Thanks for the upload
