### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by emmaai** [pydata/numexpr#494]
Wondering if any appetite to support multithreading usage with `ne.evaluate`? From my recent experiment and test, it looks as long as the global dict `_numexpr_last` is avoided, or `ne.evaluate` doesn't share `ne.re_evaluate` routine, it's safe to run `ne.evaluate` in threading. From the comment line I read https://github.com/pydata/numexpr/blob/7484828ac5e3454201169f81d5d90a13203d988d/numexpr/necompiler.py#L782-L783
it appears to me that it doesn't require much work to achieve, and it's in consideration. Thanks!

**Comment by FrancescAlted** [comment]
Thanks for your proposal. It turns out that numexpr is mainly in maintenance mode, so I don't think we can put resources on this anytime soon.  Having said that, this feature sounds quite appealing, so if you find the time to address that via a PR, we will be happy to review it.

**Comment by emmaai** [comment]
will put into a pr soon, thanks!

**Comment by emmaai** [comment]
pr is in, may I have a review? thanks a lot!
