### ISSUE TITLE
evaluate global_dict argument ignored

### ISSUE THREAD

**Issue by gdementen** [pydata/numexpr#497]
```python
>>> ne.evaluate('a', local_dict={'a': 1})
array(1, dtype=int32)
>>> ne.evaluate('a', global_dict={'a': 1})
KeyError: 'a'
```
The problem is a regression introduced in https://github.com/pydata/numexpr/commit/21ff376a0853aff6aea63343c6010d6434917319 because global_dict is not passed to re_evaluate (which does not support global_dict either)

**Comment by FrancescAlted** [comment]
Ok, so `global_dict` is not honored since that commit (May 23, 2023)?  That probably means that not many people use it.  Maybe should we deprecate it; or do you think there is some use for it?  If so, a PR would be appreciated.
