### ISSUE TITLE
Python 3.13 wheels?

### ISSUE THREAD

**Issue by cbrnr** [pydata/numexpr#498]
I saw that several bugs related to Python 3.13 have already been addressed, so I was wondering if numexpr already supports 3.13, and if so, if and when binary wheels will be available on PyPI. Thanks and keep up the great work!

**Comment by cbrnr** [comment]
Apparently, CI already produces wheels for Python 3.13. Would it be possible to cut a new release?

**Comment by FrancescAlted** [comment]
Sorry for the delay.  New 2.10.2 is out with wheels for Python 3.13.
