### ISSUE TITLE
Add conjugate() function

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#57]
_From [pierre.c...@gmail.com](https://code.google.com/u/105358803093019457519/) on September 06, 2011 11:27:16_

This is a request for enhancement, to add the complex-conjugate to the list of supported functions (currently, one has to type 'complex(a.real, -a.imag)', which is fine, but less readable.

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=57_

**Comment by robbmcleod** [comment]
I think this one has been fixed for several years now, so closing.
