### ISSUE TITLE
Numexpr 2.0 only accepts 31 different variables as input

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#67]
_From [gdemen...@gmail.com](https://code.google.com/u/116605672876360875462/) on December 06, 2011 12:03:50_

Numpy 1.4.2 accepted expressions with up to 249 different variables (I got this number empirically and I'm not sure why this isn't 255) but in any case, it was way more than the current version.

See attached test case.

Fixing the root cause would probably be difficult because it comes from the NPY_MAXARGS constant in numpy, but it might be possible to have some kind of workaround.

**Attachment:** [many_vars.py](http://code.google.com/p/numexpr/issues/detail?id=67)

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=67_

**Comment by takahashi64** [comment]
It seems (90% sure) this issue only occurs if there < 32 unique variable names in the expression. There could be > 32 atomic boolean conditions in the expression if some variable names appear more than once.

**Comment by takahashi64** [comment]
@FrancescAlted would this issue be quick to fix? Do you know of any work-arounds?

**Comment by robbmcleod** [comment]
The error is raised here:

https://github.com/numpy/numpy/blob/dc27edb92ec70b5c0ade8ecd1ed78884a0a0a5dc/numpy/core/src/multiarray/nditer_constr.c

in NpyIter_AdvancedNew().

Probably you would have to recompile numpy with NPY_MAXARGS = 256 and NPY_MAXDIMS=256, which are #defined in 

numpy/core/include/numpy/ndarraytypes.h 

I just recompiled NumPy with this and then NumExpr and yes, it works up to 248 in my case.  It gets really expensive, however.  

python many_vars.py 
trying with 1 variables...
ok, evaluated in 0.000415325 s
trying with 2 variables...
ok, evaluated in 0.000404835 s
trying with 3 variables...
ok, evaluated in 0.000442743 s
trying with 4 variables...
ok, evaluated in 0.000537872 s
trying with 5 variables...
ok, evaluated in 0.000671625 s
trying with 6 variables...
ok, evaluated in 0.000880957 s
trying with 7 variables...
ok, evaluated in 0.000924826 s
trying with 8 variables...
ok, evaluated in 0.000935793 s
trying with 9 variables...
ok, evaluated in 0.00108194 s
trying with 10 variables...
ok, evaluated in 0.0012455 s
trying with 11 variables...
ok, evaluated in 0.00123024 s
trying with 12 variables...
ok, evaluated in 0.00169849 s
trying with 13 variables...
ok, evaluated in 0.00209165 s
trying with 14 variables...
ok, evaluated in 0.00177813 s
trying with 15 variables...
ok, evaluated in 0.00214672 s
trying with 16 variables...
ok, evaluated in 0.00193763 s
trying with 17 variables...
ok, evaluated in 0.00233626 s
trying with 18 variables...
ok, evaluated in 0.00240397 s
trying with 19 variables...
ok, evaluated in 0.0033772 s
trying with 20 variables...
ok, evaluated in 0.00267887 s
trying with 21 variables...
ok, evaluated in 0.00323892 s
trying with 22 variables...
ok, evaluated in 0.00314403 s
trying with 23 variables...
ok, evaluated in 0.00314713 s
trying with 24 variables...
ok, evaluated in 0.00349092 s
trying with 25 variables...
ok, evaluated in 0.00397134 s
trying with 26 variables...
ok, evaluated in 0.00386024 s
trying with 27 variables...
ok, evaluated in 0.00392675 s
trying with 28 variables...
ok, evaluated in 0.00437069 s
trying with 29 variables...
ok, evaluated in 0.00562549 s
trying with 30 variables...
ok, evaluated in 0.00482774 s
trying with 31 variables...
ok, evaluated in 0.00500846 s
trying with 32 variables...
ok, evaluated in 0.00534034 s
trying with 33 variables...
ok, evaluated in 0.00542617 s
trying with 34 variables...
ok, evaluated in 0.00564599 s
trying with 35 variables...
ok, evaluated in 0.00709629 s
trying with 36 variables...
ok, evaluated in 0.00629997 s
trying with 37 variables...
ok, evaluated in 0.00672841 s
trying with 38 variables...
ok, evaluated in 0.00673556 s
trying with 39 variables...
ok, evaluated in 0.00690889 s
trying with 40 variables...
ok, evaluated in 0.00792551 s
trying with 41 variables...
ok, evaluated in 0.00771213 s
trying with 42 variables...
ok, evaluated in 0.00766611 s
trying with 43 variables...
ok, evaluated in 0.00815511 s
trying with 44 variables...
ok, evaluated in 0.00912094 s
trying with 45 variables...
ok, evaluated in 0.00891018 s
trying with 46 variables...
ok, evaluated in 0.00889468 s
trying with 47 variables...
ok, evaluated in 0.00957608 s
trying with 48 variables...
ok, evaluated in 0.0103033 s
trying with 49 variables...
ok, evaluated in 0.010169 s
trying with 50 variables...
ok, evaluated in 0.0105221 s
trying with 51 variables...
ok, evaluated in 0.0114999 s
trying with 52 variables...
ok, evaluated in 0.0114706 s
trying with 53 variables...
ok, evaluated in 0.0115502 s
trying with 54 variables...
ok, evaluated in 0.0119257 s
trying with 55 variables...
ok, evaluated in 0.0125194 s
trying with 56 variables...
ok, evaluated in 0.0127141 s
trying with 57 variables...
ok, evaluated in 0.0133467 s
trying with 58 variables...
ok, evaluated in 0.0135512 s
trying with 59 variables...
ok, evaluated in 0.0139196 s
trying with 60 variables...
ok, evaluated in 0.0143304 s
trying with 61 variables...
ok, evaluated in 0.0146461 s
trying with 62 variables...
ok, evaluated in 0.0157046 s
trying with 63 variables...
ok, evaluated in 0.0159061 s
trying with 64 variables...
ok, evaluated in 0.01718 s
trying with 65 variables...
ok, evaluated in 0.016849 s
trying with 66 variables...
ok, evaluated in 0.0174716 s
trying with 67 variables...
ok, evaluated in 0.0176535 s
trying with 68 variables...
ok, evaluated in 0.0180471 s
trying with 69 variables...
ok, evaluated in 0.0184028 s
trying with 70 variables...
ok, evaluated in 0.019459 s
trying with 71 variables...
ok, evaluated in 0.0198233 s
trying with 72 variables...
ok, evaluated in 0.0199828 s
trying with 73 variables...
ok, evaluated in 0.0208547 s
trying with 74 variables...
ok, evaluated in 0.0210028 s
trying with 75 variables...
ok, evaluated in 0.0219126 s
trying with 76 variables...
ok, evaluated in 0.0225286 s
trying with 77 variables...
ok, evaluated in 0.0227201 s
trying with 78 variables...
ok, evaluated in 0.0237749 s
trying with 79 variables...
ok, evaluated in 0.0241215 s
trying with 80 variables...
ok, evaluated in 0.02423 s
trying with 81 variables...
ok, evaluated in 0.0255072 s
trying with 82 variables...
ok, evaluated in 0.0259476 s
trying with 83 variables...
ok, evaluated in 0.0268137 s
trying with 84 variables...
ok, evaluated in 0.0267978 s
trying with 85 variables...
ok, evaluated in 0.0280602 s
trying with 86 variables...
ok, evaluated in 0.0289359 s
trying with 87 variables...
ok, evaluated in 0.0287268 s
trying with 88 variables...
ok, evaluated in 0.0290384 s
trying with 89 variables...
ok, evaluated in 0.0297 s
trying with 90 variables...
ok, evaluated in 0.0306613 s
trying with 91 variables...
ok, evaluated in 0.0320449 s
trying with 92 variables...
ok, evaluated in 0.0327687 s
trying with 93 variables...
ok, evaluated in 0.0336473 s
trying with 94 variables...
ok, evaluated in 0.0339358 s
trying with 95 variables...
ok, evaluated in 0.0393791 s
trying with 96 variables...
ok, evaluated in 0.0343077 s
trying with 97 variables...
ok, evaluated in 0.0359435 s
trying with 98 variables...
ok, evaluated in 0.0373576 s
trying with 99 variables...
ok, evaluated in 0.0377469 s
trying with 100 variables...
ok, evaluated in 0.0381837 s
trying with 101 variables...
ok, evaluated in 0.0385628 s
trying with 102 variables...
ok, evaluated in 0.0394788 s
trying with 103 variables...
ok, evaluated in 0.0403104 s
trying with 104 variables...
ok, evaluated in 0.0410438 s
trying with 105 variables...
ok, evaluated in 0.0420082 s
trying with 106 variables...
ok, evaluated in 0.041029 s
trying with 107 variables...
ok, evaluated in 0.0423694 s
trying with 108 variables...
ok, evaluated in 0.0424745 s
trying with 109 variables...
ok, evaluated in 0.0447328 s
trying with 110 variables...
ok, evaluated in 0.0447147 s
trying with 111 variables...
ok, evaluated in 0.0453596 s
trying with 112 variables...
ok, evaluated in 0.0479591 s
trying with 113 variables...
ok, evaluated in 0.0473073 s
trying with 114 variables...
ok, evaluated in 0.047138 s
trying with 115 variables...
ok, evaluated in 0.0479777 s
trying with 116 variables...
ok, evaluated in 0.0502431 s
trying with 117 variables...
ok, evaluated in 0.0501194 s
trying with 118 variables...
ok, evaluated in 0.0576627 s
trying with 119 variables...
ok, evaluated in 0.0517137 s
trying with 120 variables...
ok, evaluated in 0.0545006 s
trying with 121 variables...
ok, evaluated in 0.0549116 s
trying with 122 variables...
ok, evaluated in 0.0555272 s
trying with 123 variables...
ok, evaluated in 0.0544987 s
trying with 124 variables...
ok, evaluated in 0.0561147 s
trying with 125 variables...
ok, evaluated in 0.0579624 s
trying with 126 variables...
ok, evaluated in 0.0593174 s
trying with 127 variables...
ok, evaluated in 0.0595605 s
trying with 128 variables...
ok, evaluated in 0.0602615 s
trying with 129 variables...
ok, evaluated in 0.0595906 s
trying with 130 variables...
ok, evaluated in 0.0620375 s
trying with 131 variables...
ok, evaluated in 0.0637538 s
trying with 132 variables...
ok, evaluated in 0.0641408 s
trying with 133 variables...
ok, evaluated in 0.0651319 s
trying with 134 variables...
ok, evaluated in 0.0665686 s
trying with 135 variables...
ok, evaluated in 0.0653708 s
trying with 136 variables...
ok, evaluated in 0.0671101 s
trying with 137 variables...
ok, evaluated in 0.071934 s
trying with 138 variables...
ok, evaluated in 0.0697868 s
trying with 139 variables...
ok, evaluated in 0.0703163 s
trying with 140 variables...
ok, evaluated in 0.0706489 s
trying with 141 variables...
ok, evaluated in 0.070672 s
trying with 142 variables...
ok, evaluated in 0.0727193 s
trying with 143 variables...
ok, evaluated in 0.0744975 s
trying with 144 variables...
ok, evaluated in 0.0750542 s
trying with 145 variables...
ok, evaluated in 0.074894 s
trying with 146 variables...
ok, evaluated in 0.0771751 s
trying with 147 variables...
ok, evaluated in 0.0764072 s
trying with 148 variables...
ok, evaluated in 0.0804846 s
trying with 149 variables...
ok, evaluated in 0.080487 s
trying with 150 variables...
ok, evaluated in 0.0797932 s
trying with 151 variables...
ok, evaluated in 0.0836003 s
trying with 152 variables...
ok, evaluated in 0.0813906 s
trying with 153 variables...
ok, evaluated in 0.0872715 s
trying with 154 variables...
ok, evaluated in 0.0866754 s
trying with 155 variables...
ok, evaluated in 0.0832951 s
trying with 156 variables...
ok, evaluated in 0.0872774 s
trying with 157 variables...
ok, evaluated in 0.0864034 s
trying with 158 variables...
ok, evaluated in 0.0931115 s
trying with 159 variables...
ok, evaluated in 0.0889781 s
trying with 160 variables...
ok, evaluated in 0.0932579 s
trying with 161 variables...
ok, evaluated in 0.0949595 s
trying with 162 variables...
ok, evaluated in 0.096312 s
trying with 163 variables...
ok, evaluated in 0.095612 s
trying with 164 variables...
ok, evaluated in 0.0989642 s
trying with 165 variables...
ok, evaluated in 0.104634 s
trying with 166 variables...
ok, evaluated in 0.0996132 s
trying with 167 variables...
ok, evaluated in 0.102031 s
trying with 168 variables...
ok, evaluated in 0.100876 s
trying with 169 variables...
ok, evaluated in 0.101001 s
trying with 170 variables...
ok, evaluated in 0.103696 s
trying with 171 variables...
ok, evaluated in 0.1071 s
trying with 172 variables...
ok, evaluated in 0.103842 s
trying with 173 variables...
ok, evaluated in 0.10729 s
trying with 174 variables...
ok, evaluated in 0.109372 s
trying with 175 variables...
ok, evaluated in 0.112159 s
trying with 176 variables...
ok, evaluated in 0.109097 s
trying with 177 variables...
ok, evaluated in 0.11347 s
trying with 178 variables...
ok, evaluated in 0.113163 s
trying with 179 variables...
ok, evaluated in 0.118133 s
trying with 180 variables...
ok, evaluated in 0.112491 s
trying with 181 variables...
ok, evaluated in 0.114572 s
trying with 182 variables...
ok, evaluated in 0.115374 s
trying with 183 variables...
ok, evaluated in 0.120823 s
trying with 184 variables...
ok, evaluated in 0.1199 s
trying with 185 variables...
ok, evaluated in 0.120102 s
trying with 186 variables...
ok, evaluated in 0.120403 s
trying with 187 variables...
ok, evaluated in 0.12764 s
trying with 188 variables...
ok, evaluated in 0.12582 s
trying with 189 variables...
ok, evaluated in 0.129507 s
trying with 190 variables...
ok, evaluated in 0.126094 s
trying with 191 variables...
ok, evaluated in 0.128977 s
trying with 192 variables...
ok, evaluated in 0.128711 s
trying with 193 variables...
ok, evaluated in 0.131378 s
trying with 194 variables...
ok, evaluated in 0.133373 s
trying with 195 variables...
ok, evaluated in 0.133713 s
trying with 196 variables...
ok, evaluated in 0.141943 s
trying with 197 variables...
ok, evaluated in 0.147794 s
trying with 198 variables...
ok, evaluated in 0.148291 s
trying with 199 variables...
ok, evaluated in 0.153758 s
trying with 200 variables...
ok, evaluated in 0.147025 s
trying with 201 variables...
ok, evaluated in 0.147795 s
trying with 202 variables...
ok, evaluated in 0.145289 s
trying with 203 variables...
ok, evaluated in 0.150942 s
trying with 204 variables...
ok, evaluated in 0.154106 s
trying with 205 variables...
ok, evaluated in 0.154846 s
trying with 206 variables...
ok, evaluated in 0.153266 s
trying with 207 variables...
ok, evaluated in 0.158937 s
trying with 208 variables...
ok, evaluated in 0.161894 s
trying with 209 variables...
ok, evaluated in 0.170068 s
trying with 210 variables...
ok, evaluated in 0.165477 s
trying with 211 variables...
ok, evaluated in 0.160324 s
trying with 212 variables...
ok, evaluated in 0.157777 s
trying with 213 variables...
ok, evaluated in 0.158717 s
trying with 214 variables...
ok, evaluated in 0.160258 s
trying with 215 variables...
ok, evaluated in 0.158752 s
trying with 216 variables...
ok, evaluated in 0.164663 s
trying with 217 variables...
ok, evaluated in 0.168016 s
trying with 218 variables...
ok, evaluated in 0.167177 s
trying with 219 variables...
ok, evaluated in 0.172997 s
trying with 220 variables...
ok, evaluated in 0.167339 s
trying with 221 variables...
ok, evaluated in 0.168459 s
trying with 222 variables...
ok, evaluated in 0.171857 s
trying with 223 variables...
ok, evaluated in 0.17171 s
trying with 224 variables...
ok, evaluated in 0.176155 s
trying with 225 variables...
ok, evaluated in 0.181217 s
trying with 226 variables...
ok, evaluated in 0.178267 s
trying with 227 variables...
ok, evaluated in 0.18764 s
trying with 228 variables...
ok, evaluated in 0.189209 s
trying with 229 variables...
ok, evaluated in 0.18326 s
trying with 230 variables...
ok, evaluated in 0.18879 s
trying with 231 variables...
ok, evaluated in 0.193517 s
trying with 232 variables...
ok, evaluated in 0.187022 s
trying with 233 variables...
ok, evaluated in 0.191354 s
trying with 234 variables...
ok, evaluated in 0.19718 s
trying with 235 variables...
ok, evaluated in 0.198361 s
trying with 236 variables...
ok, evaluated in 0.195098 s
trying with 237 variables...
ok, evaluated in 0.197281 s
trying with 238 variables...
ok, evaluated in 0.193372 s
trying with 239 variables...
ok, evaluated in 0.198586 s
trying with 240 variables...
ok, evaluated in 0.203288 s
trying with 241 variables...
ok, evaluated in 0.200123 s
trying with 242 variables...
ok, evaluated in 0.207537 s
trying with 243 variables...
ok, evaluated in 0.210578 s
trying with 244 variables...
ok, evaluated in 0.209189 s
trying with 245 variables...
ok, evaluated in 0.2124 s
trying with 246 variables...
ok, evaluated in 0.213917 s
trying with 247 variables...
ok, evaluated in 0.220931 s
trying with 248 variables...
ok, evaluated in 0.222058 s

**Comment by robbmcleod** [comment]
I made an addition to the FAQ for NumExpr 3 that explains how to work around this limitation for NumPy.
