### ISSUE TITLE
Test failure of 1.4.2 on 32bit platforms

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#72]
_From [a.valent...@gmail.com](https://code.google.com/u/113663911208750643682/) on February 15, 2012 21:30:41_

Unit tests fails on 32 bit platforms.

numexpr v. 1.4.2

The error is generated by the following code:

x = zeros(1e5)+.01   # checks issue #41 assert_equal(evaluate("sum(x+2,axis=0)"), sum(x+2,axis=0))

See also https://groups.google.com/group/numexpr/browse_thread/thread/bb777b53da34bbd0?hl=it Console output:

set -e -x;\
    for py in 2.6 2.7; do \
        cd /tmp/buildd/numexpr-1.4.2/build/lib._-$py;\
        env PYTHONPATH=. python$py numexpr/tests/test_numexpr.py;\
        cd /tmp/buildd/numexpr-1.4.2/build/lib._-$py-pydebug;\
        env PYTHONPATH=. python$py-dbg numexpr/tests/test_numexpr.py;\
    done
- cd /tmp/buildd/numexpr-1.4.2/build/lib.linux-i686-2.6
- env PYTHONPATH=. python2.6 numexpr/tests/test_numexpr.py
  ...F......F..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  .
  .
  .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  .
  .
  .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  .
  .
  .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  .
  .
  .....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  .
  .
  ....................................................................................................................................................-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  Numexpr version:   1.4.2
  NumPy version:     1.5.1
  Python version:    2.6.7 ( r267 :88850, Aug  3 2011, 15:19:01)
  [GCC 4.6.1]
  Platform:          linux2-i686
  AMD/Intel CPU?     True
  VML available?     False
  Detected cores:    1
  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
  ..
  ======================================================================
  FAIL: test_reductions (**main**.test_numexpr1)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
  File "numexpr/tests/test_numexpr.py", line 76, in test_reductions
    assert_equal(evaluate("sum(x+2,axis=0)"), sum(x+2,axis=0))
  File "/usr/lib/pymodules/python2.6/numpy/testing/utils.py", line 256,
  in assert_equal
  return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/lib/pymodules/python2.6/numpy/testing/utils.py", line 686,
  in assert_array_equal
  verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/pymodules/python2.6/numpy/t...

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=72_

**Comment by robbmcleod** [comment]
Untest-able, closing.
