### ISSUE TITLE
calculation of sum is slow and uses only one core

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#73]
_From [mimak...@gmail.com](https://code.google.com/u/107846061536121574655/) on February 19, 2012 03:06:02_
1. a = numpy.random.random((10000,10000))
2. numexpr.evaluate("sin(a) + exp(a) + log(a + 3)").sum() - fast, uses all cores 
3. numexpr.evaluate("sum(sin(a) + exp(a) + log(a + 3))") - slow, uses one core

I often use sum for expressions like sum(exp(a[:,None]*b[None,:])), where two vectors are passed to numexpr, and one number is an output. It would be great to avoid creation of an array a[:,None] \* b[None,:] at all. 

numexpr: 2.0.1, numpy:1.6.1, OS: ubuntu 11.04

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=73_

**Comment by kif** [comment]
Thanks for keeping the issue opened as it is still present.

**Comment by artpelling** [comment]
Any news on this issue? `evaluate('sum(X, 2)')` with X being a 4d `ndarray` is slower than NumPy and only uses one core for me.
