### ISSUE TITLE
Full support of Intel VML functions

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#74]
_From [astep...@gmail.com](https://code.google.com/u/115849668097078750829/) on February 21, 2012 14:11:39_

Numexpr is currently supporting a number of functions from the Intel Math libraries. 

For calculations involving statistics, peak analysis and other areas a full support of all functions from the VML mathematical functions would greatly enhance the versatility of numexpr. Especially the random number generators, error function, gamma function and rounding functions are still not supported.

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=74_

**Comment by mtrbean** [comment]
I am working on something that requires `gammaln` and `betaln` and I'm interested in adding support for these functions. I'm interested in contributing but will need some directions for me to get started

**Comment by FrancescAlted** [comment]
I think the best is to see how others added support for other functions.  Here you have a couple of examples:

https://github.com/pydata/numexpr/pull/125
https://github.com/pydata/numexpr/pull/135

I think the former is closer to what you want.

**Comment by mtrbean** [comment]
These functions are under `scipy.special`. Is it ok to have scipy as a dependency?

**Comment by gdementen** [comment]
Probably not (I would vote against it, but I am not the maintainer).
Besides, is there a C API for these functions? You cannot call a Python
function from numexpr (in a numexpr expression).

**Comment by FrancescAlted** [comment]
Yes, I agree with all @gdementen has expressed.

**Comment by robbmcleod** [comment]
Scipy has a pretty permissible license, so if the functions are implemented
in C one could more-or-less cut and paste them?

On Tue, Jun 14, 2016 at 11:22 AM, FrancescAlted <notifications@github.com>
wrote:

> Yes, I agree with all @gdementen <https://github.com/gdementen> has
> expressed.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pydata/numexpr/issues/74#issuecomment-225826437>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFuMmcyHfLfObKRcXLJYdHlKRL2x6la9ks5qLnLPgaJpZM4Bbm1v>
> .
>



-- 
Robert McLeod, Ph.D.
Center for Cellular Imaging and Nano Analytics (C-CINA)
Biozentrum der Universität Basel
Mattenstrasse 26, 4058 Basel
Work: +41.061.387.3225
robert.mcleod@unibas.ch
robert.mcleod@bsse.ethz.ch <robert.mcleod@ethz.ch>
robbmcleod@gmail.com

**Comment by FrancescAlted** [comment]
Yes, I don't see problems if the functions are in C and can be embedded in numexpr.  However, one thing that worries me is if there is much point in adding too much specific functions, and `gammaln` and `betaln` looks like they fall in this category.

**Comment by RoyiAvital** [comment]
By the way, if I install Anaconda's Numpy which comes with Intel MKL (Or any Numpy compiled with MKL), can `numexpr` use that for VML?

**Comment by gdementen** [comment]
@RoyiAvital This depends how your numexpr has been compiled. AFAIK, most recent versions of numexpr on Anaconda are linked against the MKL.

**Comment by gdementen** [comment]
@RoyiAvital I suppose the binaries on pypi were not linked against the MKL, so you will have to compile yourself. But since you are using anaconda, why don't you install numexpr from there too?

**Comment by RoyiAvital** [comment]
I can mange it by myself.
Just thought it would be easier to more users if it was offered on PIP linked to MKL.

I wish someone would make available on PIP all those MKL accelerated packages.

**Comment by RoyiAvital** [comment]
Is there a test to verify `numexpr` uses MKL (VML) on a given configuration?

**Comment by FrancescAlted** [comment]
Yes:

```
$ python -c"import numexpr; numexpr.print_versions()"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Numexpr version:   2.6.4
NumPy version:     1.14.2
Python version:    3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Platform:          darwin-x86_64
AMD/Intel CPU?     False
VML available?     True
VML/MKL version:   Intel(R) Math Kernel Library Version 2018.0.2 Product Build 20180127 for Intel(R) 64 architecture applications
Number of threads used by default: 4 (out of 4 detected cores)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Comment by rootsmusic** [comment]
Can the latest version still enable Intel VML?  [VML's README.md](https://github.com/intel/VML/blob/main/README.md) says, "This project will no longer be maintained by Intel."

When I run `numexpr.test()`, it outputs: "VML available? False".  However, I'm unsure if it's indicating my platform is missing that library or if numexpr hasn't enabled VML (and that library isn't missing).  Thanks.
