### ISSUE TITLE
failing unittests / crashes on GNU/Linux Debian sparc arch (in threaded mode)

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#77]
_From [yarikop...@gmail.com](https://code.google.com/u/106463979469591360865/) on April 09, 2012 20:34:26_

What steps will reproduce the problem? 1. happens with 1.4.2 and 2.0.1 (debian experimental)
2. on sparc boxes (but necessarily all of them)
3. some times just a test failure some times a crash, e.g. http://www.onerussian.com/tmp/numexpr-crash.txt Here is the script with rudimentary evaluate which reveals the failing tests and crash:

import numpy as np
from numpy.testing import *
from numpy import arange
import numexpr
from numexpr import E, NumExpr, evaluate, disassemble, use_vml
# numexpr.set_num_threads(1)

print "LIOOP"

for r in xrange(1000000000):
        x = arange(800000., 1e6)
        y = evaluate("x")
        print r
        if not np.all( x == y):
            print "FAILED on &#37;d run:" &#37; r
            print len(np.where (x!=y)[0])
            print (np.where (x!=y)[0])
            print x[x!=y]
            print (x-y)[x!=y]
            #import pdb; pdb.set_trace()
        #assert_array_equal(x, y)

if threading is disabled above -- then tests failures and crash goes away.

could you please advise on directions to troubleshoot?

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=77_

**Comment by robbmcleod** [comment]
This hasn't been addressed in four years, and the `sparc` platform still has pthreads disabled on 2.6, so closing.
