### ISSUE TITLE
numexpr.evaluate('(a*1j)+0') 

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#81]
_From [majid.al...@gmail.com](https://code.google.com/u/111269600501787951096/) on May 16, 2012 02:27:10_

numexpr.evaluate('(a*1j)+0')
gives
TypeError: no ordering relation is defined for complex numbers

ver 1.4.2

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=81_

**Comment by robbmcleod** [comment]
Fixed in 1812d9b, closing.
