### ISSUE TITLE
give option to use optimized object

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#84]
_From [majid.al...@gmail.com](https://code.google.com/u/111269600501787951096/) on June 01, 2012 00:21:30_

in my case i have a complicated expression i want to repeatedly give different inputs. the inefficiency is that each time it complies/optimizes the same expression.

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=84_

**Comment by robbmcleod** [comment]
This is possible in NE3.  Also in NE2 there was the `revaluate` patch awhile ago.
