### ISSUE TITLE
multidimensional output

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#85]
_From [jsw....@gmail.com](https://code.google.com/u/114215716443835783112/) on June 05, 2012 22:59:55_

This is an enhancement request.

I frequently need to create multidimensional histograms from data stored in PyTables, usually of variables computed from the various columns of the table.  tables.Expr is a very natural way to do this, but it is a bit cumbersome for multiple dimensions and I expect could be more efficient.  For instance:

```
histdata = array([
  tables.Expr("col1**2", vars(mytable.cols)),
  tables.Expr("col2 * (col3 + col4) * exp(col1*(3.84/400.))", vars(mytable.cols))
  tables.Expr("col5", vars(mytable.cols))])
hist, edges = histogramdd(histdata.T)
```

It would be really great, reducing either typing or code complexity, if I could instead generate a 2-dimensional array from just one numexpr call, like:

```
histdata = tables.Expr("[col1**2, col2 * (col3+col4), col5]", vars(mytable.cols))
hist, edges = histogramdd(histdata.T)
```

And I suspect that this would be more efficient as well.
Regards,
Jon

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=85_

**Comment by maedoc** [comment]
I'd also like to see this, for performance reasons. Is there a technical reason (not just lack of developer time) this feature isn't yet implemented?

**Comment by FrancescAlted** [comment]
I am not sure, but probably this could be done, yes.  Do you want to have it a try and send a pull request?
