### ISSUE TITLE
Add minimum, maximum functions

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#86]
_From [pierre.c...@gmail.com](https://code.google.com/u/105358803093019457519/) on June 07, 2012 16:43:59_

It would be useful to add np.mininum and np.maximum functions.
'maximum(x-a, 0)' would be faster and clearer than 'where(x-a>0,x-a,0)

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=86_

**Comment by Ablinne** [comment]
In the context of `min` and `max` I would also suggest to implement `clip`. While `clip(a,b,c)` is equivalent to `min(max(a,b),c)`, the former is easier to read.

**Comment by vallsv** [comment]
+1 for `minimum` and `clip`

But at least i am happy to read that i can use this `where` function.

**Comment by wilko339** [comment]
Just found this thread still open. Any progress?

**Comment by robbmcleod** [comment]
Min and max were implemented awhile ago. There is no room left for more opcodes, so clip cannot be implemented in NumExpr 2.7. I do believe `numexpr3` could have `clip` implemented.

**Comment by vallsv** [comment]
Really! That's super nice. How can we use it?

I tried all this sentences:
```
a = numpy.array([2,3,4])
b = numpy.array([3,2,4])

> numexpr.evaluate("min(a,2)")
ValueError: reduction axis is out of bounds

> numexpr.evaluate("min(a,b)")
TypeError: You can't use Python's standard boolean operators in NumExpr expressions. You should use their bitwise counterparts instead: '&' instead of 'and', '|' instead of 'or', and '~' instead of 'not'.

> numexpr.evaluate("minimum(a,2)")
TypeError: 'VariableNode' object is not callable

> numexpr.evaluate("a.min(b)")
AttributeError: 'VariableNode' object has no attribute 'min'
```

**Comment by robbmcleod** [comment]
Oh, sorry, they are reductions.

Element-wise could be done for `float32` and `float64` but not for integers.

**Comment by sebbelese** [comment]
Hi,

Sorry if I misunderstood: does it mean that element-wise min and max should work with float32 and float64 arrays? I tried @vallsv expressions with a and b as float arrays, but got the same issue as for integer.

Are element-wise min and max implemented, and do you have an example?

Thanks

**Comment by robbmcleod** [comment]
Element-wise are not implemented at this time. However, you can use the `where` function instead. It's just uglier.

**Comment by shubham2941** [comment]
> Really! That's super nice. How can we use it?
> 
> I tried all this sentences:
> 
> ```
> a = numpy.array([2,3,4])
> b = numpy.array([3,2,4])
> 
> > numexpr.evaluate("min(a,2)")
> ValueError: reduction axis is out of bounds
> 
> > numexpr.evaluate("min(a,b)")
> TypeError: You can't use Python's standard boolean operators in NumExpr expressions.
> You should use their bitwise counterparts instead: '&' instead of 'and', '|' instead of 'or',
> and '~' instead of 'not'.
> 
> > numexpr.evaluate("minimum(a,2)")
> TypeError: 'VariableNode' object is not callable
> 
> > numexpr.evaluate("a.min(b)")
> AttributeError: 'VariableNode' object has no attribute 'min'
> 
> > numexpr.version.version                                                        
> '2.7.1'
> ```

Hi,
Is there a way to use all these in the current version of numexpr? I tried these and same error appears.

**Comment by robbmcleod** [comment]
Such as this:

    import numexpr as ne
    import numpy as np

    a = np.array([2,3,4])
    b = np.array([3,2,4])

    out1 = ne.evaluate('where(a < 2, a, 2)')
    out2 = ne.evaluate('where(a < b, a, b)')

**Comment by shubham2941** [comment]
Thanks, @robbmcleod. I somehow missed that function earlier. 

Is there a way to define your own operator in numexpr? For eg., if you want to do multiple operations on two parameters in a user-defined function. If there is a post somewhere or some documentation, can someone point to it? Any suggestions is welcome.

**Comment by robbmcleod** [comment]
No, I'd suggest you look at `numba` for such a task.

**Comment by shubham2941** [comment]
I am not sure how to use numba with numexpr.evaluate and user-defined function.

Let me explain my issue with numexpr.evaluate in detail:

I have a string function in the form with data in variables A and B in data dictionary form:
`
               def ufunc(A,B):
                     ............
                     return var
`
The evaluation function goes like this:
`
               numexpr.evaluate( 'A + B**2 + A*B + sin(A) + ufunc(A,B)' , data_dict)
`
The problem is I don't how to send the 'ufunc' information to 'numexpr.evaluate'. I am not sure how 'numba' will help with that.

**Comment by josedaniel-escribano-clarity** [comment]
I was evaluating this library and not having min or max operator is a big negative aspect... is there any plan to implement them? It's very strange not using min or max in the formula and have to use the where function.
