### ISSUE TITLE
Add np.sign function

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#87]
_From [pierre.c...@gmail.com](https://code.google.com/u/105358803093019457519/) on June 07, 2012 16:48:28_

I'd like to use numexpr to calculate soft thresholding:
np.sign(x) \* np.maximum(abs(x)-l, 0)

in numexpr, one might want to use std::copysign as an optimisation, but that's another matter.

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=87_

**Comment by robbmcleod** [comment]
We have `copysign()` and `signbit()` in NE3 which should be sufficient for the moment.

**Comment by WarrenWeckesser** [comment]
> We have copysign() and signbit() in NE3 which should be sufficient for the moment.

Is NE3 an unreleased version 3 of numexpr?

Is there an equivalent to `numpy.sign` (perhaps restricted to real arguments) in numexpr 2?

**Comment by WarrenWeckesser** [comment]
> Is NE3 an unreleased version 3 of numexpr?

Nevermind, I found the 3.0 branch.

**Comment by robbmcleod** [comment]
NE3 is sort of in a beta-state because it has some regressions (no string handling, no reductions) and I've had trouble finding the energy to work on it further.
