### ISSUE TITLE
Add np.trunc, np.ceil equivalents

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#89]
_From [pierre.c...@gmail.com](https://code.google.com/u/105358803093019457519/) on June 26, 2012 11:12:12_

This is a request for enhancement.
Summary says it all.

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=89_

**Comment by robbmcleod** [comment]
`floor()`, `ceil()`, and `trunc()` are all present in NE3 and tests show equivalence to their NumPy counterparts.
