### ISSUE TITLE
 ImportError: cannot import name _get_vml_version

### ISSUE THREAD

**Issue by FrancescAlted** [pydata/numexpr#90]
_From [G.G.S...@gmail.com](https://code.google.com/u/114517590074567208682/) on July 25, 2012 03:21:07_

What steps will reproduce the problem? Compiling numexpr_2.0.1 with mkl_10.3.11.339

Here is the site.cfg:

[mkl]
library_dirs = /opt/intel/mkl/lib/intel64
include_dirs = /opt/intel/mkl/include
mkl_libs = mkl_gf_lp64, mkl_gnu_thread, mkl_core, iomp5

Build step says:

mkl_info:
  FOUND:
    libraries = ['mkl_gf_lp64', 'mkl_gnu_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/opt/intel/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None)]
    include_dirs = ['/opt/intel/mkl/include']

After installation, I start python, try to import numexpr, and I get:

Python 2.7.1+ ( r271 :86832, Apr 11 2011, 18:13:53) 
[GCC 4.5.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import numexpr
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/numexpr-2.0.1-py2.7-linux-x86_64.egg/numexpr/**init**.py", line 39, in <module>
> > >     from numexpr.necompiler import NumExpr, disassemble, evaluate
> > >   File "/usr/local/lib/python2.7/dist-packages/numexpr-2.0.1-py2.7-linux-x86_64.egg/numexpr/necompiler.py", line 16, in <module>
> > >     from numexpr.utils import CacheDict
> > >   File "/usr/local/lib/python2.7/dist-packages/numexpr-2.0.1-py2.7-linux-x86_64.egg/numexpr/utils.py", line 17, in <module>
> > >     from numexpr.interpreter import (
> > > ImportError: cannot import name _get_vml_version

System:Ubuntu 11.04 64-bit

_Original issue: http://code.google.com/p/numexpr/issues/detail?id=90_

**Comment by robbmcleod** [comment]
This is long gone, protected by `try` statements.
